import type { ChapterId, Difficulty, Recipe } from './types';

/**
 * Jia's growing recipe collection. These use a small builder (`r`) so each
 * entry stays short and readable while still producing a full `Recipe`. The
 * flagship recipes in data.ts show the verbose object form; both are valid —
 * see USER_GUIDE.md. Heroes fall back to generated art until photos are added.
 */

type Tup = [number | null, string, string, string?]; // [qty, unit, item, note?]
type St = string | [string, number]; // instruction | [instruction, timerSeconds]

interface Mini {
  id: string;
  chapter: ChapterId;
  title: string;
  tagline: string;
  story: string;
  tasteLike: string;
  texture: string;
  cuisine: string;
  difficulty: Difficulty;
  spice?: number;
  allergens?: string[];
  prep: number;
  cook: number;
  servings: number;
  cal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  tags: string[];
  ing: Tup[];
  steps: St[];
  tips?: string[];
  related?: string[];
  seed: number;
}

function r(x: Mini): Recipe {
  return {
    id: x.id,
    chapter: x.chapter,
    title: x.title,
    tagline: x.tagline,
    story: x.story,
    tasteLike: x.tasteLike,
    texture: x.texture,
    cuisine: x.cuisine,
    difficulty: x.difficulty,
    spiceLevel: x.spice ?? 0,
    allergens: x.allergens ?? [],
    prepMin: x.prep,
    cookMin: x.cook,
    servings: x.servings,
    nutrition: {
      calories: x.cal,
      protein: x.protein,
      carbs: x.carbs,
      fat: x.fat,
      fiber: x.fiber ?? 2,
      sugar: x.sugar ?? 4,
    },
    tags: x.tags,
    ingredients: [{ items: x.ing.map(([q, u, it, n]) => ({ quantity: q, unit: u, item: it, note: n })) }],
    steps: x.steps.map((s) => (Array.isArray(s) ? { instruction: s[0], durationSec: s[1] } : { instruction: s })),
    tips: x.tips,
    related: x.related,
    heroSeed: x.seed,
  };
}

/* ── Shared building blocks (keep the biryanis DRY) ───────────────────────*/
const RICE: Tup[] = [
  [500, 'g', 'basmati rice', 'soaked 30 min'],
  [4, '', 'green cardamom pods'],
  [1, '', 'cinnamon stick'],
  [2, 'tbsp', 'salt', 'for parboiling'],
];

export const EXTRA_RECIPES: Recipe[] = [
  /* ═══════════════════ BREADS ═══════════════════ */
  r({
    id: 'simple-bread',
    chapter: 'breads',
    title: 'Simple Bread',
    tagline: 'One loaf, five ingredients, endless comfort.',
    story: 'The first bread I ever baked. If you can stir, you can make this — start here and you’ll never fear dough again. I keep the ingredients list short on purpose. Flavour comes from heat and patience.',
    tasteLike: 'Mild, wheaty and faintly sweet.',
    texture: 'Soft crumb under a crackly crust.',
    cuisine: 'Home',
    difficulty: 'easy',
    prep: 20,
    cook: 35,
    servings: 10,
    cal: 180,
    protein: 6,
    carbs: 34,
    fat: 2,
    tags: ['bread', 'staple', 'vegetarian'],
    allergens: ['gluten'],
    ing: [
      [500, 'g', 'strong bread flour'],
      [7, 'g', 'instant yeast'],
      [10, 'g', 'salt'],
      [320, 'ml', 'warm water'],
      [1, 'tbsp', 'olive oil'],
    ],
    steps: [
      'Mix flour, yeast and salt. Add water and oil; bring together into a shaggy dough.',
      ['Knead until smooth and springy.', 600],
      ['Cover and let rise until doubled.', 3600],
      'Shape into a loaf, prove again 40 minutes, then slash the top.',
      ['Bake at 220°C until deep gold and hollow-sounding.', 2100],
    ],
    tips: ['A tray of water in the oven gives a crisper crust.'],
    related: ['sourdough-focaccia', 'simple-buns'],
    seed: 101,
  }),
  r({
    id: 'simple-buns',
    chapter: 'breads',
    title: 'Simple Buns',
    tagline: 'Soft, pillowy rolls for any table.',
    story: 'I make a tray of these for every family dinner — they vanish before the mains arrive. The version in my head is louder with spice — dial to your table.',
    tasteLike: 'Buttery and lightly sweet.',
    texture: 'Fluffy and tear-apart tender.',
    cuisine: 'Home',
    difficulty: 'easy',
    prep: 25,
    cook: 20,
    servings: 9,
    cal: 210,
    protein: 6,
    carbs: 32,
    fat: 6,
    sugar: 6,
    tags: ['bread', 'soft', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [450, 'g', 'bread flour'],
      [7, 'g', 'instant yeast'],
      [40, 'g', 'sugar'],
      [1, '', 'egg'],
      [200, 'ml', 'warm milk'],
      [50, 'g', 'soft butter'],
      [1, 'tsp', 'salt'],
    ],
    steps: [
      'Mix everything into a soft dough; knead until it passes the windowpane test.',
      ['Rise until doubled.', 3600],
      'Divide into 9, roll tight, and nestle in a square tin. Prove 40 minutes.',
      'Brush with egg wash.',
      ['Bake at 190°C until golden and shiny.', 1200],
    ],
    tips: ['Brush the tops with butter the moment they leave the oven for a soft crust.'],
    related: ['simple-bread', 'cinnamon-rolls'],
    seed: 102,
  }),
  r({
    id: 'cinnamon-sugar-bun',
    chapter: 'breads',
    title: 'Cinnamon Sugar Bun',
    tagline: 'Soft buns rolled in cinnamon sugar.',
    story: 'A lazy-Sunday treat — all the cosiness of cinnamon rolls with none of the fuss. Serve it hot, with something cool on the side if you have it.',
    tasteLike: 'Sweet, warm and spiced.',
    texture: 'Soft and sugary-crisp on top.',
    cuisine: 'Home',
    difficulty: 'easy',
    prep: 25,
    cook: 20,
    servings: 9,
    cal: 240,
    protein: 6,
    carbs: 38,
    fat: 7,
    sugar: 14,
    tags: ['sweet', 'breakfast', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [450, 'g', 'bread flour'],
      [7, 'g', 'instant yeast'],
      [50, 'g', 'sugar'],
      [200, 'ml', 'warm milk'],
      [1, '', 'egg'],
      [50, 'g', 'butter'],
      [3, 'tbsp', 'cinnamon sugar', 'to coat'],
    ],
    steps: [
      'Make a soft enriched dough and let it rise until doubled.',
      ['First rise.', 3600],
      'Shape into balls, prove, and bake at 190°C until golden.',
      ['Bake.', 1200],
      'While warm, brush with melted butter and roll in cinnamon sugar.',
    ],
    tips: ['Coat them warm — the butter helps the sugar cling.'],
    related: ['cinnamon-rolls', 'simple-buns'],
    seed: 103,
  }),

  /* ═══════════════════ BAKING ═══════════════════ */
  r({
    id: 'simple-tea-cake',
    chapter: 'baking',
    title: 'Simple Tea Cake',
    tagline: 'A plain, perfect cake for chai time.',
    story: 'Nothing fancy — the cake I keep under a dome for whoever drops by with news. Serve it hot, with something cool on the side if you have it.',
    tasteLike: 'Buttery vanilla, gently sweet.',
    texture: 'Tender, close crumb.',
    cuisine: 'Home',
    difficulty: 'easy',
    prep: 15,
    cook: 40,
    servings: 8,
    cal: 300,
    protein: 5,
    carbs: 40,
    fat: 14,
    sugar: 22,
    tags: ['sweet', 'teatime', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [200, 'g', 'butter', 'soft'],
      [200, 'g', 'caster sugar'],
      [4, '', 'eggs'],
      [200, 'g', 'self-raising flour'],
      [1, 'tsp', 'vanilla'],
    ],
    steps: [
      ['Cream butter and sugar until pale and fluffy.', 240],
      'Beat in eggs one at a time, then vanilla.',
      'Fold in the flour gently.',
      ['Bake at 170°C until a skewer comes out clean.', 2400],
    ],
    tips: ['Room-temperature eggs stop the batter curdling.'],
    related: ['vanilla-cake', 'masala-chai'],
    seed: 104,
  }),
  r({
    id: 'vanilla-cake',
    chapter: 'baking',
    title: 'Vanilla Cake',
    tagline: 'The birthday classic, done right.',
    story: 'My go-to celebration cake — soft, moist, and happy to wear any frosting. Smell tells you when it’s ready more than any clock will.',
    tasteLike: 'Pure sweet vanilla.',
    texture: 'Moist and fluffy.',
    cuisine: 'American',
    difficulty: 'medium',
    prep: 20,
    cook: 30,
    servings: 10,
    cal: 340,
    protein: 5,
    carbs: 48,
    fat: 15,
    sugar: 30,
    tags: ['sweet', 'celebration', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [250, 'g', 'flour'],
      [250, 'g', 'sugar'],
      [200, 'g', 'butter'],
      [4, '', 'eggs'],
      [2, 'tsp', 'baking powder'],
      [120, 'ml', 'milk'],
      [2, 'tsp', 'vanilla'],
    ],
    steps: [
      ['Cream butter and sugar until light.', 240],
      'Add eggs, then alternate flour + baking powder with the milk.',
      'Stir in vanilla; divide between two tins.',
      ['Bake at 175°C until springy.', 1800],
      'Cool fully before frosting.',
    ],
    tips: ['Weigh, don’t scoop — cake is chemistry.'],
    related: ['chocolate-cake', 'cupcakes'],
    seed: 105,
  }),
  r({
    id: 'chocolate-cake',
    chapter: 'baking',
    title: 'Chocolate Cake',
    tagline: 'Deep, dark, and dangerously moist.',
    story: 'The cake people ask me to bring. Hot coffee in the batter is my not-so-secret secret. Write the timings on a sticky if you must; the method is forgiving.',
    tasteLike: 'Rich cocoa with a fudgy edge.',
    texture: 'Moist and dense.',
    cuisine: 'American',
    difficulty: 'medium',
    prep: 20,
    cook: 35,
    servings: 10,
    cal: 380,
    protein: 6,
    carbs: 50,
    fat: 18,
    sugar: 34,
    tags: ['sweet', 'chocolate', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [200, 'g', 'flour'],
      [250, 'g', 'sugar'],
      [75, 'g', 'cocoa powder'],
      [2, '', 'eggs'],
      [120, 'ml', 'oil'],
      [200, 'ml', 'hot coffee'],
      [1.5, 'tsp', 'baking soda'],
    ],
    steps: [
      'Whisk the dry ingredients, then the wet, then combine — batter will be thin.',
      'Pour in the hot coffee last and whisk smooth.',
      ['Bake at 175°C until a skewer is just clean.', 2100],
      'Cool, then blanket in chocolate ganache.',
    ],
    tips: ['Thin batter is right — it bakes up beautifully moist.'],
    related: ['triple-choc-brownies', 'chocolate-orange-swirl'],
    seed: 106,
  }),
  r({
    id: 'chocolate-orange-swirl',
    chapter: 'baking',
    title: 'Chocolate Orange Swirl Cupcakes',
    tagline: 'Two batters, one marbled loaf.',
    story: 'Chocolate and orange are old friends. Don’t over-swirl — you want ribbons, not mud. I cook it the way I want to eat it — honest portions, no ceremony.',
    tasteLike: 'Bittersweet cocoa with bright orange.',
    texture: 'Buttery pound-cake crumb.',
    cuisine: 'Home',
    difficulty: 'medium',
    prep: 25,
    cook: 45,
    servings: 8,
    cal: 350,
    protein: 5,
    carbs: 44,
    fat: 17,
    sugar: 26,
    tags: ['sweet', 'chocolate', 'citrus', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [220, 'g', 'butter'],
      [220, 'g', 'sugar'],
      [4, '', 'eggs'],
      [240, 'g', 'flour'],
      [2, 'tsp', 'baking powder'],
      [3, 'tbsp', 'cocoa powder'],
      [1, '', 'orange', 'zest + 2 tbsp juice'],
    ],
    steps: [
      'Make one plain batter; split it. Flavour one half with cocoa, the other with orange.',
      'Spoon alternately into a loaf tin.',
      'Draw a skewer through once or twice to marble.',
      ['Bake at 170°C until a skewer comes out clean.', 2700],
    ],
    tips: ['Swirl minimally — two passes is plenty.'],
    related: ['chocolate-cake', 'simple-tea-cake'],
    seed: 107,
  }),
  r({
    id: 'cupcakes',
    chapter: 'baking',
    title: 'Cupcakes',
    tagline: 'Little cakes, big smiles.',
    story: 'The recipe I bake with the kids — small hands, big frosting swirls, flour everywhere. Don’t rush the last minute; that’s where it turns from fine to lovely.',
    tasteLike: 'Sweet vanilla sponge.',
    texture: 'Light and tender.',
    cuisine: 'American',
    difficulty: 'easy',
    prep: 20,
    cook: 20,
    servings: 12,
    cal: 260,
    protein: 4,
    carbs: 36,
    fat: 12,
    sugar: 24,
    tags: ['sweet', 'kid-friendly', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [150, 'g', 'butter'],
      [150, 'g', 'sugar'],
      [3, '', 'eggs'],
      [150, 'g', 'self-raising flour'],
      [1, 'tsp', 'vanilla'],
    ],
    steps: [
      ['Cream butter and sugar; beat in eggs and vanilla.', 180],
      'Fold in flour and divide into 12 cases.',
      ['Bake at 180°C until springy.', 1200],
      'Cool fully, then pipe buttercream.',
    ],
    tips: ['Fill cases two-thirds — they need room to dome.'],
    related: ['vanilla-cake', 'brownies-cupcakes'],
    seed: 108,
  }),
  r({
    id: 'cinnamon-rolls',
    chapter: 'baking',
    title: 'Cinnamon Rolls',
    tagline: 'Soft spirals under cream-cheese glaze.',
    story: 'Worth the wait every single time. Roll them tight and don’t skimp on the glaze while they’re warm. If you’re tired, still make this — it’s kinder than takeaway and nearly as fast.',
    tasteLike: 'Sweet, buttery, cinnamon-warm.',
    texture: 'Gooey-soft, sticky-topped.',
    cuisine: 'American',
    difficulty: 'medium',
    prep: 40,
    cook: 25,
    servings: 9,
    cal: 380,
    protein: 7,
    carbs: 56,
    fat: 14,
    sugar: 28,
    tags: ['sweet', 'breakfast', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [500, 'g', 'bread flour'],
      [7, 'g', 'yeast'],
      [60, 'g', 'sugar'],
      [250, 'ml', 'warm milk'],
      [1, '', 'egg'],
      [60, 'g', 'butter'],
      [100, 'g', 'brown sugar', 'for filling'],
      [2, 'tbsp', 'cinnamon'],
    ],
    steps: [
      'Make a soft enriched dough; rise until doubled.',
      ['First rise.', 3600],
      'Roll into a rectangle, spread butter, brown sugar and cinnamon; roll up and cut.',
      'Nestle in a tin, prove 45 minutes.',
      ['Bake at 180°C until golden.', 1500],
      'Glaze with cream-cheese icing while warm.',
    ],
    tips: ['Use unflavoured floss to cut clean rolls without squashing them.'],
    related: ['cinnamon-sugar-bun', 'simple-buns'],
    seed: 109,
  }),
  r({
    id: 'brownies-cupcakes',
    chapter: 'baking',
    title: 'Brownies',
    tagline: 'Fudgy brownies in a cupcake coat.',
    story: 'For when you can’t decide between brownie and cupcake — so you don’t. This one earns its page: simple enough for a Tuesday, proud enough for guests.',
    tasteLike: 'Intense chocolate, barely sweet.',
    texture: 'Fudgy centre, crackly top.',
    cuisine: 'American',
    difficulty: 'easy',
    prep: 15,
    cook: 22,
    servings: 12,
    cal: 300,
    protein: 5,
    carbs: 34,
    fat: 17,
    sugar: 24,
    tags: ['sweet', 'chocolate', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [200, 'g', 'dark chocolate'],
      [150, 'g', 'butter'],
      [200, 'g', 'sugar'],
      [3, '', 'eggs'],
      [100, 'g', 'flour'],
      [30, 'g', 'cocoa'],
    ],
    steps: [
      'Melt chocolate and butter together; cool slightly.',
      'Whisk in sugar, then eggs, then fold flour and cocoa.',
      'Divide into 12 cases.',
      ['Bake at 175°C until the tops just set.', 1320],
    ],
    tips: ['Pull them while the centres look underdone — they firm as they cool.'],
    related: ['triple-choc-brownies', 'cupcakes'],
    seed: 110,
  }),
  r({
    id: 'triple-choc-brownies',
    chapter: 'baking',
    title: 'Triple Chocolate Brownies',
    tagline: 'Dark, milk, and white — all at once.',
    story: 'The fudgiest brownies I make. Three chocolates sounds greedy; it is, and it’s worth it. I learned this by burning one batch and loving the next.',
    tasteLike: 'Deeply chocolatey, rich and sweet.',
    texture: 'Dense, fudgy, chunk-studded.',
    cuisine: 'American',
    difficulty: 'easy',
    prep: 15,
    cook: 30,
    servings: 16,
    cal: 320,
    protein: 4,
    carbs: 36,
    fat: 18,
    sugar: 28,
    tags: ['sweet', 'chocolate', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [200, 'g', 'dark chocolate'],
      [175, 'g', 'butter'],
      [250, 'g', 'sugar'],
      [3, '', 'eggs'],
      [120, 'g', 'flour'],
      [100, 'g', 'milk & white chocolate chunks'],
    ],
    steps: [
      'Melt dark chocolate with butter; cool a little.',
      'Whisk sugar and eggs to a thick, pale ribbon, then fold in the chocolate.',
      'Fold flour and the chunks; spread in a lined tin.',
      ['Bake at 170°C until set at the edges but soft in the middle.', 1800],
    ],
    tips: ['Chill before slicing for clean, sharp squares.'],
    related: ['chocolate-cake', 'brownies-cupcakes'],
    seed: 111,
  }),
  r({
    id: 'choc-chip-cookies',
    chapter: 'baking',
    title: 'Chocolate Chip Cookies',
    tagline: 'Crisp edges, chewy middles.',
    story: 'Browned butter and a rest in the fridge — the two steps that make people ask for the recipe. I learned this by burning one batch and loving the next.',
    tasteLike: 'Buttery, toffee-sweet, chocolatey.',
    texture: 'Crisp rim, chewy centre.',
    cuisine: 'American',
    difficulty: 'easy',
    prep: 20,
    cook: 12,
    servings: 18,
    cal: 210,
    protein: 3,
    carbs: 26,
    fat: 11,
    sugar: 16,
    tags: ['sweet', 'chocolate', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [170, 'g', 'butter', 'browned'],
      [150, 'g', 'brown sugar'],
      [80, 'g', 'white sugar'],
      [1, '', 'egg'],
      [260, 'g', 'flour'],
      [200, 'g', 'chocolate chips'],
      [0.5, 'tsp', 'baking soda'],
    ],
    steps: [
      'Brown the butter and cool it. Beat with both sugars, then the egg.',
      'Fold in flour, soda and chips.',
      ['Chill the dough.', 3600],
      'Scoop onto trays.',
      ['Bake at 180°C until the edges set but centres look soft.', 720],
    ],
    tips: ['A flaky-salt pinch on top before baking makes them sing.'],
    related: ['double-choc-cookies', 'triple-choc-brownies'],
    seed: 112,
  }),
  r({
    id: 'double-choc-cookies',
    chapter: 'baking',
    title: 'Double Chocolate Cookies',
    tagline: 'Chocolate dough, chocolate chunks.',
    story: 'For the days only chocolate will do. Slightly underbake them — that’s the whole trick. The version in my head is louder with spice — dial to your table.',
    tasteLike: 'Deep cocoa, molten pockets.',
    texture: 'Soft and brownie-like.',
    cuisine: 'American',
    difficulty: 'easy',
    prep: 20,
    cook: 11,
    servings: 16,
    cal: 230,
    protein: 4,
    carbs: 28,
    fat: 12,
    sugar: 18,
    tags: ['sweet', 'chocolate', 'vegetarian'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [170, 'g', 'butter'],
      [200, 'g', 'brown sugar'],
      [1, '', 'egg'],
      [200, 'g', 'flour'],
      [50, 'g', 'cocoa'],
      [200, 'g', 'dark chocolate chunks'],
      [0.5, 'tsp', 'baking soda'],
    ],
    steps: [
      'Cream butter and sugar; beat in the egg.',
      'Fold flour, cocoa, soda and chunks.',
      'Scoop onto trays.',
      ['Bake at 180°C until just set at the edges.', 660],
    ],
    tips: ['They look underdone at 11 minutes — that’s exactly right.'],
    related: ['choc-chip-cookies', 'chocolate-cake'],
    seed: 113,
  }),

  /* ═══════════════════ DESSERTS ═══════════════════ */
  r({
    id: 'oreo-custard-crunch',
    chapter: 'desserts',
    title: 'Oreo, Custard Crunch',
    tagline: 'Layers of custard, cream and crushed Oreo.',
    story: 'My cheat’s trifle — no baking, endlessly popular, gone in one sitting. This one earns its page: simple enough for a Tuesday, proud enough for guests.',
    tasteLike: 'Creamy vanilla against cocoa crunch.',
    texture: 'Silky custard, crunchy rubble.',
    cuisine: 'Home',
    difficulty: 'easy',
    prep: 25,
    cook: 10,
    servings: 8,
    cal: 340,
    protein: 6,
    carbs: 44,
    fat: 16,
    sugar: 32,
    tags: ['sweet', 'no-bake', 'vegetarian'],
    allergens: ['dairy', 'gluten'],
    ing: [
      [1, 'l', 'milk'],
      [4, 'tbsp', 'custard powder'],
      [6, 'tbsp', 'sugar'],
      [300, 'ml', 'whipped cream'],
      [2, 'packs', 'Oreos', 'crushed'],
    ],
    steps: [
      ['Cook custard with milk and sugar until thick; cool with cling on the surface.', 600],
      'Layer crushed Oreos, custard, then cream. Repeat.',
      'Finish with an Oreo-crumb top.',
      ['Chill before serving.', 10800],
    ],
    tips: ['Assemble a few hours ahead so the layers set and slice cleanly.'],
    related: ['kheer', 'tiramisu'],
    seed: 114,
  }),
  r({
    id: 'kheer',
    chapter: 'desserts',
    title: 'Kheer',
    tagline: 'Slow-cooked rice pudding, perfumed with cardamom.',
    story: 'The dessert of every celebration in my family. Low and slow is the only way — don’t rush the milk. This one earns its page: simple enough for a Tuesday, proud enough for guests.',
    tasteLike: 'Creamy, milky-sweet, fragrant.',
    texture: 'Thick and spoon-coating.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    prep: 10,
    cook: 60,
    servings: 6,
    cal: 260,
    protein: 7,
    carbs: 40,
    fat: 8,
    sugar: 28,
    tags: ['sweet', 'festive', 'vegetarian'],
    allergens: ['dairy', 'nuts'],
    ing: [
      [1.5, 'l', 'full-fat milk'],
      [80, 'g', 'basmati rice', 'soaked'],
      [120, 'g', 'sugar'],
      [4, '', 'cardamom pods'],
      [2, 'tbsp', 'chopped pistachios & almonds'],
    ],
    steps: [
      'Simmer milk with the cardamom.',
      ['Add rice and cook low, stirring often, until soft and thickened.', 3000],
      'Stir in sugar and half the nuts; cook a few minutes more.',
      'Serve warm or chilled, topped with the rest of the nuts.',
    ],
    tips: ['Stir the base often so it never catches and scorches.'],
    related: ['gulab-jamun', 'masala-chai'],
    seed: 115,
  }),
  r({
    id: 'balushahi',
    chapter: 'desserts',
    title: 'Balushai',
    tagline: 'Flaky fried rings in sugar syrup.',
    story: 'My grandmother’s Eid sweet. The dough must stay shaggy and the frying slow — patience makes the flakes. Serve it hot, with something cool on the side if you have it.',
    tasteLike: 'Sweet, buttery, syrup-soaked.',
    texture: 'Crisp-flaky outside, soft within.',
    cuisine: 'Pakistani',
    difficulty: 'hard',
    prep: 30,
    cook: 40,
    servings: 12,
    cal: 300,
    protein: 3,
    carbs: 44,
    fat: 13,
    sugar: 30,
    tags: ['sweet', 'festive', 'fried', 'vegetarian'],
    allergens: ['gluten', 'dairy'],
    ing: [
      [300, 'g', 'flour'],
      [80, 'g', 'ghee'],
      [3, 'tbsp', 'yogurt'],
      [0.25, 'tsp', 'baking soda'],
      [400, 'g', 'sugar', 'for syrup'],
      [null, '', 'oil', 'to fry'],
    ],
    steps: [
      'Rub ghee into flour and soda, then bring together with yogurt into a soft, shaggy dough. Rest.',
      ['Rest the dough.', 1800],
      'Make a one-string sugar syrup and keep warm.',
      ['Shape rings and fry very slowly on low heat until deep gold.', 1800],
      'Soak the hot rings in warm syrup, then lift out to set.',
    ],
    tips: ['Fry on low — high heat browns the outside before the inside flakes.'],
    related: ['gulab-jamun', 'kheer'],
    seed: 116,
  }),
  r({
    id: 'gulab-jamun',
    chapter: 'desserts',
    title: 'Gulab Jamun',
    tagline: 'Soft milk dumplings drenched in rose syrup.',
    story: 'No family gathering is complete without these. Fry them gently and let them drink the syrup slowly. Write the timings on a sticky if you must; the method is forgiving.',
    tasteLike: 'Intensely sweet, rose and cardamom.',
    texture: 'Melt-soft, syrup-heavy.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    prep: 20,
    cook: 30,
    servings: 14,
    cal: 220,
    protein: 4,
    carbs: 34,
    fat: 8,
    sugar: 28,
    tags: ['sweet', 'festive', 'fried', 'vegetarian'],
    allergens: ['dairy', 'gluten'],
    ing: [
      [200, 'g', 'milk powder'],
      [60, 'g', 'flour'],
      [0.25, 'tsp', 'baking soda'],
      [3, 'tbsp', 'ghee'],
      [80, 'ml', 'milk'],
      [500, 'g', 'sugar', 'for syrup'],
      [4, '', 'cardamom pods'],
    ],
    steps: [
      'Make a soft dough from milk powder, flour, soda, ghee and milk. Rest briefly.',
      'Simmer sugar, water and cardamom into a light syrup; keep warm.',
      'Roll crack-free balls.',
      ['Fry very gently on low until even deep brown.', 600],
      ['Drop hot into warm syrup and soak.', 1800],
    ],
    tips: ['Smooth, crack-free balls won’t split in the oil.'],
    related: ['balushahi', 'kheer'],
    seed: 117,
  }),

  /* ═══════════════════ PAKISTANI — BIRYANI ═══════════════════ */
  ...biryani('saadi', 'chicken', 201),
  ...biryani('sindhi', 'chicken', 202),
  ...biryani('zaffarani', 'chicken', 203),
  ...biryani('saadi', 'mutton', 204),
  ...biryani('sindhi', 'mutton', 205),
  ...biryani('zaffarani', 'mutton', 206),
  ...biryani('saadi', 'beef', 207),
  ...biryani('sindhi', 'beef', 208),
  ...biryani('zaffarani', 'beef', 209),

  /* ═══════════════════ PAKISTANI — CURRIES ═══════════════════ */
  r({
    id: 'karahi-chicken',
    chapter: 'pakistani',
    title: 'Karahi (Chicken)',
    tagline: 'Tomato, ginger and green chili in a blazing wok.',
    story: 'The dish that tastes of a dhaba by the roadside. Cook it hard and fast, and finish with lots of ginger. I learned this by burning one batch and loving the next.',
    tasteLike: 'Tangy tomato, fiery, ginger-bright.',
    texture: 'Tender chicken in a clinging masala.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 4,
    prep: 15,
    cook: 30,
    servings: 4,
    cal: 420,
    protein: 34,
    carbs: 10,
    fat: 26,
    tags: ['savory', 'spicy', 'karahi'],
    ing: [
      [800, 'g', 'chicken', 'bone-in'],
      [4, '', 'tomatoes'],
      [4, 'tbsp', 'oil'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [4, '', 'green chilies'],
      [1, 'tsp', 'crushed red chili'],
      [1, 'tsp', 'cumin'],
      [1, '', 'ginger', 'julienned, to finish'],
    ],
    steps: [
      'Sear the chicken in hot oil until it colours.',
      'Add ginger-garlic paste and tomatoes; cook until the oil separates.',
      ['Cover and cook until the chicken is tender.', 900],
      'Add spices and green chilies; fry hard to reduce.',
      'Finish with julienned ginger.',
    ],
    tips: ['Don’t add water — the tomatoes give all the moisture you need.'],
    related: ['karahi-mutton', 'handi-chicken'],
    seed: 210,
  }),
  r({
    id: 'karahi-mutton',
    chapter: 'pakistani',
    title: 'Karahi (Mutton)',
    tagline: 'Slow-tendered mutton in a fierce tomato masala.',
    story: 'Sunday-long cooking. The mutton must be spoon-soft before the masala tightens around it. Smell tells you when it’s ready more than any clock will.',
    tasteLike: 'Deep, tangy, peppery.',
    texture: 'Fall-apart mutton, thick masala.',
    cuisine: 'Pakistani',
    difficulty: 'hard',
    spice: 4,
    prep: 15,
    cook: 75,
    servings: 4,
    cal: 520,
    protein: 36,
    carbs: 10,
    fat: 36,
    tags: ['savory', 'spicy', 'karahi'],
    ing: [
      [800, 'g', 'mutton', 'bone-in'],
      [4, '', 'tomatoes'],
      [5, 'tbsp', 'oil'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [4, '', 'green chilies'],
      [1, 'tbsp', 'crushed coriander'],
      [1, 'tsp', 'black pepper'],
    ],
    steps: [
      'Brown the mutton in oil, add ginger-garlic paste.',
      ['Add a little water, cover, and simmer until tender.', 3600],
      'Add tomatoes and spices; fry until the oil splits.',
      'Reduce hard until the masala clings; finish with chilies.',
    ],
    tips: ['A pressure cooker cuts the tenderising time in half.'],
    related: ['karahi-chicken', 'nihari-beef'],
    seed: 211,
  }),
  r({
    id: 'handi-chicken',
    chapter: 'pakistani',
    title: 'Handi (Chicken)',
    tagline: 'Creamy, cardamom-scented clay-pot chicken.',
    story: 'Richer and gentler than karahi — cream and yogurt make it a special-occasion favourite. I learned this by burning one batch and loving the next.',
    tasteLike: 'Mild, creamy, aromatic.',
    texture: 'Velvety, tender.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 2,
    prep: 15,
    cook: 35,
    servings: 4,
    cal: 460,
    protein: 32,
    carbs: 12,
    fat: 30,
    tags: ['savory', 'creamy', 'handi'],
    allergens: ['dairy'],
    ing: [
      [800, 'g', 'chicken'],
      [4, 'tbsp', 'oil'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [150, 'g', 'yogurt'],
      [100, 'ml', 'cream'],
      [2, '', 'tomatoes'],
      [1, 'tsp', 'garam masala'],
    ],
    steps: [
      'Sauté chicken with ginger-garlic paste until sealed.',
      'Add tomatoes and whisked yogurt; cook until the oil separates.',
      ['Cover and simmer until tender.', 1200],
      'Stir in cream and garam masala; warm through.',
    ],
    tips: ['Whisk the yogurt before adding so it doesn’t split.'],
    related: ['cheese-handi-chicken', 'green-handi-chicken'],
    seed: 212,
  }),
  r({
    id: 'handi-mutton',
    chapter: 'pakistani',
    title: 'Handi (Mutton)',
    tagline: 'Creamy clay-pot mutton, deeply spiced.',
    story: 'The handi that fills the house with the best smell. Give the mutton time — cream forgives nothing tough. Smell tells you when it’s ready more than any clock will.',
    tasteLike: 'Rich, creamy, warmly spiced.',
    texture: 'Tender mutton in silky gravy.',
    cuisine: 'Pakistani',
    difficulty: 'hard',
    spice: 3,
    prep: 15,
    cook: 80,
    servings: 4,
    cal: 560,
    protein: 34,
    carbs: 12,
    fat: 40,
    tags: ['savory', 'creamy', 'handi'],
    allergens: ['dairy'],
    ing: [
      [800, 'g', 'mutton'],
      [5, 'tbsp', 'oil'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [150, 'g', 'yogurt'],
      [100, 'ml', 'cream'],
      [2, '', 'onions', 'fried'],
      [1, 'tsp', 'garam masala'],
    ],
    steps: [
      'Brown mutton with ginger-garlic paste.',
      ['Add yogurt and water; simmer covered until tender.', 3600],
      'Blend in fried onions; reduce to a thick gravy.',
      'Finish with cream and garam masala.',
    ],
    tips: ['Fried-onion paste is the shortcut to restaurant richness.'],
    related: ['handi-chicken', 'qorma-mutton'],
    seed: 213,
  }),
  r({
    id: 'cheese-handi-chicken',
    chapter: 'pakistani',
    title: 'Cheese Handi (Chicken)',
    tagline: 'Chicken handi turned indulgent with molten cheese.',
    story: 'A modern favourite the kids beg for — creamy handi finished with a blanket of melting cheese. I learned this by burning one batch and loving the next.',
    tasteLike: 'Creamy and mild with cheesy richness.',
    texture: 'Gooey, velvety.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 2,
    prep: 15,
    cook: 35,
    servings: 4,
    cal: 540,
    protein: 36,
    carbs: 12,
    fat: 38,
    tags: ['savory', 'creamy', 'cheesy', 'handi'],
    allergens: ['dairy'],
    ing: [
      [800, 'g', 'chicken'],
      [4, 'tbsp', 'oil'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [150, 'g', 'yogurt'],
      [100, 'ml', 'cream'],
      [150, 'g', 'mozzarella', 'grated'],
      [1, 'tsp', 'garam masala'],
    ],
    steps: [
      'Cook a creamy chicken handi base until the oil separates and the chicken is tender.',
      ['Simmer until tender.', 1200],
      'Stir in cream and garam masala.',
      'Scatter cheese, cover off the heat until molten.',
    ],
    tips: ['Melt the cheese with residual heat so it stays stretchy, not oily.'],
    related: ['handi-chicken', 'green-handi-chicken'],
    seed: 214,
  }),
  r({
    id: 'green-handi-chicken',
    chapter: 'pakistani',
    title: 'Green Handi (Chicken)',
    tagline: 'A herb-green handi, fresh with coriander and mint.',
    story: 'The freshest handi in my kitchen — a fistful of herbs blended in turns it vivid and bright. If you’re tired, still make this — it’s kinder than takeaway and nearly as fast.',
    tasteLike: 'Fresh, herby, gently spiced.',
    texture: 'Creamy with a green lift.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 3,
    prep: 15,
    cook: 35,
    servings: 4,
    cal: 440,
    protein: 33,
    carbs: 10,
    fat: 28,
    tags: ['savory', 'herby', 'handi'],
    allergens: ['dairy'],
    ing: [
      [800, 'g', 'chicken'],
      [1, 'bunch', 'coriander'],
      [0.5, 'bunch', 'mint'],
      [4, '', 'green chilies'],
      [4, 'tbsp', 'oil'],
      [150, 'g', 'yogurt'],
      [2, 'tbsp', 'ginger-garlic paste'],
    ],
    steps: [
      'Blend coriander, mint and chilies into a green paste.',
      'Cook chicken with ginger-garlic paste and yogurt until tender.',
      ['Simmer until tender.', 1200],
      'Stir in the green paste and cook briefly to keep it vivid.',
    ],
    tips: ['Add the herb paste near the end so the colour stays bright.'],
    related: ['handi-chicken', 'cheese-handi-chicken'],
    seed: 215,
  }),
  r({
    id: 'nihari-chicken',
    chapter: 'pakistani',
    title: 'Nihari (Chicken)',
    tagline: 'A quicker nihari, deep with slow-spice flavour.',
    story: 'Nihari is a weekend ritual. The chicken version brings that soulful spice to a weeknight. The version in my head is louder with spice — dial to your table.',
    tasteLike: 'Warm, peppery, deeply spiced.',
    texture: 'Silky, flour-thickened gravy.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 3,
    prep: 15,
    cook: 45,
    servings: 4,
    cal: 400,
    protein: 32,
    carbs: 14,
    fat: 24,
    tags: ['savory', 'spicy', 'nihari'],
    allergens: ['gluten'],
    ing: [
      [800, 'g', 'chicken', 'bone-in'],
      [4, 'tbsp', 'oil'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [2, 'tbsp', 'nihari masala'],
      [3, 'tbsp', 'flour', 'slurry'],
      [null, '', 'ginger, chili, lemon', 'to serve'],
    ],
    steps: [
      'Fry ginger-garlic paste, add chicken and nihari masala.',
      ['Add water and simmer until tender.', 1800],
      'Whisk in the flour slurry and cook until glossy and thick.',
      'Serve topped with ginger, green chili and lemon.',
    ],
    tips: ['Stream the flour slurry in slowly, whisking, so it never lumps.'],
    related: ['nihari-beef', 'pakistani-stew'],
    seed: 216,
  }),
  r({
    id: 'nihari-beef',
    chapter: 'pakistani',
    title: 'Nihari (Beef)',
    tagline: 'The Sunday-morning classic, slow and soulful.',
    story: 'This is the dish of celebration mornings. It cannot be hurried — the shanks give in only to time. I learned this by burning one batch and loving the next.',
    tasteLike: 'Rich, peppery, deeply savoury.',
    texture: 'Fork-soft beef, luscious gravy.',
    cuisine: 'Pakistani',
    difficulty: 'hard',
    spice: 4,
    prep: 20,
    cook: 180,
    servings: 6,
    cal: 520,
    protein: 38,
    carbs: 14,
    fat: 34,
    tags: ['savory', 'spicy', 'nihari', 'festive'],
    allergens: ['gluten'],
    ing: [
      [1, 'kg', 'beef shank'],
      [5, 'tbsp', 'oil or ghee'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [3, 'tbsp', 'nihari masala'],
      [4, 'tbsp', 'flour', 'slurry'],
      [null, '', 'ginger, chili, lemon', 'to serve'],
    ],
    steps: [
      'Brown the beef with ginger-garlic paste and nihari masala.',
      ['Add plenty of water and simmer very low until fork-tender.', 9000],
      'Thicken with the flour slurry, whisking until glossy.',
      'Rest, then serve with ginger, chili and lemon.',
    ],
    tips: ['A final tempering of sizzling ghee and chili poured on top is traditional.'],
    related: ['nihari-chicken', 'pakistani-stew'],
    seed: 217,
  }),
  r({
    id: 'pakistani-stew',
    chapter: 'pakistani',
    title: 'Pakistani Stew',
    tagline: 'A homely one-pot of meat and vegetables.',
    story: 'The comforting stew my mother made when someone was under the weather — gentle spice, all in one pot. I learned this by burning one batch and loving the next.',
    tasteLike: 'Warm, mild, brothy.',
    texture: 'Tender meat and soft vegetables.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 15,
    cook: 60,
    servings: 5,
    cal: 380,
    protein: 28,
    carbs: 24,
    fat: 18,
    tags: ['savory', 'comfort', 'one-pot'],
    ing: [
      [600, 'g', 'beef or chicken', 'cubed'],
      [3, '', 'potatoes'],
      [2, '', 'carrots'],
      [2, '', 'onions'],
      [2, '', 'tomatoes'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [1, 'tbsp', 'mixed spice powder'],
    ],
    steps: [
      'Brown the meat with onions and ginger-garlic paste.',
      'Add tomatoes and spice; cook down.',
      ['Add water and vegetables; simmer until everything is tender.', 2400],
      'Adjust the broth and serve with bread or rice.',
    ],
    tips: ['Cut the vegetables large so they don’t collapse in the long simmer.'],
    related: ['nihari-beef', 'qorma-chicken'],
    seed: 218,
  }),
  r({
    id: 'qorma-chicken',
    chapter: 'pakistani',
    title: 'Qorma (Chicken)',
    tagline: 'Fried-onion and yogurt gravy, festive and rich.',
    story: 'The wedding-table qorma. Bloom the whole spices in ghee first — that aroma is the soul of the dish. If you’re tired, still make this — it’s kinder than takeaway and nearly as fast.',
    tasteLike: 'Rich, mildly sweet, aromatic.',
    texture: 'Smooth, glossy gravy.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 2,
    prep: 15,
    cook: 45,
    servings: 5,
    cal: 460,
    protein: 32,
    carbs: 12,
    fat: 30,
    tags: ['savory', 'festive', 'qorma'],
    allergens: ['dairy'],
    ing: [
      [900, 'g', 'chicken'],
      [3, '', 'onions', 'fried & blended'],
      [200, 'g', 'yogurt'],
      [5, 'tbsp', 'ghee'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [null, '', 'whole spices', 'cardamom, cloves, cinnamon'],
      [1, 'tsp', 'garam masala'],
    ],
    steps: [
      'Bloom whole spices in ghee, add ginger-garlic paste and chicken.',
      'Add whisked yogurt gradually; cook until the oil separates.',
      'Stir in the fried-onion paste and a little water.',
      ['Simmer to a glossy gravy.', 1500],
      'Finish with garam masala.',
    ],
    tips: ['Add the yogurt off the boil, a little at a time, so it never curdles.'],
    related: ['qorma-mutton', 'badami-qorma-chicken'],
    seed: 219,
  }),
  r({
    id: 'qorma-mutton',
    chapter: 'pakistani',
    title: 'Qorma (Mutton)',
    tagline: 'The grand qorma, slow-built and luxurious.',
    story: 'The centrepiece of our biggest feasts. Everything about it rewards patience. I learned this by burning one batch and loving the next.',
    tasteLike: 'Deep, aromatic, gently rich.',
    texture: 'Tender mutton in a silky gravy.',
    cuisine: 'Pakistani',
    difficulty: 'hard',
    spice: 3,
    prep: 20,
    cook: 90,
    servings: 6,
    cal: 560,
    protein: 36,
    carbs: 12,
    fat: 40,
    tags: ['savory', 'festive', 'qorma'],
    allergens: ['dairy'],
    ing: [
      [1, 'kg', 'mutton'],
      [4, '', 'onions', 'fried & blended'],
      [250, 'g', 'yogurt'],
      [6, 'tbsp', 'ghee'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [null, '', 'whole spices'],
      [1, 'tsp', 'garam masala'],
    ],
    steps: [
      'Bloom whole spices in ghee; brown the mutton with ginger-garlic paste.',
      'Add yogurt gradually and cook until the oil separates.',
      ['Add water and simmer until the mutton is tender.', 3600],
      'Blend in fried onions; reduce to a glossy gravy and finish with garam masala.',
    ],
    tips: ['Low and slow — a rushed qorma is a tough qorma.'],
    related: ['qorma-chicken', 'badami-qorma-mutton'],
    seed: 220,
  }),
  r({
    id: 'badami-qorma-chicken',
    chapter: 'pakistani',
    title: 'Badami Qorma (Chicken)',
    tagline: 'Qorma enriched with a silky almond paste.',
    story: 'A qorma dressed for a special night — ground almonds make it luxuriously smooth. Write the timings on a sticky if you must; the method is forgiving.',
    tasteLike: 'Nutty, rich, delicately spiced.',
    texture: 'Extra-silky, luscious.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 2,
    prep: 20,
    cook: 45,
    servings: 5,
    cal: 500,
    protein: 33,
    carbs: 14,
    fat: 34,
    tags: ['savory', 'festive', 'qorma'],
    allergens: ['dairy', 'nuts'],
    ing: [
      [900, 'g', 'chicken'],
      [80, 'g', 'almonds', 'blanched & ground'],
      [3, '', 'onions', 'fried & blended'],
      [200, 'g', 'yogurt'],
      [5, 'tbsp', 'ghee'],
      [2, 'tbsp', 'ginger-garlic paste'],
    ],
    steps: [
      'Build a qorma base with ghee, ginger-garlic paste, chicken and yogurt.',
      'Add the fried-onion paste and simmer until tender.',
      ['Simmer until tender.', 1200],
      'Stir in the almond paste and warm through until velvety.',
    ],
    tips: ['A splash of cream alongside the almonds makes it even smoother.'],
    related: ['qorma-chicken', 'badami-qorma-mutton'],
    seed: 221,
  }),
  r({
    id: 'badami-qorma-mutton',
    chapter: 'pakistani',
    title: 'Badami Qorma (Mutton)',
    tagline: 'Almond-enriched mutton qorma, pure luxury.',
    story: 'The most decadent thing I cook. Reserved for the people I love most. I keep the ingredients list short on purpose. Flavour comes from heat and patience.',
    tasteLike: 'Deeply nutty and rich.',
    texture: 'Silken, spoon-coating gravy.',
    cuisine: 'Pakistani',
    difficulty: 'hard',
    spice: 3,
    prep: 20,
    cook: 95,
    servings: 6,
    cal: 600,
    protein: 37,
    carbs: 14,
    fat: 44,
    tags: ['savory', 'festive', 'qorma'],
    allergens: ['dairy', 'nuts'],
    ing: [
      [1, 'kg', 'mutton'],
      [100, 'g', 'almonds', 'ground'],
      [4, '', 'onions', 'fried & blended'],
      [250, 'g', 'yogurt'],
      [6, 'tbsp', 'ghee'],
      [2, 'tbsp', 'ginger-garlic paste'],
    ],
    steps: [
      'Brown mutton with whole spices and ginger-garlic paste in ghee.',
      'Add yogurt gradually, then water, and simmer until tender.',
      ['Simmer until tender.', 3600],
      'Blend in fried onions and the almond paste; reduce to a glossy, silky gravy.',
    ],
    tips: ['Toast the almonds lightly before grinding for a deeper flavour.'],
    related: ['qorma-mutton', 'badami-qorma-chicken'],
    seed: 222,
  }),

  /* ═══════════════════ ITALIAN ═══════════════════ */
  r({
    id: 'lasagna-chicken',
    chapter: 'italian',
    title: 'Lasagna (Chicken)',
    tagline: 'Creamy chicken layered with béchamel and pasta.',
    story: 'My crowd-pleaser bake. Season every layer — a bland middle ruins the whole tray. Write the timings on a sticky if you must; the method is forgiving.',
    tasteLike: 'Creamy, cheesy, savoury.',
    texture: 'Soft layers under a bubbling top.',
    cuisine: 'Italian',
    difficulty: 'medium',
    prep: 30,
    cook: 45,
    servings: 6,
    cal: 560,
    protein: 34,
    carbs: 44,
    fat: 28,
    tags: ['savory', 'baked', 'comfort'],
    allergens: ['gluten', 'dairy'],
    ing: [
      [12, '', 'lasagna sheets'],
      [500, 'g', 'chicken', 'cooked & shredded'],
      [700, 'ml', 'béchamel'],
      [200, 'g', 'mozzarella'],
      [1, '', 'onion'],
      [2, '', 'garlic cloves'],
    ],
    steps: [
      'Cook the chicken with onion and garlic; fold through half the béchamel.',
      'Layer sheets, chicken, béchamel and cheese; repeat.',
      'Finish with béchamel and mozzarella.',
      ['Bake at 190°C until golden and bubbling.', 2700],
      ['Rest before cutting.', 600],
    ],
    tips: ['Let it rest 10 minutes so the layers hold when you slice.'],
    related: ['lasagna-beef', 'alfredo-pasta'],
    seed: 223,
  }),
  r({
    id: 'lasagna-beef',
    chapter: 'italian',
    title: 'Lasagna (Beef)',
    tagline: 'Classic ragù layered with béchamel.',
    story: 'The lasagna I grew up wanting at every birthday. A slow ragù is the whole secret. Smell tells you when it’s ready more than any clock will.',
    tasteLike: 'Rich tomato-meat and creamy cheese.',
    texture: 'Hearty, tender layers.',
    cuisine: 'Italian',
    difficulty: 'medium',
    prep: 30,
    cook: 75,
    servings: 6,
    cal: 590,
    protein: 33,
    carbs: 46,
    fat: 30,
    tags: ['savory', 'baked', 'comfort'],
    allergens: ['gluten', 'dairy'],
    ing: [
      [12, '', 'lasagna sheets'],
      [500, 'g', 'minced beef'],
      [700, 'g', 'tomato passata'],
      [700, 'ml', 'béchamel'],
      [200, 'g', 'mozzarella & parmesan'],
      [1, '', 'onion'],
    ],
    steps: [
      ['Simmer a rich beef ragù with onion and passata.', 2400],
      'Layer sheets, ragù, béchamel and cheese; repeat.',
      ['Bake at 190°C until deep golden.', 2700],
      ['Rest before cutting.', 600],
    ],
    tips: ['A longer-simmered ragù makes a noticeably better lasagna.'],
    related: ['lasagna-chicken', 'rigatoni-pasta'],
    seed: 224,
  }),
  r({
    id: 'alfredo-pasta',
    chapter: 'italian',
    title: 'Alfredo Pasta',
    tagline: 'Silky parmesan cream over fettuccine.',
    story: 'Fast, rich, and always a yes. Loosen it with pasta water so it stays glossy, not gluey. The version in my head is louder with spice — dial to your table.',
    tasteLike: 'Creamy, cheesy, garlicky.',
    texture: 'Velvety sauce clinging to ribbons.',
    cuisine: 'Italian',
    difficulty: 'easy',
    prep: 10,
    cook: 20,
    servings: 4,
    cal: 620,
    protein: 20,
    carbs: 66,
    fat: 30,
    tags: ['savory', 'creamy', 'quick'],
    allergens: ['gluten', 'dairy'],
    ing: [
      [400, 'g', 'fettuccine'],
      [300, 'ml', 'cream'],
      [80, 'g', 'butter'],
      [80, 'g', 'parmesan'],
      [3, '', 'garlic cloves'],
    ],
    steps: [
      ['Boil the pasta, reserving a cup of water.', 600],
      'Gently melt butter, garlic and cream; add parmesan.',
      'Toss the pasta through, loosening with pasta water until glossy.',
    ],
    tips: ['Keep the heat low so the cheese emulsifies instead of clumping.'],
    related: ['rigatoni-pasta', 'caprese-orzo'],
    seed: 225,
  }),
  r({
    id: 'rigatoni-pasta',
    chapter: 'italian',
    title: 'Rigatoni Pasta',
    tagline: 'Tube pasta in a rich tomato-cream sauce.',
    story: 'Those ridges catch the sauce — my favourite shape for a cosy bowl on a cold night. Write the timings on a sticky if you must; the method is forgiving.',
    tasteLike: 'Sweet tomato with a creamy edge.',
    texture: 'Al dente tubes, clinging sauce.',
    cuisine: 'Italian',
    difficulty: 'easy',
    prep: 10,
    cook: 25,
    servings: 4,
    cal: 540,
    protein: 18,
    carbs: 72,
    fat: 20,
    tags: ['savory', 'comfort', 'vegetarian'],
    allergens: ['gluten', 'dairy'],
    ing: [
      [400, 'g', 'rigatoni'],
      [700, 'g', 'tomato passata'],
      [100, 'ml', 'cream'],
      [1, '', 'onion'],
      [3, '', 'garlic cloves'],
      [1, 'handful', 'basil'],
    ],
    steps: [
      'Soften onion and garlic, add passata; simmer to sweeten.',
      ['Simmer the sauce.', 900],
      'Stir in cream. Toss with cooked rigatoni and basil.',
    ],
    tips: ['A pinch of sugar tames a sharp tomato sauce.'],
    related: ['alfredo-pasta', 'caprese-orzo'],
    seed: 226,
  }),

  /* ═══════════════════ CHINESE ═══════════════════ */
  r({
    id: 'desi-chinese',
    chapter: 'chinese',
    title: 'Desi Chinese',
    tagline: 'The saucy, spicy Chinese of home takeaways.',
    story: 'Not authentic and proud of it — this is the garlicky, chili-hot Chinese we all grew up ordering. The version in my head is louder with spice — dial to your table.',
    tasteLike: 'Sweet, hot, garlicky, tangy.',
    texture: 'Crisp vegetables in a glossy sauce.',
    cuisine: 'Chinese',
    difficulty: 'medium',
    spice: 3,
    prep: 20,
    cook: 15,
    servings: 4,
    cal: 420,
    protein: 24,
    carbs: 40,
    fat: 18,
    tags: ['savory', 'spicy', 'stir-fry'],
    allergens: ['soy', 'gluten'],
    ing: [
      [400, 'g', 'chicken', 'sliced'],
      [1, '', 'capsicum'],
      [1, '', 'onion'],
      [4, '', 'garlic cloves'],
      [3, 'tbsp', 'soy sauce'],
      [2, 'tbsp', 'chili-garlic sauce'],
      [1, 'tbsp', 'cornstarch', 'slurry'],
    ],
    steps: [
      'Sear the chicken hot and fast; set aside.',
      'Stir-fry garlic, onion and capsicum until just crisp.',
      'Return chicken, add the sauces, and thicken with the slurry.',
    ],
    tips: ['Everything chopped and ready before the wok gets hot — this moves fast.'],
    related: ['kung-pao-tofu', 'karahi-chicken'],
    seed: 227,
  }),

  /* ═══════════════════ COFFEE & CHAI — ICED LATTES ═══════════════════ */
  ...latte('iced-caramel-latte', 'Iced Caramel Latte', 'Espresso, milk, and a caramel ribbon.', 'Sweet caramel over cool coffee.', ['caramel sauce'], 230),
  ...latte('iced-mocha-latte', 'Iced Mocha Latte', 'Chocolate meets cold coffee.', 'Rich chocolate and espresso.', ['chocolate syrup'], 231),
  ...latte('iced-spanish-latte', 'Iced Spanish Latte', 'Espresso sweetened with condensed milk.', 'Creamy, sweet, and strong.', ['condensed milk'], 232),
  ...latte('iced-mocha-orange-latte', 'Iced Mocha Orange Latte', 'Chocolate and orange over ice.', 'Chocolate-orange and coffee.', ['chocolate syrup', 'orange zest'], 233),
  ...latte('iced-blueberry-latte', 'Iced Blueberry Latte', 'Fruity blueberry cold coffee.', 'Sweet blueberry and espresso.', ['blueberry syrup'], 234),
  ...latte('iced-strawberry-latte', 'Iced Strawberry Latte', 'Strawberry syrup and cold milk coffee.', 'Bright strawberry and coffee.', ['strawberry syrup'], 235),
  ...latte('strawberry-oreo-latte', 'Strawberry and Oreo Latte', 'Strawberry latte with Oreo crumble.', 'Strawberry, cream, cocoa crunch.', ['strawberry syrup', 'crushed Oreos'], 236),
  ...latte('cookies-cream-latte', 'Cookies and Cream Latte', 'Blended Oreo and coffee, iced.', 'Creamy cookies-and-cream and coffee.', ['crushed Oreos', 'vanilla syrup'], 237),

  /* ═══════════════════ EASY SNACKS — FRIED CHICKEN ═══════════════════ */
  r({
    id: 'kfc-chicken',
    chapter: 'snacks',
    title: 'KFC Chicken',
    tagline: 'Craggy, crunchy, buttermilk-brined chicken.',
    story: 'My weekend project that beats the drive-through. Double-dip for that famous craggy crust. Smell tells you when it’s ready more than any clock will.',
    tasteLike: 'Savoury, herby, deeply crunchy.',
    texture: 'Shatter-crisp crust, juicy inside.',
    cuisine: 'American',
    difficulty: 'medium',
    spice: 1,
    prep: 30,
    cook: 20,
    servings: 4,
    cal: 560,
    protein: 38,
    carbs: 34,
    fat: 30,
    tags: ['savory', 'fried', 'crowd-pleaser'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [8, '', 'chicken pieces'],
      [500, 'ml', 'buttermilk'],
      [300, 'g', 'flour'],
      [2, 'tbsp', 'mixed herbs & spice'],
      [1, '', 'egg'],
      [null, '', 'oil', 'to deep-fry'],
    ],
    steps: [
      ['Brine the chicken in seasoned buttermilk.', 7200],
      'Dredge in seasoned flour, back into buttermilk, then flour again.',
      ['Fry at 170°C until deep gold and cooked through (74°C internal).', 900],
      'Rest on a rack so it stays crisp.',
    ],
    tips: ['Squeeze a little buttermilk into the flour first — those clumps become the crags.'],
    related: ['kfc-spicy-chicken', 'halloumi-wrap'],
    seed: 240,
  }),
  r({
    id: 'kfc-spicy-chicken',
    chapter: 'snacks',
    title: 'KFC Spicy Chicken',
    tagline: 'The crunchy classic, turned up hot.',
    story: 'For the chili-lovers in my house — the same craggy crust, with real heat baked into the dredge. Don’t rush the last minute; that’s where it turns from fine to lovely.',
    tasteLike: 'Spicy, savoury, crunchy.',
    texture: 'Extra-crisp, fiery crust.',
    cuisine: 'American',
    difficulty: 'medium',
    spice: 4,
    prep: 30,
    cook: 20,
    servings: 4,
    cal: 570,
    protein: 38,
    carbs: 34,
    fat: 31,
    tags: ['savory', 'fried', 'spicy'],
    allergens: ['gluten', 'dairy', 'egg'],
    ing: [
      [8, '', 'chicken pieces'],
      [500, 'ml', 'buttermilk'],
      [1, 'tbsp', 'hot sauce'],
      [300, 'g', 'flour'],
      [2, 'tbsp', 'cayenne & paprika blend'],
      [null, '', 'oil', 'to deep-fry'],
    ],
    steps: [
      ['Brine in buttermilk spiked with hot sauce.', 7200],
      'Dredge in fiery seasoned flour, double-dipping for crags.',
      ['Fry at 170°C until deep gold and 74°C inside.', 900],
      'Dust with extra cayenne while hot.',
    ],
    tips: ['Cook to 74°C internal — colour alone isn’t doneness.'],
    related: ['kfc-chicken', 'desi-chinese'],
    seed: 241,
  }),
];

/* ── Generators ───────────────────────────────────────────────────────── */

/** Three biryani styles × three meats, sharing a base method, varied to taste. */
function biryani(style: 'saadi' | 'sindhi' | 'zaffarani', meat: 'chicken' | 'mutton' | 'beef', seed: number): Recipe[] {
  const styleName = { saadi: 'Saadi', sindhi: 'Sindhi', zaffarani: 'Zaffarani' }[style];
  const meatName = { chicken: 'Chicken', mutton: 'Mutton', beef: 'Beef' }[meat];
  const styleNote = {
    saadi: 'the plain, elegant biryani — gentle spice, all about the rice',
    sindhi: 'the fiery Sindhi style, with potatoes, prunes and extra chili',
    zaffarani: 'the saffron biryani — mild, fragrant and golden',
  }[style];
  const spice = { saadi: 2, sindhi: 4, zaffarani: 2 }[style];
  const cook = meat === 'chicken' ? 40 : meat === 'mutton' ? 90 : 80;
  const tenderSec = meat === 'chicken' ? 1200 : 3600;

  const meatIng: [number, string, string, string?] = [800, 'g', `${meat}`, 'bone-in'];
  const extra: Tup[] =
    style === 'sindhi'
      ? [[3, '', 'potatoes', 'halved'], [8, '', 'dried prunes'], [2, 'tsp', 'extra red chili']]
      : style === 'zaffarani'
        ? [[0.5, 'tsp', 'saffron', 'in warm milk']]
        : [];

  return [
    r({
      id: `${style}-biryani-${meat}`,
      chapter: 'pakistani',
      title: `${styleName} Biryani (${meatName})`,
      tagline: `${styleNote.charAt(0).toUpperCase()}${styleNote.slice(1)}.`,
      story: `Biryani is Sunday in our house. This is ${styleNote}, made with ${meat} — layered, dum-cooked, and worth every step.`,
      tasteLike: style === 'sindhi' ? 'Boldly spiced, tangy and hot.' : style === 'zaffarani' ? 'Delicate, saffron-fragrant, mild.' : 'Balanced, aromatic, comforting.',
      texture: 'Separate, fluffy rice over tender meat.',
      cuisine: 'Pakistani',
      difficulty: meat === 'chicken' ? 'medium' : 'hard',
      spice,
      allergens: ['dairy'],
      prep: 30,
      cook,
      servings: 6,
      cal: 620,
      protein: 32,
      carbs: 72,
      fat: 22,
      tags: ['savory', 'rice', 'festive', 'biryani'],
      ing: [
        meatIng,
        ...RICE,
        [3, '', 'onions', 'fried'],
        [200, 'g', 'yogurt'],
        [2, 'tbsp', 'ginger-garlic paste'],
        [2, 'tbsp', 'biryani masala'],
        ...extra,
      ],
      steps: [
        'Fry the onions until deep golden; reserve half for layering.',
        `Cook the ${meat} with ginger-garlic paste, yogurt and biryani masala until tender.`,
        [`Simmer the ${meat} until tender.`, tenderSec],
        'Parboil the soaked rice with whole spices and salt until 70% done; drain.',
        style === 'zaffarani'
          ? 'Layer rice and masala, drizzle over the saffron milk and fried onions.'
          : style === 'sindhi'
            ? 'Layer rice with the masala, potatoes, prunes and fried onions.'
            : 'Layer rice and masala with the fried onions.',
        ['Cover tightly and steam on dum over low heat.', 1200],
        'Rest, then fold gently from the sides to serve.',
      ],
      tips: [
        'Parboil the rice to 70% — it finishes cooking in the steam.',
        'Seal the lid with foil or dough so no steam escapes during dum.',
      ],
      related: ['saadi', 'sindhi', 'saadi', 'chicken', 'qorma-chicken', 'mutton', 'qorma-mutton', 'nihari-beef'],
      seed,
    }),
  ];
}

/** Iced latte template — same build, different sweet flavouring. */
function latte(id: string, title: string, tagline: string, tasteLike: string, flavour: string[], seed: number): Recipe[] {
  return [
    r({
      id,
      chapter: 'coffee',
      title,
      tagline,
      story: 'The café order I taught myself to make at home — cheaper, and exactly how I like it.',
      tasteLike,
      texture: 'Cold, creamy, lightly frothy.',
      cuisine: 'Café',
      difficulty: 'easy',
      spice: 0,
      allergens: ['dairy'],
      prep: 5,
      cook: 0,
      servings: 1,
      cal: 220,
      protein: 6,
      carbs: 28,
      fat: 8,
      sugar: 24,
      tags: ['drink', 'iced', 'coffee', 'sweet'],
      ing: [
        [2, 'shots', 'espresso', 'cooled'],
        [200, 'ml', 'cold milk'],
        [null, '', 'ice'],
        ...flavour.map((f): Tup => [2, 'tbsp', f]),
      ],
      steps: [
        'Add the flavouring to a tall glass of ice.',
        'Pour in the cold milk.',
        'Float the espresso over the back of a spoon for the layered look, then stir.',
      ],
      tips: ['Brew the espresso ahead and chill it so the ice doesn’t melt down your drink.'],
      related: ['masala-chai'],
      seed,
    }),
  ];
}
