import type { Recipe } from './types';
import { EXTRA_RECIPES } from './data-extra';
import { FILL_RECIPES } from './data-fill';
import { FOODFUSION_RECIPES } from './data-foodfusion';
import { GOAL_RECIPES } from './data-goal';
import { MEALDB_RECIPES } from './data-themealdb';

/**
 * The cookbook's recipes. Flagship entries below are fully editorial; the
 * growing collection in `data-extra.ts` / `data-fill.ts` uses a compact builder.
 * `data-foodfusion.ts` = cleaned English adaptations (no promo/login/Urdu dump).
 * `data-goal.ts` = breakfast / high-protein / light / budget goal recipes.
 * `data-themealdb.ts` = TheMealDB imports (photo bundled with each dish).
 * Heroes fall back to procedural art (`hero.ts`) until photos are added.
 */
export const RECIPES: Recipe[] = [
  {
    id: 'buttermilk-pancakes',
    chapter: 'baking',
    title: 'Buttermilk Pancakes',
    tagline: 'Tall, tender, and lacquered in maple.',
    story:
      'Weekend mornings in our house are lazy on purpose. I make these while everyone’s still in socks, and the first one is always mine — cook’s privilege. Don’t skip the rest; that ten minutes is what makes them fluffy.',
    tasteLike: 'Buttery and gently sweet, with a tang from the buttermilk.',
    texture: 'Cloud-soft inside, lightly crisp at the lacy edges.',
    spiceLevel: 0,
    allergens: ['dairy', 'gluten', 'egg'],
    cuisine: 'American',
    difficulty: 'easy',
    prepMin: 10,
    cookMin: 15,
    servings: 4,
    nutrition: { calories: 420, protein: 11, carbs: 58, fat: 16, fiber: 2, sugar: 18 },
    tags: ['sweet', 'weekend', 'kid-friendly', 'vegetarian'],
    ingredients: [
      {
        heading: 'Batter',
        items: [
          { quantity: 260, unit: 'g', item: 'all-purpose flour' },
          { quantity: 2, unit: 'tbsp', item: 'caster sugar' },
          { quantity: 2, unit: 'tsp', item: 'baking powder' },
          { quantity: 0.5, unit: 'tsp', item: 'baking soda' },
          { quantity: 0.5, unit: 'tsp', item: 'fine salt' },
          { quantity: 480, unit: 'ml', item: 'buttermilk', note: 'well shaken' },
          { quantity: 2, unit: '', item: 'large eggs' },
          { quantity: 60, unit: 'g', item: 'butter', note: 'melted, plus more for the pan' },
        ],
      },
    ],
    steps: [
      { instruction: 'Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl.' },
      {
        instruction:
          'In a second bowl whisk buttermilk, eggs, and melted butter. Pour the wet into the dry and fold just until combined — lumps are good. Rest the batter.',
        durationSec: 600,
        tip: 'Resting hydrates the flour and relaxes gluten, giving a fluffier crumb.',
      },
      {
        instruction:
          'Heat a nonstick pan over medium, wipe with butter. Ladle in batter and cook until bubbles break the surface and edges set.',
        durationSec: 150,
      },
      { instruction: 'Flip once and cook until golden. Hold in a warm oven; serve with maple.' },
    ],
    chefNotes: [
      'No buttermilk? Stir 1 tbsp lemon juice into 480 ml milk and wait 10 minutes.',
    ],
    tips: ['A dry pan test: a droplet of water should skitter, not vanish instantly.'],
    warnings: ['Overmixing develops gluten and turns pancakes rubbery.'],
    substitutions: [{ from: 'all-purpose flour', to: 'a 1:1 gluten-free blend' }],
    equipment: ['Nonstick skillet', 'Whisk', 'Ladle'],
    storage: 'Refrigerate up to 3 days, layered with parchment.',
    reheating: 'Toaster on medium revives the edges better than a microwave.',
    related: ['shakshuka', 'masala-chai'],
    heroSeed: 11,
  },
  {
    id: 'shakshuka',
    chapter: 'meals',
    title: 'Shakshuka',
    tagline: 'Eggs poached in a smoky pepper sea.',
    story:
      'This is my “there’s nothing in the house” dinner that somehow always impresses. One pan, a bit of bread to mop it up, and suddenly it’s a proper meal. Pull it off the heat while the yolks still wobble — they keep cooking after.',
    tasteLike: 'Smoky, jammy tomato with a soft-set egg and salty feta.',
    texture: 'Silky sauce, runny yolks, crumbly cheese.',
    spiceLevel: 2,
    allergens: ['egg', 'dairy'],
    cuisine: 'North African',
    difficulty: 'easy',
    prepMin: 10,
    cookMin: 25,
    servings: 3,
    nutrition: { calories: 310, protein: 16, carbs: 18, fat: 20, fiber: 5, sugar: 9 },
    tags: ['savory', 'one-pan', 'vegetarian', 'spicy'],
    ingredients: [
      {
        items: [
          { quantity: 3, unit: 'tbsp', item: 'olive oil' },
          { quantity: 1, unit: '', item: 'onion', note: 'sliced' },
          { quantity: 2, unit: '', item: 'red peppers', note: 'sliced' },
          { quantity: 3, unit: '', item: 'garlic cloves', note: 'sliced' },
          { quantity: 1, unit: 'tsp', item: 'ground cumin' },
          { quantity: 1, unit: 'tsp', item: 'sweet paprika' },
          { quantity: 0.25, unit: 'tsp', item: 'chili flakes' },
          { quantity: 800, unit: 'g', item: 'crushed tomatoes' },
          { quantity: 5, unit: '', item: 'eggs' },
          { quantity: 80, unit: 'g', item: 'feta', note: 'crumbled' },
        ],
      },
    ],
    steps: [
      { instruction: 'Soften onion and peppers in olive oil over medium heat.', durationSec: 480 },
      { instruction: 'Add garlic and spices; cook until fragrant.', durationSec: 60 },
      {
        instruction: 'Pour in tomatoes, season, and simmer until jammy.',
        durationSec: 600,
        tip: 'The sauce should mound on a spoon before the eggs go in.',
      },
      {
        instruction: 'Make wells, crack in eggs, cover, and cook until whites set but yolks run.',
        durationSec: 360,
      },
      { instruction: 'Scatter feta and herbs; serve from the pan with bread.' },
    ],
    chefNotes: ['A splash of harissa deepens the smoke without extra chopping.'],
    tips: ['Cover the pan to steam the tops of the eggs while the bottoms set.'],
    warnings: ['Residual heat keeps cooking the yolks — pull the pan a touch early.'],
    equipment: ['Wide skillet with lid'],
    storage: 'Sauce keeps 4 days; poach fresh eggs to serve.',
    reheating: 'Reheat sauce, then add eggs so they stay soft.',
    related: ['buttermilk-pancakes', 'chana-masala'],
    heroSeed: 3,
  },
  {
    id: 'roast-chicken',
    chapter: 'meals',
    title: 'Sunday Roast Chicken',
    tagline: 'Crisp skin, herb butter, one pan of gold.',
    story:
      'The dish I make when the whole family comes over. Salting it the night before feels fussy the first time, then you taste the skin and never go back. Save the bones — that’s next week’s soup, and I hate to waste anything.',
    tasteLike: 'Savoury and herby, with sweet roasted potatoes underneath.',
    texture: 'Shatteringly crisp skin over juicy meat.',
    spiceLevel: 0,
    allergens: ['dairy'],
    cuisine: 'French',
    difficulty: 'medium',
    prepMin: 20,
    cookMin: 75,
    servings: 4,
    nutrition: { calories: 560, protein: 42, carbs: 8, fat: 40, fiber: 2, sugar: 3 },
    tags: ['savory', 'roast', 'gluten-free', 'celebration'],
    ingredients: [
      {
        items: [
          { quantity: 1.6, unit: 'kg', item: 'whole chicken' },
          { quantity: 80, unit: 'g', item: 'softened butter' },
          { quantity: 3, unit: '', item: 'garlic cloves', note: 'grated' },
          { quantity: 1, unit: 'tbsp', item: 'thyme leaves' },
          { quantity: 1, unit: '', item: 'lemon', note: 'halved' },
          { quantity: 500, unit: 'g', item: 'baby potatoes', note: 'halved' },
          { quantity: null, unit: '', item: 'salt & pepper' },
        ],
      },
    ],
    steps: [
      {
        instruction:
          'Dry the chicken thoroughly and salt it all over. Rest uncovered in the fridge if time allows.',
        durationSec: 3600,
        tip: 'A dry surface is the single biggest lever for crisp skin.',
      },
      { instruction: 'Mash butter with garlic and thyme; push under and over the skin.' },
      { instruction: 'Stuff the lemon inside, tie the legs, and set on potatoes in a roasting tin.' },
      {
        instruction: 'Roast at 220°C until the thigh reads 74°C.',
        durationSec: 4500,
      },
      { instruction: 'Rest 15 minutes before carving so juices settle.', durationSec: 900 },
    ],
    chefNotes: ['Save the carcass — it makes the stock for next week’s soup.'],
    tips: ['Tuck the wing tips under so they do not scorch.'],
    warnings: [
      'Poultry is safe at 74°C in the thickest part of the thigh. Always check with a thermometer.',
    ],
    substitutions: [{ from: 'baby potatoes', to: 'carrots and shallots' }],
    equipment: ['Roasting tin', 'Instant-read thermometer', 'Kitchen twine'],
    storage: 'Refrigerate carved meat up to 4 days.',
    reheating: 'Cover and warm at 150°C with a splash of stock to keep it moist.',
    related: ['risotto-milanese', 'chana-masala'],
    heroSeed: 7,
  },
  {
    id: 'risotto-milanese',
    chapter: 'italian',
    title: 'Risotto alla Milanese',
    tagline: 'Saffron gold, stirred to a slow shimmer.',
    story:
      'People think risotto is hard. It isn’t — it just wants your attention for twenty minutes. Pour yourself something cold, stir, and let it be a little meditative. Stop while it’s looser than you think looks right.',
    tasteLike: 'Rich, buttery, and faintly floral from the saffron.',
    texture: 'Creamy and loose — it should spread like lava, not stand in a mound.',
    spiceLevel: 0,
    allergens: ['dairy'],
    cuisine: 'Italian',
    difficulty: 'medium',
    prepMin: 10,
    cookMin: 30,
    servings: 4,
    nutrition: { calories: 480, protein: 12, carbs: 66, fat: 16, fiber: 2, sugar: 3 },
    tags: ['savory', 'vegetarian', 'comfort'],
    ingredients: [
      {
        items: [
          { quantity: 1.2, unit: 'l', item: 'chicken or vegetable stock', note: 'hot' },
          { quantity: 0.25, unit: 'tsp', item: 'saffron threads' },
          { quantity: 60, unit: 'g', item: 'butter' },
          { quantity: 1, unit: '', item: 'shallot', note: 'finely diced' },
          { quantity: 320, unit: 'g', item: 'carnaroli rice' },
          { quantity: 120, unit: 'ml', item: 'apple juice or extra stock', note: 'for deglaze' },
          { quantity: 60, unit: 'g', item: 'parmesan', note: 'grated' },
        ],
      },
    ],
    steps: [
      { instruction: 'Steep saffron in a ladle of hot stock.' },
      { instruction: 'Sweat the shallot in half the butter until translucent.', durationSec: 300 },
      {
        instruction: 'Add rice and toast until the edges turn glassy.',
        durationSec: 120,
        tip: 'Toasting seals the grain so it releases starch slowly.',
      },
      { instruction: 'Deglaze with apple juice (or stock) and let it evaporate.', durationSec: 120 },
      {
        instruction:
          'Add stock a ladle at a time, stirring, until each is absorbed — including the saffron stock.',
        durationSec: 1080,
      },
      {
        instruction: 'Off heat, beat in cold butter and parmesan until glossy and loose.',
        tip: 'This final emulsion (la mantecatura) is what makes it creamy.',
      },
    ],
    chefNotes: ['It should spread like lava on the plate, not stand in a mound.'],
    tips: ['Keep the stock at a bare simmer so the pan temperature never drops.'],
    warnings: ['Stop while it is looser than you think — it thickens on the plate.'],
    substitutions: [{ from: 'carnaroli rice', to: 'arborio (slightly softer bite)' }],
    equipment: ['Wide heavy pan', 'Ladle'],
    storage: 'Best fresh; refrigerate up to 2 days.',
    reheating: 'Loosen with hot stock over low heat, stirring.',
    related: ['roast-chicken'],
    heroSeed: 21,
  },
  {
    id: 'chana-masala',
    chapter: 'pakistani',
    title: 'Chana Masala',
    tagline: 'Chickpeas braised in a dark, spiced gravy.',
    story:
      'My mother made this every week, and the secret she drilled into me is patience with the onions — really let them go deep and golden, or the gravy stays pale and thin. A tea bag in the water for that classic dark colour is her little trick.',
    tasteLike: 'Deeply spiced and tangy, warming without being sharp.',
    texture: 'Tender chickpeas in a thick, clinging gravy.',
    spiceLevel: 3,
    allergens: [],
    cuisine: 'Pakistani',
    difficulty: 'easy',
    prepMin: 15,
    cookMin: 35,
    servings: 4,
    nutrition: { calories: 340, protein: 14, carbs: 48, fat: 10, fiber: 12, sugar: 8 },
    tags: ['savory', 'vegan', 'spicy', 'high-fiber'],
    ingredients: [
      {
        items: [
          { quantity: 3, unit: 'tbsp', item: 'neutral oil' },
          { quantity: 2, unit: '', item: 'onions', note: 'finely chopped' },
          { quantity: 1, unit: 'tbsp', item: 'ginger-garlic paste' },
          { quantity: 2, unit: '', item: 'tomatoes', note: 'puréed' },
          { quantity: 1.5, unit: 'tsp', item: 'ground cumin' },
          { quantity: 1.5, unit: 'tsp', item: 'ground coriander' },
          { quantity: 0.5, unit: 'tsp', item: 'turmeric' },
          { quantity: 1, unit: 'tsp', item: 'garam masala' },
          { quantity: 800, unit: 'g', item: 'cooked chickpeas', note: 'drained' },
          { quantity: 1, unit: 'tsp', item: 'dried mango powder (amchur)' },
        ],
      },
    ],
    steps: [
      {
        instruction: 'Fry onions in oil until deep golden — patience here builds the color.',
        durationSec: 720,
        tip: 'Under-browned onions leave the gravy pale and thin.',
      },
      { instruction: 'Add ginger-garlic paste and cook off the raw smell.', durationSec: 90 },
      {
        instruction: 'Add tomato purée and ground spices; fry until the oil splits out.',
        durationSec: 480,
      },
      { instruction: 'Fold in chickpeas with a cup of water; simmer to marry.', durationSec: 600 },
      { instruction: 'Finish with garam masala and amchur; mash a few chickpeas to thicken.' },
    ],
    chefNotes: ['A black tea bag simmered in the water deepens the classic dark hue.'],
    tips: ['Bloom whole cumin seeds in the oil first for extra aroma.'],
    warnings: ['Amchur is sour — add gradually and taste.'],
    substitutions: [{ from: 'amchur', to: 'a squeeze of lemon at the end' }],
    equipment: ['Heavy pot'],
    storage: 'Improves overnight; keeps 5 days refrigerated.',
    reheating: 'Loosen with a splash of water over low heat.',
    related: ['shakshuka', 'masala-chai'],
    heroSeed: 14,
  },  {
    id: 'masala-chai',
    chapter: 'coffee',
    title: 'Masala Chai',
    tagline: 'Black tea simmered with warm spice and milk.',
    story:
      'Before any cooking happens in my kitchen, there’s chai. Crush the cardamom in its shell so nothing bitter escapes, and let it rise and fall a few times — that’s what gives it body. Sit down with a cup before you start. The cooking can wait five minutes.',
    tasteLike: 'Sweet, milky, and fragrant with cardamom and ginger.',
    texture: 'Full-bodied and velvety.',
    spiceLevel: 1,
    allergens: ['dairy'],
    cuisine: 'Pakistani',
    difficulty: 'easy',
    prepMin: 5,
    cookMin: 10,
    servings: 2,
    nutrition: { calories: 120, protein: 4, carbs: 16, fat: 5, fiber: 0, sugar: 14 },
    tags: ['sweet', 'hot', 'vegetarian', 'comfort'],
    ingredients: [
      {
        items: [
          { quantity: 300, unit: 'ml', item: 'water' },
          { quantity: 4, unit: '', item: 'green cardamom pods', note: 'crushed' },
          { quantity: 1, unit: '', item: 'cinnamon stick' },
          { quantity: 2, unit: 'slices', item: 'fresh ginger' },
          { quantity: 2, unit: 'tsp', item: 'strong black tea (Assam)' },
          { quantity: 200, unit: 'ml', item: 'whole milk' },
          { quantity: 2, unit: 'tsp', item: 'sugar', note: 'to taste' },
        ],
      },
    ],
    steps: [
      { instruction: 'Simmer water with cardamom, cinnamon, and ginger to release the oils.', durationSec: 300 },
      { instruction: 'Add tea and simmer to a deep amber.', durationSec: 120 },
      {
        instruction: 'Pour in milk and sugar; bring up to a rolling foam, then pull back.',
        durationSec: 180,
        tip: 'Letting it rise and fall a few times builds body.',
      },
      { instruction: 'Strain into cups.' },
    ],
    chefNotes: ['A single clove is plenty — more and it dominates.'],
    tips: ['Crush cardamom in its shell so nothing bitter escapes.'],
    warnings: ['Milk climbs fast — keep a hand on the pan as it foams.'],
    equipment: ['Small saucepan', 'Fine strainer'],
    storage: 'Best fresh.',
    reheating: 'Gently, without boiling hard again.',
    related: ['chana-masala', 'buttermilk-pancakes'],
    heroSeed: 9,
  },
  {
    id: 'kung-pao-tofu',
    chapter: 'chinese',
    title: 'Kung Pao Tofu',
    tagline: 'Blistered chilies, peanuts, and a glossy sauce.',
    story:
      'This cooks in about a minute once the wok is hot, so do all your chopping first — I mean it, everything in little bowls by the stove. Press the tofu really dry so it crisps instead of crumbling. The Sichuan pepper tingle is the whole point.',
    tasteLike: 'Savoury-sweet and tangy, with a numbing chili buzz.',
    texture: 'Crisp tofu, crunchy peanuts, glossy clinging sauce.',
    spiceLevel: 4,
    allergens: ['soy', 'peanut'],
    cuisine: 'Chinese',
    difficulty: 'medium',
    prepMin: 20,
    cookMin: 12,
    servings: 3,
    nutrition: { calories: 380, protein: 20, carbs: 24, fat: 24, fiber: 4, sugar: 10 },
    tags: ['savory', 'vegetarian', 'spicy', 'quick'],
    ingredients: [
      {
        heading: 'Sauce',
        items: [
          { quantity: 2, unit: 'tbsp', item: 'light soy sauce' },
          { quantity: 1, unit: 'tbsp', item: 'black vinegar' },
          { quantity: 2, unit: 'tsp', item: 'sugar' },
          { quantity: 1, unit: 'tsp', item: 'cornstarch' },
        ],
      },
      {
        heading: 'Stir-fry',
        items: [
          { quantity: 400, unit: 'g', item: 'firm tofu', note: 'cubed and pressed' },
          { quantity: 8, unit: '', item: 'dried red chilies' },
          { quantity: 1, unit: 'tsp', item: 'Sichuan peppercorns' },
          { quantity: 3, unit: '', item: 'garlic cloves', note: 'sliced' },
          { quantity: 4, unit: '', item: 'spring onions', note: 'in batons' },
          { quantity: 60, unit: 'g', item: 'roasted peanuts' },
        ],
      },
    ],
    steps: [
      {
        instruction: 'Press tofu dry, then pan-fry until golden on all sides. Set aside.',
        durationSec: 480,
        tip: 'A dry, crusted surface stops the tofu breaking in the toss.',
      },
      { instruction: 'Whisk the sauce ingredients until the cornstarch dissolves.' },
      {
        instruction: 'In hot oil, sizzle chilies and Sichuan pepper briefly, then garlic.',
        durationSec: 40,
      },
      { instruction: 'Return tofu, add sauce, and toss until it turns glossy and clings.', durationSec: 60 },
      { instruction: 'Fold in spring onions and peanuts off the heat.' },
    ],
    chefNotes: ['Toast and grind the Sichuan pepper for a brighter tingle.'],
    tips: ['Have everything cut before the wok gets hot — this cooks in a minute.'],
    warnings: ['Dried chilies scorch fast and turn acrid — keep them moving.'],
    substitutions: [{ from: 'tofu', to: 'chicken thigh, diced' }],
    equipment: ['Wok or wide skillet'],
    storage: 'Keeps 3 days; peanuts soften over time.',
    reheating: 'High heat, quick toss, to re-crisp.',
    related: ['kung-pao-tofu', 'chana-masala'],
    heroSeed: 33,
  },
  {
    id: 'green-shakverdi-salad',
    chapter: 'meals',
    title: 'Herbed Grain & Green Salad',
    tagline: 'Freekeh, herbs by the handful, lemon.',
    story:
      'When I’ve been eating rich food all week, this is my reset. The trick is to be generous — double the herbs so it reads green, not beige. It keeps for days undressed, so I make a big bowl on Sunday and lean on it all week.',
    tasteLike: 'Bright and lemony, grassy with fresh herbs.',
    texture: 'Chewy grains against crisp cucumber and juicy tomato.',
    spiceLevel: 0,
    allergens: ['gluten'],
    cuisine: 'Levantine',
    difficulty: 'easy',
    prepMin: 15,
    cookMin: 20,
    servings: 4,
    nutrition: { calories: 300, protein: 9, carbs: 40, fat: 12, fiber: 9, sugar: 4 },
    tags: ['savory', 'vegan', 'high-fiber', 'meal-prep'],
    ingredients: [
      {
        items: [
          { quantity: 200, unit: 'g', item: 'freekeh or farro' },
          { quantity: 1, unit: 'bunch', item: 'parsley', note: 'chopped' },
          { quantity: 1, unit: 'bunch', item: 'mint', note: 'chopped' },
          { quantity: 1, unit: '', item: 'cucumber', note: 'diced' },
          { quantity: 150, unit: 'g', item: 'cherry tomatoes', note: 'halved' },
          { quantity: 1, unit: '', item: 'lemon', note: 'juiced' },
          { quantity: 3, unit: 'tbsp', item: 'olive oil' },
        ],
      },
    ],
    steps: [
      { instruction: 'Simmer freekeh until tender with a bite; drain and cool.', durationSec: 1200 },
      { instruction: 'Toss with herbs, cucumber, and tomatoes.' },
      { instruction: 'Dress with lemon, oil, salt; rest 10 minutes to marry.', durationSec: 600 },
    ],
    chefNotes: ['Double the herbs — this salad should read green, not beige.'],
    tips: ['Salt the tomatoes first to draw out sweetness.'],
    warnings: ['Dress just before serving if making ahead, to keep herbs bright.'],
    equipment: ['Saucepan', 'Sieve'],
    storage: 'Undressed grains keep 4 days.',
    reheating: 'Serve at room temperature.',
    related: ['chana-masala', 'shakshuka'],
    heroSeed: 41,
  },
  {
    id: 'sourdough-focaccia',
    chapter: 'breads',
    title: 'Rosemary Focaccia',
    tagline: 'Dimpled, olive-oil rich, salt-flecked.',
    story:
      'My gateway bread — no kneading, just a few folds and a lot of patience. Be shameless with the olive oil in the tin; that’s what gives you those crisp, golden edges. Dimple deep with oily fingers and it feels like play, not work.',
    tasteLike: 'Rich with olive oil, savoury with rosemary and flaky salt.',
    texture: 'Crisp-bottomed, airy and open in the middle.',
    spiceLevel: 0,
    allergens: ['gluten'],
    cuisine: 'Italian',
    difficulty: 'medium',
    prepMin: 25,
    cookMin: 25,
    servings: 8,
    nutrition: { calories: 260, protein: 6, carbs: 38, fat: 9, fiber: 2, sugar: 1 },
    tags: ['savory', 'vegan', 'bread', 'make-ahead'],
    ingredients: [
      {
        items: [
          { quantity: 500, unit: 'g', item: 'strong bread flour' },
          { quantity: 400, unit: 'ml', item: 'water', note: 'lukewarm' },
          { quantity: 7, unit: 'g', item: 'instant yeast' },
          { quantity: 10, unit: 'g', item: 'fine salt' },
          { quantity: 60, unit: 'ml', item: 'olive oil', note: 'plus more for the tin' },
          { quantity: 1, unit: 'tbsp', item: 'rosemary leaves' },
          { quantity: null, unit: '', item: 'flaky sea salt' },
        ],
      },
    ],
    steps: [
      {
        instruction: 'Mix flour, water, yeast, and salt to a shaggy dough. No kneading.',
        tip: 'High hydration does the work — you just fold.',
      },
      {
        instruction: 'Over the next 2 hours, fold the dough in the bowl 4 times, resting between.',
        durationSec: 7200,
      },
      { instruction: 'Oil a tin generously; stretch dough to fill and rest until puffy.', durationSec: 2400 },
      {
        instruction: 'Dimple deeply with oiled fingers, add rosemary and flaky salt.',
        tip: 'Press all the way to the tin — those wells hold the oil.',
      },
      { instruction: 'Bake at 230°C until deep gold and crisp-bottomed.', durationSec: 1500 },
    ],
    chefNotes: ['A long cold overnight proof in the fridge deepens the flavor.'],
    tips: ['Brush with a little water-oil emulsion before baking for extra crackle.'],
    warnings: ['Under-oiled tins mean a stuck loaf — be generous.'],
    substitutions: [{ from: 'rosemary', to: 'thin-sliced onion and thyme' }],
    equipment: ['Rimmed tin', 'Bench scraper'],
    storage: 'Best day-of; refresh next day in the oven.',
    reheating: '180°C for 5 minutes restores the crust.',
    related: ['risotto-milanese', 'roast-chicken'],
    heroSeed: 5,
  },
  {
    id: 'caprese-orzo',
    chapter: 'italian',
    title: '20-Minute Caprese Orzo',
    tagline: 'Tomato, basil, mozzarella — dinner, fast.',
    story:
      'My back-pocket weeknight dinner. Salt the pasta water like the sea — that’s where the seasoning comes from — and save a cup before you drain, because that starchy water pulls it all into a light sauce. Cheese goes in off the heat, always.',
    tasteLike: 'Fresh and summery — sweet tomato, milky mozzarella, basil.',
    texture: 'Tender orzo in a light, glossy sauce with soft cheese.',
    spiceLevel: 0,
    allergens: ['gluten', 'dairy'],
    cuisine: 'Italian',
    difficulty: 'easy',
    prepMin: 5,
    cookMin: 15,
    servings: 3,
    nutrition: { calories: 430, protein: 16, carbs: 58, fat: 15, fiber: 4, sugar: 6 },
    tags: ['savory', 'vegetarian', 'quick', 'one-pan'],
    ingredients: [
      {
        items: [
          { quantity: 250, unit: 'g', item: 'orzo' },
          { quantity: 300, unit: 'g', item: 'cherry tomatoes', note: 'halved' },
          { quantity: 2, unit: '', item: 'garlic cloves', note: 'sliced' },
          { quantity: 3, unit: 'tbsp', item: 'olive oil' },
          { quantity: 150, unit: 'g', item: 'mozzarella pearls' },
          { quantity: 1, unit: 'handful', item: 'basil' },
        ],
      },
    ],
    steps: [
      { instruction: 'Boil orzo in salted water until al dente; reserve a cup of water.', durationSec: 540 },
      { instruction: 'Meanwhile soften garlic and tomatoes in oil until slumped.', durationSec: 360 },
      {
        instruction: 'Toss drained orzo with the tomatoes, loosening with pasta water.',
        tip: 'The starchy water pulls it into a light sauce.',
      },
      { instruction: 'Off heat, fold in mozzarella and basil so it just softens.' },
    ],
    chefNotes: ['A spoon of pesto stirred through is a fine shortcut on a busy night.'],
    tips: ['Salt the pasta water like the sea — it seasons from within.'],
    warnings: ['Add cheese off the heat or it turns stringy and tough.'],
    equipment: ['Pot', 'Skillet'],
    storage: 'Keeps 2 days; best fresh.',
    reheating: 'Splash of water, gentle heat.',
    related: ['risotto-milanese', 'green-shakverdi-salad'],
    heroSeed: 17,
  },
  {
    id: 'halloumi-wrap',
    chapter: 'snacks',
    title: 'Grilled Halloumi Wrap',
    tagline: 'Charred cheese, quick pickle, garlic yogurt.',
    story:
      'When friends drop by unannounced, this is what I make — it feels generous but takes minutes. Pat the halloumi really dry so it sears golden instead of steaming, and pull it while it’s still soft. A drizzle of chili honey is worth the sticky fingers.',
    tasteLike: 'Salty grilled cheese, cool garlicky yogurt, sharp pickle.',
    texture: 'Squeaky-tender halloumi, crunchy onion, soft warm bread.',
    spiceLevel: 1,
    allergens: ['dairy', 'gluten'],
    cuisine: 'Mediterranean',
    difficulty: 'easy',
    prepMin: 12,
    cookMin: 8,
    servings: 2,
    nutrition: { calories: 520, protein: 24, carbs: 42, fat: 30, fiber: 5, sugar: 8 },
    tags: ['savory', 'vegetarian', 'quick'],
    ingredients: [
      {
        items: [
          { quantity: 225, unit: 'g', item: 'halloumi', note: 'sliced' },
          { quantity: 2, unit: '', item: 'flatbreads' },
          { quantity: 150, unit: 'g', item: 'yogurt' },
          { quantity: 1, unit: '', item: 'garlic clove', note: 'grated' },
          { quantity: 0.5, unit: '', item: 'red onion', note: 'thin, quick-pickled' },
          { quantity: 1, unit: 'handful', item: 'salad leaves' },
        ],
      },
    ],
    steps: [
      { instruction: 'Quick-pickle onion in lemon juice and a pinch of salt.', durationSec: 600 },
      { instruction: 'Stir garlic into yogurt with salt.' },
      {
        instruction: 'Sear halloumi in a dry hot pan until deep gold both sides.',
        durationSec: 300,
        tip: 'Halloumi needs no oil — it renders its own.',
      },
      { instruction: 'Warm flatbreads, spread yogurt, pile halloumi, pickle, and leaves; roll.' },
    ],
    chefNotes: ['A drizzle of chili honey over the cheese is worth the sticky fingers.'],
    tips: ['Pat halloumi dry so it sears instead of steaming.'],
    warnings: ['Halloumi turns squeaky and rubbery if cooked too long — pull it at deep gold.'],
    equipment: ['Grill pan'],
    storage: 'Assemble to order.',
    reheating: 'Re-sear the cheese only.',
    related: ['green-shakverdi-salad', 'caprese-orzo'],
    heroSeed: 24,
  },
  ...EXTRA_RECIPES,
  ...FILL_RECIPES,
  ...FOODFUSION_RECIPES,
  ...GOAL_RECIPES,
  ...MEALDB_RECIPES,
];

export const RECIPE_MAP = Object.fromEntries(RECIPES.map((r) => [r.id, r])) as Record<
  string,
  Recipe
>;

export const recipesByChapter = (chapter: string) =>
  RECIPES.filter((r) => r.chapter === chapter);
