import type { ChapterId, Difficulty, Recipe } from './types';

/** Goal-mode recipes: breakfast, high-protein, light, budget. */

type Tup = [number | null, string, string, string?];
type St = string | [string, number];

interface Mini {
  id: string;
  chapter: ChapterId;
  title: string;
  tagline: string;
  story: string;
  tasteLike: string;
  texture: string;
  cuisine: string;
  difficulty: Difficulty;
  spice?: number;
  allergens?: string[];
  prep: number;
  cook: number;
  servings: number;
  cal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  tags: string[];
  dietTags?: Recipe['dietTags'];
  costTier?: Recipe['costTier'];
  pantryStaple?: boolean;
  ing: Tup[];
  steps: St[];
  tips?: string[];
  related?: string[];
  seed: number;
}

function r(x: Mini): Recipe {
  return {
    id: x.id,
    chapter: x.chapter,
    title: x.title,
    tagline: x.tagline,
    story: x.story,
    tasteLike: x.tasteLike,
    texture: x.texture,
    cuisine: x.cuisine,
    difficulty: x.difficulty,
    spiceLevel: x.spice ?? 0,
    allergens: x.allergens ?? [],
    prepMin: x.prep,
    cookMin: x.cook,
    servings: x.servings,
    nutrition: {
      calories: x.cal,
      protein: x.protein,
      carbs: x.carbs,
      fat: x.fat,
      fiber: x.fiber ?? 3,
      sugar: x.sugar ?? 4,
    },
    tags: x.tags,
    macrosVerified: true,
    dietTags: x.dietTags,
    costTier: x.costTier ?? 'budget',
    pantryStaple: x.pantryStaple,
    ingredients: [{ items: x.ing.map(([q, u, it, n]) => ({ quantity: q, unit: u, item: it, note: n })) }],
    steps: x.steps.map((s) => (Array.isArray(s) ? { instruction: s[0], durationSec: s[1] } : { instruction: s })),
    tips: x.tips,
    related: x.related,
    heroSeed: x.seed,
  };
}

export const GOAL_RECIPES: Recipe[] = [
  r({
    id: 'goal-overnight-oats',
    chapter: 'meals',
    title: 'Overnight Oats',
    tagline: 'Jar breakfast that waits for you.',
    story: 'I stir this before bed so mornings stay calm. Greek yogurt and oats do the heavy lifting — no frying pan required.',
    tasteLike: 'Creamy oat, gentle honey, berry brightness.',
    texture: 'Soft, spoonable, lightly chewy.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 5,
    cook: 0,
    servings: 1,
    cal: 340,
    protein: 18,
    carbs: 48,
    fat: 8,
    fiber: 7,
    sugar: 12,
    tags: ['breakfast', 'make-ahead', 'vegetarian'],
    dietTags: ['breakfast', 'high-protein', 'vegetarian', 'budget'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['dairy', 'gluten'],
    ing: [
      [50, 'g', 'rolled oats'],
      [120, 'g', 'Greek yogurt', '0% or 2%'],
      [80, 'ml', 'milk', 'low-fat'],
      [1, 'tsp', 'chia seeds'],
      [1, 'tsp', 'honey'],
      [80, 'g', 'mixed berries', 'fresh or frozen'],
    ],
    steps: [
      'Stir oats, yogurt, milk, chia, and honey in a jar.',
      'Top with berries; refrigerate overnight.',
      'Eat cold or warm gently.',
    ],
    tips: ['Add a scoop of protein powder if you train early.'],
    related: ['goal-chia-pot', 'goal-greek-yogurt-bowl'],
    seed: 9001,
  }),

  r({
    id: 'goal-egg-white-omelette',
    chapter: 'meals',
    title: 'Egg White Omelette',
    tagline: 'Fluffy whites, lots of veg, almost no oil.',
    story: 'My light breakfast when I still want something hot. Spinach and tomato make it feel like a real plate, not a gym meal.',
    tasteLike: 'Clean egg, soft veg, peppery finish.',
    texture: 'Tender omelette, juicy filling.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 8,
    cook: 8,
    servings: 1,
    cal: 180,
    protein: 24,
    carbs: 6,
    fat: 5,
    fiber: 2,
    sugar: 3,
    tags: ['breakfast', 'high-protein', 'low-cal'],
    dietTags: ['breakfast', 'high-protein', 'low-cal', 'gluten-free', 'low-carb'],
    costTier: 'budget',
    allergens: ['egg'],
    ing: [
      [4, '', 'egg whites'],
      [1, '', 'whole egg', 'optional richness'],
      [1, 'handful', 'spinach'],
      [1, '', 'tomato', 'diced'],
      [1, 'tsp', 'olive oil'],
      [null, '', 'salt and pepper'],
    ],
    steps: [
      'Whisk whites (and whole egg if using) with salt.',
      'Warm oil; wilt spinach and tomato.',
      'Pour eggs; cook gently until set; fold.',
    ],
    tips: ['Nonstick pan = less oil.'],
    related: ['goal-besan-chilla', 'omelette-dinner'],
    seed: 9002,
  }),

  r({
    id: 'goal-greek-yogurt-bowl',
    chapter: 'snacks',
    title: 'Greek Yogurt Bowl',
    tagline: 'Protein base, crunchy top, five minutes.',
    story: 'When I’m not hungry enough for a meal but need staying power. Nuts and fruit keep it from tasting like diet food.',
    tasteLike: 'Tangy yogurt, sweet fruit, toasted crunch.',
    texture: 'Creamy with crisp bites.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 5,
    cook: 0,
    servings: 1,
    cal: 290,
    protein: 22,
    carbs: 28,
    fat: 10,
    fiber: 4,
    sugar: 16,
    tags: ['breakfast', 'snack', 'vegetarian'],
    dietTags: ['breakfast', 'high-protein', 'vegetarian', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['dairy', 'nuts'],
    ing: [
      [200, 'g', 'Greek yogurt', '0%'],
      [1, '', 'banana', 'sliced'],
      [15, 'g', 'almonds', 'chopped'],
      [1, 'tsp', 'honey'],
      [1, 'tsp', 'flaxseed'],
    ],
    steps: [
      'Spoon yogurt into a bowl.',
      'Top with banana, almonds, flax, and honey.',
    ],
    tips: ['Frozen berries work when bananas are gone.'],
    related: ['goal-overnight-oats', 'yogurt-parfait'],
    seed: 9003,
  }),

  r({
    id: 'goal-chapli-bowl',
    chapter: 'pakistani',
    title: 'Chapli Bowl',
    tagline: 'Lean chapli over salad, not under oil.',
    story: 'Street flavor without the deep-fry hangover. I pan-sear thin patties and pile them on cucumber and tomato.',
    tasteLike: 'Spiced mince, fresh herbs, lemon lift.',
    texture: 'Crisp edges, soft salad base.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 3,
    prep: 20,
    cook: 12,
    servings: 2,
    cal: 380,
    protein: 32,
    carbs: 14,
    fat: 22,
    fiber: 4,
    sugar: 5,
    tags: ['savory', 'high-protein', 'bowl'],
    dietTags: ['high-protein', 'low-carb', 'gluten-free'],
    costTier: 'mid',
    allergens: [],
    ing: [
      [300, 'g', 'lean minced beef', 'or chicken'],
      [1, '', 'onion', 'finely chopped'],
      [1, 'tsp', 'coriander seeds', 'crushed'],
      [1, 'tsp', 'red chili'],
      [1, 'tbsp', 'coriander', 'chopped'],
      [2, 'cups', 'salad greens'],
      [1, '', 'cucumber', 'sliced'],
      [1, 'tsp', 'oil'],
    ],
    steps: [
      'Mix mince with onion, spices, and herbs; form thin patties.',
      ['Pan-sear in a little oil until cooked through.', 600],
      'Serve over greens and cucumber with lemon.',
    ],
    tips: ['Wet hands so the mince doesn’t stick.'],
    related: ['seekh-kebab', 'goal-lean-karahi'],
    seed: 9004,
  }),

  r({
    id: 'goal-high-protein-daal',
    chapter: 'pakistani',
    title: 'High-Protein Daal',
    tagline: 'Masoor + yogurt finish, lighter tadka.',
    story: 'Daal is already honest food — I just keep the oil shy and finish with yogurt for extra protein.',
    tasteLike: 'Earthy lentils, garlic, gentle chili.',
    texture: 'Silky, spoonable.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 10,
    cook: 30,
    servings: 3,
    cal: 260,
    protein: 18,
    carbs: 36,
    fat: 5,
    fiber: 10,
    sugar: 4,
    tags: ['savory', 'vegetarian', 'budget'],
    dietTags: ['high-protein', 'vegetarian', 'budget', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['dairy'],
    ing: [
      [200, 'g', 'masoor daal', 'rinsed'],
      [1, '', 'onion', 'sliced'],
      [2, '', 'garlic cloves', 'sliced'],
      [1, 'tsp', 'cumin seeds'],
      [1, 'tsp', 'turmeric'],
      [1, 'tbsp', 'oil'],
      [100, 'g', 'yogurt', 'to finish'],
    ],
    steps: [
      'Boil daal with turmeric and salt until soft.',
      'Make a light tadka with oil, cumin, onion, garlic.',
      'Stir tadka into daal; swirl yogurt at the table.',
    ],
    tips: ['Blend half for creaminess without cream.'],
    related: ['lentil-dal', 'jia-dal-chawal'],
    seed: 9005,
  }),

  r({
    id: 'goal-lean-karahi',
    chapter: 'pakistani',
    title: 'Lean Karahi',
    tagline: 'Tomato-forward, skinless chicken, less ghee.',
    story: 'Same karahi soul, trimmed fat. I use skinless thighs and let tomatoes do the richness.',
    tasteLike: 'Bright tomato, ginger heat, coriander.',
    texture: 'Juicy chicken, thick masala.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 3,
    prep: 15,
    cook: 30,
    servings: 4,
    cal: 320,
    protein: 36,
    carbs: 10,
    fat: 14,
    fiber: 3,
    sugar: 5,
    tags: ['savory', 'curry', 'high-protein'],
    dietTags: ['high-protein', 'low-carb', 'gluten-free'],
    costTier: 'mid',
    allergens: [],
    ing: [
      [600, 'g', 'chicken', 'skinless, bone-in or boneless'],
      [4, '', 'tomatoes', 'chopped'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [2, 'tbsp', 'oil'],
      [1, 'tsp', 'red chili'],
      [1, 'tsp', 'cumin'],
      [1, 'handful', 'coriander'],
    ],
    steps: [
      'Sear chicken in oil; add paste and spices.',
      'Add tomatoes; cook until oil separates lightly.',
      ['Simmer until chicken is tender.', 900],
      'Finish with coriander.',
    ],
    tips: ['Skip cream — tomatoes + patience are enough.'],
    related: ['karahi-chicken', 'jia-karahi'],
    seed: 9006,
  }),

  r({
    id: 'goal-protein-smoothie',
    chapter: 'snacks',
    title: 'Protein Smoothie',
    tagline: 'Banana, milk, yogurt — blender breakfast.',
    story: 'For days I leave the house too fast. One glass, real ingredients, no syrup mystery.',
    tasteLike: 'Banana milkshake, lightly sweet.',
    texture: 'Thick, cold, drinkable.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 5,
    cook: 0,
    servings: 1,
    cal: 310,
    protein: 26,
    carbs: 38,
    fat: 5,
    fiber: 4,
    sugar: 22,
    tags: ['breakfast', 'drink', 'high-protein'],
    dietTags: ['breakfast', 'high-protein', 'vegetarian', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['dairy'],
    ing: [
      [1, '', 'banana', 'frozen preferred'],
      [200, 'ml', 'low-fat milk'],
      [100, 'g', 'Greek yogurt'],
      [1, 'scoop', 'protein powder', 'optional'],
      [1, 'tsp', 'peanut butter', 'optional'],
    ],
    steps: [
      'Blend everything until smooth.',
      'Drink immediately.',
    ],
    tips: ['Skip powder if yogurt is thick enough.'],
    related: ['goal-overnight-oats', 'goal-chia-pot'],
    seed: 9007,
  }),

  r({
    id: 'goal-chana-chaat',
    chapter: 'snacks',
    title: 'Chana Chaat',
    tagline: 'Chickpeas, onion, chaat masala — street light.',
    story: 'My afternoon fix that actually fills me. Boiled chana from the fridge, five minutes of chopping.',
    tasteLike: 'Tangy, spicy, lemony.',
    texture: 'Firm chickpeas, crunchy onion.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 10,
    cook: 0,
    servings: 2,
    cal: 220,
    protein: 12,
    carbs: 32,
    fat: 5,
    fiber: 9,
    sugar: 6,
    tags: ['snack', 'vegetarian', 'budget'],
    dietTags: ['vegetarian', 'budget', 'high-protein', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: [],
    ing: [
      [300, 'g', 'boiled chickpeas'],
      [1, '', 'onion', 'diced'],
      [1, '', 'tomato', 'diced'],
      [1, '', 'cucumber', 'diced'],
      [1, 'tsp', 'chaat masala'],
      [1, '', 'lemon', 'juiced'],
      [null, '', 'coriander', 'chopped'],
    ],
    steps: [
      'Toss chickpeas with veg, chaat masala, and lemon.',
      'Finish with coriander.',
    ],
    tips: ['Tinned chickpeas are fine — rinse well.'],
    related: ['boiled-chana', 'fruit-chaat', 'goal-sprout-chaat'],
    seed: 9008,
  }),

  r({
    id: 'goal-tuna-sabudana',
    chapter: 'meals',
    title: 'Tuna Sabudana',
    tagline: 'Light tapioca stir with tinned tuna.',
    story: 'Unexpected combo that works on busy nights. Soft pearls, savory tuna, squeeze of lemon.',
    tasteLike: 'Mild sabudana, briny tuna, cumin.',
    texture: 'Chewy pearls, flaky fish.',
    cuisine: 'Fusion',
    difficulty: 'easy',
    spice: 1,
    prep: 15,
    cook: 10,
    servings: 2,
    cal: 340,
    protein: 28,
    carbs: 42,
    fat: 6,
    fiber: 2,
    sugar: 2,
    tags: ['savory', 'high-protein', 'quick'],
    dietTags: ['high-protein', 'gluten-free', 'budget'],
    costTier: 'budget',
    allergens: ['fish'],
    ing: [
      [100, 'g', 'sabudana', 'soaked'],
      [1, '', 'tin tuna', 'in water, drained'],
      [1, '', 'onion', 'sliced'],
      [1, 'tsp', 'cumin seeds'],
      [1, 'tsp', 'oil'],
      [1, '', 'green chili', 'optional'],
    ],
    steps: [
      'Soak sabudana until soft; drain well.',
      'Sauté onion and cumin in oil; add chili.',
      'Toss in sabudana and tuna; cook until pearls turn translucent.',
    ],
    tips: ['Drain sabudana thoroughly or it goes gluey.'],
    related: ['goal-grilled-fish-masala', 'sheet-pan-salmon'],
    seed: 9009,
  }),

  r({
    id: 'goal-paneer-bhurji',
    chapter: 'pakistani',
    title: 'Paneer Bhurji',
    tagline: 'Scrambled paneer with onion and tomato.',
    story: 'When eggs feel tired but I still want protein. Soft paneer takes spices beautifully.',
    tasteLike: 'Mild cheese, savory masala.',
    texture: 'Soft crumbles, juicy onion.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 10,
    cook: 12,
    servings: 2,
    cal: 310,
    protein: 22,
    carbs: 10,
    fat: 20,
    fiber: 2,
    sugar: 5,
    tags: ['savory', 'vegetarian', 'high-protein'],
    dietTags: ['vegetarian', 'high-protein', 'low-carb', 'gluten-free'],
    costTier: 'mid',
    allergens: ['dairy'],
    ing: [
      [200, 'g', 'paneer', 'crumbled'],
      [1, '', 'onion', 'chopped'],
      [2, '', 'tomatoes', 'chopped'],
      [1, 'tsp', 'cumin'],
      [1, 'tsp', 'turmeric'],
      [1, 'tbsp', 'oil'],
      [null, '', 'coriander'],
    ],
    steps: [
      'Sauté onion in oil; add spices.',
      'Add tomato; cook until soft.',
      'Stir in paneer; cook 3–4 minutes; finish with coriander.',
    ],
    tips: ['Use low-fat paneer if you find it.'],
    related: ['goal-egg-bhurji-light', 'goal-tofu-scramble'],
    seed: 9010,
  }),

  r({
    id: 'goal-besan-chilla',
    chapter: 'meals',
    title: 'Besan Chilla',
    tagline: 'Chickpea pancake stuffed with veg.',
    story: 'Budget breakfast that eats like a meal. Crispy edges, soft middle, no fancy flour.',
    tasteLike: 'Toasted gram flour, onion, chili.',
    texture: 'Crisp rim, tender center.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 10,
    cook: 15,
    servings: 2,
    cal: 250,
    protein: 14,
    carbs: 32,
    fat: 7,
    fiber: 6,
    sugar: 4,
    tags: ['breakfast', 'vegetarian', 'budget'],
    dietTags: ['breakfast', 'vegetarian', 'budget', 'high-protein', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: [],
    ing: [
      [100, 'g', 'besan'],
      [1, '', 'onion', 'finely chopped'],
      [1, '', 'tomato', 'chopped'],
      [1, '', 'green chili', 'chopped'],
      [150, 'ml', 'water'],
      [1, 'tsp', 'oil', 'per chilla'],
    ],
    steps: [
      'Whisk besan with water to a thin batter; add veg and salt.',
      'Pour onto a hot lightly oiled tawa; cook both sides.',
      'Serve with yogurt or mint chutney.',
    ],
    tips: ['Rest batter 10 minutes for softer chillas.'],
    related: ['goal-egg-white-omelette', 'goal-oat-pancake'],
    seed: 9011,
  }),

  r({
    id: 'goal-baked-samosa',
    chapter: 'snacks',
    title: 'Baked Samosa',
    tagline: 'Oven-crisp shells, classic aloo filling.',
    story: 'Same filling, no deep fryer. Brush with oil and bake until the pastry blisters.',
    tasteLike: 'Spiced potato, toasted pastry.',
    texture: 'Flaky shell, soft filling.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 2,
    prep: 30,
    cook: 25,
    servings: 4,
    cal: 210,
    protein: 5,
    carbs: 32,
    fat: 7,
    fiber: 3,
    sugar: 2,
    tags: ['snack', 'vegetarian', 'baked'],
    dietTags: ['vegetarian', 'budget'],
    costTier: 'budget',
    allergens: ['gluten'],
    ing: [
      [8, '', 'samosa wrappers', 'or filo sheets'],
      [3, '', 'potatoes', 'boiled, mashed'],
      [1, 'tsp', 'cumin'],
      [1, 'tsp', 'garam masala'],
      [50, 'g', 'peas'],
      [1, 'tbsp', 'oil', 'for brushing'],
    ],
    steps: [
      'Season mash with spices and peas.',
      'Fill wrappers; seal with water.',
      ['Brush with oil; bake at 200°C until golden.', 1500],
    ],
    tips: ['Air fryer works at 180°C for ~15 minutes.'],
    related: ['samosas', 'goal-airfryer-pakora'],
    seed: 9012,
  }),

  r({
    id: 'goal-airfryer-tikka',
    chapter: 'pakistani',
    title: 'Air-Fryer Tikka',
    tagline: 'Yogurt-marinated chicken, char without charcoal.',
    story: 'Weeknight tikka when the BBQ isn’t happening. Yogurt tenderizes; the air fryer crisps the edges.',
    tasteLike: 'Smoky spice, tangy yogurt.',
    texture: 'Charred tips, juicy inside.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 3,
    prep: 15,
    cook: 18,
    servings: 3,
    cal: 280,
    protein: 38,
    carbs: 6,
    fat: 10,
    fiber: 1,
    sugar: 3,
    tags: ['savory', 'high-protein', 'air-fryer'],
    dietTags: ['high-protein', 'low-carb', 'gluten-free'],
    costTier: 'mid',
    allergens: ['dairy'],
    ing: [
      [500, 'g', 'chicken breast', 'cubed'],
      [150, 'g', 'yogurt'],
      [1, 'tbsp', 'tikka masala'],
      [1, 'tbsp', 'ginger-garlic paste'],
      [1, 'tsp', 'oil'],
      [null, '', 'lemon'],
    ],
    steps: [
      'Marinate chicken in yogurt, paste, and spices (30+ min).',
      ['Air-fry at 200°C, shaking once, until cooked.', 1080],
      'Squeeze lemon; rest 2 minutes.',
    ],
    tips: ['Pat marinade thick so it sticks.'],
    related: ['goal-lean-karahi', 'ff-fish-tikka'],
    seed: 9013,
  }),

  r({
    id: 'goal-chia-pot',
    chapter: 'snacks',
    title: 'Chia Pot',
    tagline: 'Seed pudding that sets while you sleep.',
    story: 'Tiny effort, big fiber. I keep a few jars ready for snack attacks.',
    tasteLike: 'Mild coconut or milk, vanilla whisper.',
    texture: 'Gel pearls, creamy.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 5,
    cook: 0,
    servings: 1,
    cal: 240,
    protein: 10,
    carbs: 22,
    fat: 12,
    fiber: 12,
    sugar: 8,
    tags: ['breakfast', 'snack', 'make-ahead'],
    dietTags: ['breakfast', 'vegetarian', 'gluten-free', 'budget'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['dairy'],
    ing: [
      [3, 'tbsp', 'chia seeds'],
      [180, 'ml', 'low-fat milk'],
      [50, 'g', 'yogurt'],
      [1, 'tsp', 'honey'],
      [null, '', 'fruit', 'to top'],
    ],
    steps: [
      'Stir chia, milk, yogurt, and honey.',
      'Rest 10 minutes; stir again; chill 2+ hours.',
      'Top with fruit.',
    ],
    tips: ['Second stir stops clumps.'],
    related: ['goal-overnight-oats', 'goal-greek-yogurt-bowl'],
    seed: 9014,
  }),

  r({
    id: 'goal-egg-bhurji-light',
    chapter: 'meals',
    title: 'Light Egg Bhurji',
    tagline: 'Desi scramble with more veg than oil.',
    story: 'Bhurji for breakfast or late dinner. Extra tomato keeps it juicy without butter.',
    tasteLike: 'Spiced egg, soft onion, fresh chili.',
    texture: 'Soft curds, moist veg.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 8,
    cook: 10,
    servings: 2,
    cal: 220,
    protein: 16,
    carbs: 8,
    fat: 14,
    fiber: 2,
    sugar: 4,
    tags: ['breakfast', 'savory', 'quick'],
    dietTags: ['breakfast', 'high-protein', 'low-carb', 'budget', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['egg'],
    ing: [
      [4, '', 'eggs'],
      [1, '', 'onion', 'chopped'],
      [2, '', 'tomatoes', 'chopped'],
      [1, 'tsp', 'oil'],
      [0.5, 'tsp', 'turmeric'],
      [null, '', 'coriander'],
    ],
    steps: [
      'Sauté onion in oil; add tomato and turmeric.',
      'Pour beaten eggs; scramble softly.',
      'Finish with coriander.',
    ],
    tips: ['Pull off heat while still slightly soft.'],
    related: ['goal-paneer-bhurji', 'goal-egg-white-omelette'],
    seed: 9015,
  }),

  r({
    id: 'goal-moong-salad',
    chapter: 'snacks',
    title: 'Sprouted Moong Salad',
    tagline: 'Crunchy sprouts, lemon, chaat spice.',
    story: 'Fridge-clearing salad that still feels intentional. Protein without cooking much.',
    tasteLike: 'Fresh, lemony, lightly spicy.',
    texture: 'Crisp sprouts, juicy tomato.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 1,
    prep: 10,
    cook: 0,
    servings: 2,
    cal: 160,
    protein: 11,
    carbs: 24,
    fat: 2,
    fiber: 8,
    sugar: 5,
    tags: ['salad', 'vegetarian', 'light'],
    dietTags: ['vegetarian', 'low-cal', 'budget', 'high-protein', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: [],
    ing: [
      [200, 'g', 'sprouted moong'],
      [1, '', 'tomato', 'diced'],
      [0.5, '', 'onion', 'diced'],
      [1, '', 'cucumber', 'diced'],
      [1, 'tsp', 'chaat masala'],
      [1, '', 'lemon'],
    ],
    steps: [
      'Toss sprouts with veg, chaat masala, and lemon.',
      'Season with salt; serve cold.',
    ],
    tips: ['Steam sprouts 2 minutes if you prefer softer.'],
    related: ['goal-chana-chaat', 'goal-sprout-chaat'],
    seed: 9016,
  }),

  r({
    id: 'goal-chicken-salad-wrap',
    chapter: 'meals',
    title: 'Chicken Salad Wrap',
    tagline: 'Leftover chicken, yogurt dressing, soft wrap.',
    story: 'Lunchbox hero. Greek yogurt instead of mayo keeps it light but creamy.',
    tasteLike: 'Herb chicken, cool yogurt, crunch.',
    texture: 'Soft wrap, crisp lettuce.',
    cuisine: 'Fusion',
    difficulty: 'easy',
    prep: 12,
    cook: 0,
    servings: 2,
    cal: 360,
    protein: 32,
    carbs: 34,
    fat: 10,
    fiber: 4,
    sugar: 5,
    tags: ['lunch', 'high-protein', 'wrap'],
    dietTags: ['high-protein', 'budget'],
    costTier: 'budget',
    allergens: ['dairy', 'gluten'],
    ing: [
      [250, 'g', 'cooked chicken', 'shredded'],
      [100, 'g', 'Greek yogurt'],
      [1, 'tsp', 'mustard'],
      [2, '', 'wraps or roti'],
      [1, 'handful', 'lettuce'],
      [0.5, '', 'cucumber', 'sticks'],
    ],
    steps: [
      'Mix chicken with yogurt, mustard, salt, and pepper.',
      'Warm wraps; fill with chicken, lettuce, cucumber.',
      'Roll tight; slice if packing.',
    ],
    tips: ['Air-fryer tikka leftovers are perfect here.'],
    related: ['goal-airfryer-tikka', 'halloumi-wrap'],
    seed: 9017,
  }),

  r({
    id: 'goal-tofu-scramble',
    chapter: 'meals',
    title: 'Tofu Scramble',
    tagline: 'Turmeric tofu, soft and savory.',
    story: 'Plant protein for mornings when eggs feel heavy. Crumble firm tofu and treat it like bhurji.',
    tasteLike: 'Savory, eggy spice, soft onion.',
    texture: 'Soft crumbles.',
    cuisine: 'Fusion',
    difficulty: 'easy',
    spice: 1,
    prep: 8,
    cook: 10,
    servings: 2,
    cal: 210,
    protein: 18,
    carbs: 10,
    fat: 11,
    fiber: 3,
    sugar: 3,
    tags: ['breakfast', 'vegan', 'high-protein'],
    dietTags: ['vegan', 'vegetarian', 'high-protein', 'low-carb', 'gluten-free', 'breakfast'],
    costTier: 'budget',
    allergens: ['soy'],
    ing: [
      [300, 'g', 'firm tofu', 'crumbled'],
      [1, '', 'onion', 'chopped'],
      [1, '', 'tomato', 'chopped'],
      [0.5, 'tsp', 'turmeric'],
      [1, 'tsp', 'oil'],
      [null, '', 'black pepper'],
    ],
    steps: [
      'Sauté onion in oil; add tomato and turmeric.',
      'Add tofu; cook until heated and lightly dry.',
      'Season well with pepper and salt.',
    ],
    tips: ['Press tofu 10 minutes for better texture.'],
    related: ['goal-paneer-bhurji', 'goal-egg-bhurji-light'],
    seed: 9018,
  }),

  r({
    id: 'goal-protein-khichdi',
    chapter: 'pakistani',
    title: 'Protein Khichdi',
    tagline: 'Rice, moong, and a soft egg on top.',
    story: 'Comfort bowl with a protein bump. One pot, easy on the stomach, filling enough for dinner.',
    tasteLike: 'Gentle spice, soft grain, eggy richness.',
    texture: 'Porridge-soft with a jammy egg.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 1,
    prep: 10,
    cook: 30,
    servings: 3,
    cal: 330,
    protein: 18,
    carbs: 48,
    fat: 7,
    fiber: 5,
    sugar: 2,
    tags: ['comfort', 'budget', 'one-pot'],
    dietTags: ['high-protein', 'budget', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['egg'],
    ing: [
      [100, 'g', 'rice'],
      [80, 'g', 'moong daal'],
      [1, 'tsp', 'cumin'],
      [1, 'tsp', 'turmeric'],
      [1, 'tsp', 'ghee or oil'],
      [3, '', 'eggs', 'soft-boiled to serve'],
    ],
    steps: [
      'Rinse rice and daal; cook with turmeric and salt until soft.',
      'Temper cumin in oil; stir in.',
      'Top each bowl with a soft-boiled egg.',
    ],
    tips: ['Add frozen peas in the last 5 minutes.'],
    related: ['goal-high-protein-daal', 'jia-dal-chawal'],
    seed: 9019,
  }),

  r({
    id: 'goal-oat-pancake',
    chapter: 'meals',
    title: 'Oat Protein Pancakes',
    tagline: 'Blended oats, egg whites, no flour bag.',
    story: 'Pancake Sunday without the sugar crash. Blender batter, skillet, yogurt on top.',
    tasteLike: 'Mild oat, lightly sweet banana.',
    texture: 'Soft, slightly dense.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 8,
    cook: 12,
    servings: 2,
    cal: 280,
    protein: 20,
    carbs: 36,
    fat: 6,
    fiber: 5,
    sugar: 8,
    tags: ['breakfast', 'high-protein', 'vegetarian'],
    dietTags: ['breakfast', 'high-protein', 'vegetarian', 'budget'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['egg', 'dairy', 'gluten'],
    ing: [
      [80, 'g', 'rolled oats'],
      [3, '', 'egg whites'],
      [1, '', 'egg'],
      [1, '', 'banana'],
      [50, 'g', 'yogurt'],
      [1, 'tsp', 'baking powder'],
    ],
    steps: [
      'Blend all ingredients to a batter.',
      'Cook spoonfuls on a nonstick pan until bubbles set; flip.',
      'Serve with yogurt and fruit.',
    ],
    tips: ['Rest batter 5 minutes so oats hydrate.'],
    related: ['buttermilk-pancakes', 'goal-overnight-oats'],
    seed: 9020,
  }),

  r({
    id: 'goal-turkey-keema',
    chapter: 'pakistani',
    title: 'Turkey Keema',
    tagline: 'Lean mince, peas, classic tadka spices.',
    story: 'Keema nights without the heavy afterfeel. Turkey (or chicken mince) takes the same spices.',
    tasteLike: 'Warm spice, savory mince, sweet peas.',
    texture: 'Fine crumble, soft peas.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 10,
    cook: 25,
    servings: 4,
    cal: 270,
    protein: 30,
    carbs: 12,
    fat: 11,
    fiber: 3,
    sugar: 4,
    tags: ['savory', 'high-protein', 'weeknight'],
    dietTags: ['high-protein', 'low-carb', 'gluten-free'],
    costTier: 'mid',
    allergens: [],
    ing: [
      [500, 'g', 'turkey mince', 'or chicken'],
      [1, '', 'onion', 'chopped'],
      [2, 'tbsp', 'ginger-garlic paste'],
      [100, 'g', 'peas'],
      [1, 'tsp', 'garam masala'],
      [1, 'tbsp', 'oil'],
    ],
    steps: [
      'Sauté onion in oil; add paste and mince; brown well.',
      'Add spices and a splash of water; simmer.',
      'Stir in peas; cook until tender.',
    ],
    tips: ['Serve with salad instead of rice some nights.'],
    related: ['goal-chapli-bowl', 'ff-qeema-naan'],
    seed: 9021,
  }),

  r({
    id: 'goal-grilled-fish-masala',
    chapter: 'meals',
    title: 'Grilled Fish Masala',
    tagline: 'Spice-rubbed fillets, grill or pan.',
    story: 'Fast protein dinner. Rub, rest, sear — lemon at the end.',
    tasteLike: 'Chili-cumin crust, clean fish.',
    texture: 'Flaky, lightly crisp skin.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 10,
    cook: 12,
    servings: 2,
    cal: 260,
    protein: 34,
    carbs: 4,
    fat: 11,
    fiber: 1,
    sugar: 1,
    tags: ['savory', 'high-protein', 'quick'],
    dietTags: ['high-protein', 'low-carb', 'low-cal', 'gluten-free'],
    costTier: 'mid',
    allergens: ['fish'],
    ing: [
      [400, 'g', 'white fish fillets'],
      [1, 'tsp', 'red chili'],
      [1, 'tsp', 'cumin'],
      [1, 'tsp', 'turmeric'],
      [1, 'tbsp', 'oil'],
      [1, '', 'lemon'],
    ],
    steps: [
      'Rub fish with spices, salt, and oil; rest 10 minutes.',
      ['Grill or pan-sear until just opaque.', 600],
      'Finish with lemon.',
    ],
    tips: ['Don’t flip too early — wait for a crust.'],
    related: ['sheet-pan-salmon', 'ff-fish-tikka'],
    seed: 9022,
  }),

  r({
    id: 'goal-cottage-cheese-toast',
    chapter: 'snacks',
    title: 'Cottage Cheese Toast',
    tagline: 'Protein toast with tomato and pepper.',
    story: 'Snack that behaves like breakfast. Toast, cottage cheese, cracked pepper — done.',
    tasteLike: 'Mild cheese, toasted bread, tomato.',
    texture: 'Crunchy toast, creamy topping.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 5,
    cook: 3,
    servings: 1,
    cal: 270,
    protein: 20,
    carbs: 28,
    fat: 8,
    fiber: 3,
    sugar: 4,
    tags: ['snack', 'breakfast', 'vegetarian'],
    dietTags: ['breakfast', 'high-protein', 'vegetarian', 'budget'],
    costTier: 'budget',
    allergens: ['dairy', 'gluten'],
    ing: [
      [2, 'slices', 'wholemeal bread'],
      [120, 'g', 'cottage cheese'],
      [1, '', 'tomato', 'sliced'],
      [null, '', 'black pepper'],
      [null, '', 'chili flakes', 'optional'],
    ],
    steps: [
      'Toast bread.',
      'Spread cottage cheese; top with tomato and pepper.',
    ],
    tips: ['Add cucumber for more crunch.'],
    related: ['goal-greek-yogurt-bowl', 'bruschetta'],
    seed: 9023,
  }),

  r({
    id: 'goal-lentil-soup-light',
    chapter: 'meals',
    title: 'Light Lentil Soup',
    tagline: 'Masoor broth with veg, barely any oil.',
    story: 'Soup night when we want warm and light. Blend half for body without cream.',
    tasteLike: 'Earthy lentil, carrot sweetness, cumin.',
    texture: 'Smooth-brothy with soft veg.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 1,
    prep: 10,
    cook: 35,
    servings: 4,
    cal: 200,
    protein: 13,
    carbs: 32,
    fat: 3,
    fiber: 9,
    sugar: 5,
    tags: ['soup', 'vegetarian', 'budget'],
    dietTags: ['vegetarian', 'low-cal', 'budget', 'high-protein', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: [],
    ing: [
      [180, 'g', 'masoor daal'],
      [2, '', 'carrots', 'chopped'],
      [1, '', 'onion', 'chopped'],
      [1, 'tsp', 'cumin'],
      [1, 'tsp', 'oil'],
      [1.2, 'L', 'water or stock'],
    ],
    steps: [
      'Sauté onion and cumin in oil; add carrot and daal.',
      'Add water; simmer until soft.',
      'Blend half; return; season.',
    ],
    tips: ['Lemon at the table wakes it up.'],
    related: ['goal-high-protein-daal', 'minestrone'],
    seed: 9024,
  }),

  r({
    id: 'goal-chicken-shashlik-bowl',
    chapter: 'meals',
    title: 'Chicken Shashlik Bowl',
    tagline: 'Skewered veg and chicken over brown rice.',
    story: 'Restaurant memory, home macros. Grill the skewers; skip the heavy gravy.',
    tasteLike: 'Charred pepper, yogurt marinade, mild spice.',
    texture: 'Juicy chicken, crisp veg.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 2,
    prep: 20,
    cook: 20,
    servings: 3,
    cal: 390,
    protein: 36,
    carbs: 38,
    fat: 10,
    fiber: 5,
    sugar: 7,
    tags: ['bowl', 'high-protein', 'grill'],
    dietTags: ['high-protein', 'gluten-free'],
    costTier: 'mid',
    allergens: ['dairy'],
    ing: [
      [450, 'g', 'chicken breast', 'cubed'],
      [1, '', 'capsicum', 'chunks'],
      [1, '', 'onion', 'chunks'],
      [100, 'g', 'yogurt'],
      [1, 'tbsp', 'tikka spices'],
      [150, 'g', 'cooked brown rice', 'per serving ~50g dry'],
    ],
    steps: [
      'Marinate chicken in yogurt and spices.',
      'Thread with veg; grill or roast until cooked.',
      'Serve over brown rice with salad.',
    ],
    tips: ['Separate veg and chicken skewers if cook times differ.'],
    related: ['goal-airfryer-tikka', 'goal-chapli-bowl'],
    seed: 9025,
  }),

  r({
    id: 'goal-sprout-chaat',
    chapter: 'snacks',
    title: 'Sprout Chaat',
    tagline: 'Mixed sprouts, sev optional, lemon required.',
    story: 'Chaat energy without the fried base. Skip sev if you want it cleaner.',
    tasteLike: 'Tangy, herby, lightly spicy.',
    texture: 'Crunchy sprouts, soft potato optional.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 12,
    cook: 0,
    servings: 2,
    cal: 180,
    protein: 10,
    carbs: 28,
    fat: 3,
    fiber: 7,
    sugar: 6,
    tags: ['snack', 'vegetarian', 'light'],
    dietTags: ['vegetarian', 'low-cal', 'budget', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: [],
    ing: [
      [200, 'g', 'mixed sprouts'],
      [1, '', 'boiled potato', 'diced, optional'],
      [1, '', 'onion', 'diced'],
      [1, 'tsp', 'chaat masala'],
      [2, 'tbsp', 'mint yogurt'],
      [1, '', 'lemon'],
    ],
    steps: [
      'Toss sprouts with onion, potato, and chaat masala.',
      'Drizzle mint yogurt and lemon.',
    ],
    tips: ['A spoon of tamarind chutney if you have it.'],
    related: ['goal-chana-chaat', 'goal-moong-salad'],
    seed: 9026,
  }),

  r({
    id: 'goal-egg-white-french-toast',
    chapter: 'meals',
    title: 'Egg-White French Toast',
    tagline: 'Cinnamon toast, lighter dip.',
    story: 'Weekend treat without drowning in yolks. Whites + one yolk still brown nicely.',
    tasteLike: 'Cinnamon, toast, light sweetness.',
    texture: 'Crisp edges, custardy middle.',
    cuisine: 'Breakfast',
    difficulty: 'easy',
    prep: 8,
    cook: 10,
    servings: 2,
    cal: 260,
    protein: 18,
    carbs: 34,
    fat: 5,
    fiber: 3,
    sugar: 8,
    tags: ['breakfast', 'sweet', 'high-protein'],
    dietTags: ['breakfast', 'high-protein', 'vegetarian'],
    costTier: 'budget',
    allergens: ['egg', 'gluten', 'dairy'],
    ing: [
      [4, '', 'egg whites'],
      [1, '', 'egg'],
      [80, 'ml', 'low-fat milk'],
      [4, 'slices', 'wholemeal bread'],
      [0.5, 'tsp', 'cinnamon'],
      [1, 'tsp', 'oil or spray'],
    ],
    steps: [
      'Whisk whites, egg, milk, cinnamon, and a pinch of salt.',
      'Dip bread; cook on a lightly oiled pan until gold both sides.',
      'Serve with fruit, not syrup lakes.',
    ],
    tips: ['Stale bread soaks better.'],
    related: ['goal-oat-pancake', 'buttermilk-pancakes'],
    seed: 9027,
  }),

  r({
    id: 'goal-raita-chicken-bowl',
    chapter: 'meals',
    title: 'Raita Chicken Bowl',
    tagline: 'Grilled chicken, cucumber raita, salad.',
    story: 'Cool and filling. Raita doubles as sauce so you don’t need mayo or cream.',
    tasteLike: 'Cool yogurt, warm spice chicken.',
    texture: 'Juicy chicken, crisp cucumber.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 15,
    cook: 15,
    servings: 2,
    cal: 350,
    protein: 40,
    carbs: 12,
    fat: 14,
    fiber: 2,
    sugar: 6,
    tags: ['bowl', 'high-protein', 'low-carb'],
    dietTags: ['high-protein', 'low-carb', 'gluten-free'],
    costTier: 'mid',
    allergens: ['dairy'],
    ing: [
      [400, 'g', 'chicken breast'],
      [200, 'g', 'yogurt'],
      [1, '', 'cucumber', 'grated'],
      [1, 'tsp', 'cumin'],
      [1, 'tsp', 'oil'],
      [2, 'cups', 'salad greens'],
    ],
    steps: [
      'Season chicken; pan-sear or grill until done.',
      'Mix yogurt, cucumber, cumin, salt for raita.',
      'Slice chicken over greens; spoon raita.',
    ],
    tips: ['Squeeze grated cucumber so raita stays thick.'],
    related: ['goal-airfryer-tikka', 'goal-chicken-salad-wrap'],
    seed: 9028,
  }),

  r({
    id: 'goal-masoor-salad',
    chapter: 'snacks',
    title: 'Masoor Salad',
    tagline: 'Cold lentil salad with herbs and lemon.',
    story: 'Cook once, eat cold for days. Lentils hold dressing better than lettuce alone.',
    tasteLike: 'Earthy lentil, bright lemon, herbs.',
    texture: 'Firm lentils, soft onion.',
    cuisine: 'Fusion',
    difficulty: 'easy',
    spice: 0,
    prep: 10,
    cook: 20,
    servings: 3,
    cal: 230,
    protein: 14,
    carbs: 34,
    fat: 5,
    fiber: 10,
    sugar: 4,
    tags: ['salad', 'vegetarian', 'meal-prep'],
    dietTags: ['vegetarian', 'budget', 'high-protein', 'gluten-free', 'vegan'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: [],
    ing: [
      [180, 'g', 'masoor daal', 'cooked and cooled'],
      [0.5, '', 'red onion', 'thin'],
      [1, 'handful', 'parsley or coriander'],
      [1, 'tbsp', 'olive oil'],
      [1, '', 'lemon'],
      [1, '', 'tomato', 'diced'],
    ],
    steps: [
      'Cook daal until just tender; drain and cool.',
      'Toss with onion, tomato, herbs, oil, and lemon.',
      'Season; chill or eat room temp.',
    ],
    tips: ['Don’t overcook — salad needs bite.'],
    related: ['goal-high-protein-daal', 'goal-moong-salad'],
    seed: 9029,
  }),

  r({
    id: 'goal-airfryer-pakora',
    chapter: 'snacks',
    title: 'Air-Fryer Pakora',
    tagline: 'Onion fritters, crisp without the oil bath.',
    story: 'Chai-time craving, lighter method. Mist with oil so they still bronze.',
    tasteLike: 'Spiced besan, sweet onion.',
    texture: 'Crisp outside, soft onion.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    spice: 2,
    prep: 15,
    cook: 15,
    servings: 3,
    cal: 190,
    protein: 8,
    carbs: 24,
    fat: 7,
    fiber: 4,
    sugar: 4,
    tags: ['snack', 'vegetarian', 'air-fryer'],
    dietTags: ['vegetarian', 'budget', 'gluten-free'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: [],
    ing: [
      [100, 'g', 'besan'],
      [2, '', 'onions', 'sliced'],
      [1, 'tsp', 'ajwain'],
      [1, 'tsp', 'red chili'],
      [80, 'ml', 'water'],
      [1, 'tbsp', 'oil', 'for misting'],
    ],
    steps: [
      'Mix onions with besan, spices, and enough water to coat.',
      'Drop spoonfuls into air fryer; mist with oil.',
      ['Cook at 180°C until crisp, flipping once.', 900],
    ],
    tips: ['Don’t overcrowd or they steam.'],
    related: ['pakoras', 'goal-baked-samosa'],
    seed: 9030,
  }),

  r({
    id: 'goal-protein-paratha-light',
    chapter: 'breads',
    title: 'Light Protein Paratha',
    tagline: 'Atta + besan dough, yogurt inside.',
    story: 'Paratha mornings with a protein nudge. Besan in the dough and a yogurt smear instead of lakes of ghee.',
    tasteLike: 'Toasted wheat, mild spice.',
    texture: 'Soft layers, lightly crisp.',
    cuisine: 'Pakistani',
    difficulty: 'medium',
    spice: 1,
    prep: 20,
    cook: 15,
    servings: 3,
    cal: 290,
    protein: 12,
    carbs: 42,
    fat: 8,
    fiber: 5,
    sugar: 3,
    tags: ['bread', 'breakfast', 'vegetarian'],
    dietTags: ['breakfast', 'vegetarian', 'budget', 'high-protein'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['gluten', 'dairy'],
    ing: [
      [150, 'g', 'atta'],
      [50, 'g', 'besan'],
      [80, 'g', 'yogurt'],
      [null, '', 'water', 'as needed'],
      [1, 'tsp', 'oil', 'per paratha'],
      [null, '', 'ajwain', 'optional'],
    ],
    steps: [
      'Knead atta, besan, yogurt, and water into a soft dough; rest.',
      'Roll thin; cook on a tawa with minimal oil, pressing edges.',
      'Serve with cucumber raita.',
    ],
    tips: ['Rest dough 15 minutes for softer rolls.'],
    related: ['paratha', 'aloo-paratha', 'goal-besan-chilla'],
    seed: 9031,
  }),

  r({
    id: 'goal-yogurt-lassi-protein',
    chapter: 'snacks',
    title: 'Protein Lassi',
    tagline: 'Salted or sweet, Greek yogurt base.',
    story: 'Lassi that actually sticks with you. Greek yogurt + milk, ice, and a pinch of roasted cumin.',
    tasteLike: 'Tangy yogurt, cool spice.',
    texture: 'Frothy, pourable.',
    cuisine: 'Pakistani',
    difficulty: 'easy',
    prep: 5,
    cook: 0,
    servings: 1,
    cal: 200,
    protein: 20,
    carbs: 16,
    fat: 4,
    fiber: 0,
    sugar: 12,
    tags: ['drink', 'snack', 'high-protein'],
    dietTags: ['high-protein', 'vegetarian', 'budget', 'gluten-free', 'breakfast'],
    costTier: 'budget',
    pantryStaple: true,
    allergens: ['dairy'],
    ing: [
      [200, 'g', 'Greek yogurt'],
      [100, 'ml', 'low-fat milk'],
      [null, '', 'ice'],
      [null, '', 'salt or honey', 'to taste'],
      [0.25, 'tsp', 'roasted cumin', 'for salted'],
    ],
    steps: [
      'Blend yogurt, milk, ice, and seasoning until frothy.',
      'Pour and drink cold.',
    ],
    tips: ['Salted version is more filling than sweet for me.'],
    related: ['goal-protein-smoothie', 'goal-greek-yogurt-bowl'],
    seed: 9032,
  }),
];
