import type { Recipe } from './types';

/**
 * Optional sides — raita, chutney, kachumber. Chapter snacks.
 * Art heroes only (no lock unlock). Tags: accompaniment + serve-with.
 */

function side(partial: Omit<Recipe, 'cuisine' | 'difficulty' | 'nutrition' | 'allergens'> & {
  allergens?: string[];
  nutrition?: Recipe['nutrition'];
}): Recipe {
  return {
    cuisine: 'Pakistani',
    difficulty: 'easy',
    ...partial,
    allergens: partial.allergens ?? ['dairy'],
    nutrition: partial.nutrition ?? {
      calories: 90,
      protein: 4,
      carbs: 8,
      fat: 5,
      fiber: 1,
      sugar: 4,
    },
    spiceLevel: partial.spiceLevel ?? 1,
    prepMin: partial.prepMin ?? 10,
    cookMin: partial.cookMin ?? 0,
    servings: partial.servings ?? 4,
    tags: [...new Set([...(partial.tags ?? []), 'accompaniment', 'serve-with', 'vegetarian'])],
  };
}

export const SERVE_WITH_RECIPES: Recipe[] = [
  side({
    id: 'mint-raita',
    chapter: 'snacks',
    title: 'Mint Raita',
    tagline: 'Cool yogurt, mint, a pinch of roasted cumin.',
    story:
      'I put this on the table whenever biryani or karahi shows up. It takes five minutes and saves every spicy bite.',
    tasteLike: 'Cool, herby, gently salted.',
    texture: 'Smooth yogurt with flecks of mint.',
    allergens: ['dairy'],
    spiceLevel: 0,
    prepMin: 8,
    cookMin: 0,
    servings: 4,
    nutrition: { calories: 70, protein: 4, carbs: 5, fat: 3, fiber: 0, sugar: 4 },
    tags: ['raita', 'yogurt', 'side'],
    ingredients: [
      {
        items: [
          { quantity: 400, unit: 'g', item: 'plain yogurt', note: 'whisked smooth' },
          { quantity: 1, unit: 'handful', item: 'fresh mint', note: 'finely chopped' },
          { quantity: 0.5, unit: 'tsp', item: 'roasted cumin powder' },
          { quantity: null, unit: '', item: 'salt', note: 'to taste' },
          { quantity: 1, unit: 'pinch', item: 'chaat masala', note: 'optional' },
        ],
      },
    ],
    steps: [
      { instruction: 'Whisk the yogurt until smooth and loose.' },
      { instruction: 'Fold in mint, cumin, salt, and chaat masala if using.' },
      { instruction: 'Chill 10 minutes if you can — colder tastes brighter beside hot rice.' },
    ],
    tips: ['If yogurt is thick, loosen with a spoon of cold water or milk.'],
    related: ['cucumber-raita', 'green-chutney'],
    heroSeed: 9101,
  }),
  side({
    id: 'cucumber-raita',
    chapter: 'snacks',
    title: 'Cucumber Raita',
    tagline: 'Grated cucumber in salted yogurt.',
    story: 'The quiet cousin of mint raita — crunchier, softer spice, perfect with dum biryani.',
    tasteLike: 'Fresh, milky, lightly peppered.',
    texture: 'Creamy with juicy cucumber shreds.',
    allergens: ['dairy'],
    spiceLevel: 0,
    prepMin: 10,
    cookMin: 0,
    servings: 4,
    nutrition: { calories: 65, protein: 3, carbs: 6, fat: 3, fiber: 1, sugar: 4 },
    tags: ['raita', 'yogurt', 'side'],
    ingredients: [
      {
        items: [
          { quantity: 400, unit: 'g', item: 'plain yogurt' },
          { quantity: 1, unit: '', item: 'cucumber', note: 'grated, squeezed lightly' },
          { quantity: 0.25, unit: 'tsp', item: 'black pepper' },
          { quantity: null, unit: '', item: 'salt', note: 'to taste' },
          { quantity: 1, unit: 'tsp', item: 'lemon juice', note: 'optional' },
        ],
      },
    ],
    steps: [
      { instruction: 'Grate cucumber; squeeze out excess water so the raita stays thick.' },
      { instruction: 'Whisk yogurt; fold in cucumber, salt, pepper, and lemon if using.' },
      { instruction: 'Serve cold beside rice or grilled meat.' },
    ],
    tips: ['Salt the grated cucumber 5 minutes, then squeeze — less watery bowl.'],
    related: ['mint-raita', 'kachumber-salad'],
    heroSeed: 9102,
  }),
  side({
    id: 'boondi-raita',
    chapter: 'snacks',
    title: 'Boondi Raita',
    tagline: 'Tiny crisp gram pearls in yogurt.',
    story: 'Party raita. I add the boondi at the last minute so it stays a little crunchy.',
    tasteLike: 'Mild yogurt with toasted gram flavour.',
    texture: 'Soft yogurt, soft-crisp boondi.',
    allergens: ['dairy'],
    spiceLevel: 0,
    prepMin: 5,
    cookMin: 0,
    servings: 6,
    nutrition: { calories: 110, protein: 5, carbs: 12, fat: 5, fiber: 1, sugar: 5 },
    tags: ['raita', 'yogurt', 'side', 'festive'],
    ingredients: [
      {
        items: [
          { quantity: 500, unit: 'g', item: 'plain yogurt' },
          { quantity: 1, unit: 'cup', item: 'plain boondi' },
          { quantity: 0.5, unit: 'tsp', item: 'roasted cumin powder' },
          { quantity: null, unit: '', item: 'salt', note: 'to taste' },
          { quantity: 1, unit: 'pinch', item: 'red chili powder', note: 'optional' },
        ],
      },
    ],
    steps: [
      { instruction: 'Whisk yogurt with salt and cumin.' },
      { instruction: 'Soak boondi in warm water 2 minutes; drain well.' },
      { instruction: 'Fold boondi into yogurt just before serving; dust chili if you like.' },
    ],
    tips: ['Skip soaking for extra crunch — serve immediately.'],
    related: ['mint-raita', 'cucumber-raita'],
    heroSeed: 9103,
  }),
  side({
    id: 'green-chutney',
    chapter: 'snacks',
    title: 'Green Chutney',
    tagline: 'Coriander, mint, green chili, lemon.',
    story: 'The blender sauce that makes seekh kebab and samosas taste finished.',
    tasteLike: 'Bright, herby, sharp with chili.',
    texture: 'Loose puree, spoonable.',
    allergens: [],
    spiceLevel: 3,
    prepMin: 10,
    cookMin: 0,
    servings: 6,
    nutrition: { calories: 25, protein: 1, carbs: 4, fat: 1, fiber: 1, sugar: 1 },
    dietTags: ['vegan', 'vegetarian', 'gluten-free'],
    tags: ['chutney', 'side', 'vegan'],
    ingredients: [
      {
        items: [
          { quantity: 1, unit: 'bunch', item: 'fresh coriander' },
          { quantity: 1, unit: 'handful', item: 'fresh mint' },
          { quantity: 2, unit: '', item: 'green chilies', note: 'or to taste' },
          { quantity: 1, unit: '', item: 'garlic clove', note: 'optional' },
          { quantity: 2, unit: 'tbsp', item: 'lemon juice' },
          { quantity: null, unit: '', item: 'salt', note: 'to taste' },
          { quantity: 2, unit: 'tbsp', item: 'water', note: 'to blend' },
        ],
      },
    ],
    steps: [
      { instruction: 'Roughly chop herbs and chilies.' },
      { instruction: 'Blend with lemon, salt, garlic, and a splash of water until spoonable.' },
      { instruction: 'Taste — more lemon if flat, more chili if shy.' },
    ],
    tips: ['A spoon of yogurt calms the heat for kids.'],
    warnings: ['Raw chili — wash hands after handling.'],
    related: ['imli-chutney', 'mint-raita'],
    heroSeed: 9104,
  }),
  side({
    id: 'imli-chutney',
    chapter: 'snacks',
    title: 'Imli Chutney',
    tagline: 'Tamarind, jaggery, gentle spice.',
    story: 'Sweet-sour for chaat and fried snacks. I keep a jar in the fridge most weeks.',
    tasteLike: 'Tangy, sticky-sweet, warm spices.',
    texture: 'Pourable sauce.',
    allergens: [],
    spiceLevel: 1,
    prepMin: 5,
    cookMin: 12,
    servings: 8,
    nutrition: { calories: 45, protein: 0, carbs: 11, fat: 0, fiber: 0, sugar: 9 },
    dietTags: ['vegan', 'vegetarian', 'gluten-free'],
    tags: ['chutney', 'side', 'vegan'],
    ingredients: [
      {
        items: [
          { quantity: 80, unit: 'g', item: 'seedless tamarind pulp' },
          { quantity: 60, unit: 'g', item: 'jaggery', note: 'or brown sugar' },
          { quantity: 300, unit: 'ml', item: 'water' },
          { quantity: 0.5, unit: 'tsp', item: 'roasted cumin powder' },
          { quantity: 0.25, unit: 'tsp', item: 'red chili powder' },
          { quantity: null, unit: '', item: 'salt', note: 'to taste' },
        ],
      },
    ],
    steps: [
      { instruction: 'Simmer tamarind and water until soft; mash and strain.', durationSec: 480 },
      { instruction: 'Return liquid to pan with jaggery; dissolve on low heat.' },
      { instruction: 'Season with cumin, chili, salt; cool — it thickens as it sits.' },
    ],
    tips: ['Too sharp? More jaggery. Too thick? Splash of water.'],
    storage: 'Fridge up to a week in a clean jar.',
    related: ['green-chutney', 'kachumber-salad'],
    heroSeed: 9105,
  }),
  side({
    id: 'kachumber-salad',
    chapter: 'snacks',
    title: 'Kachumber Salad',
    tagline: 'Onion, tomato, cucumber, lemon, chili.',
    story: 'Not a raita, still a side. Cuts through qorma and nihari when you want crunch without dairy.',
    tasteLike: 'Sharp, juicy, lightly chili-warm.',
    texture: 'Crisp chopped salad.',
    allergens: [],
    spiceLevel: 2,
    prepMin: 12,
    cookMin: 0,
    servings: 4,
    nutrition: { calories: 40, protein: 1, carbs: 8, fat: 0, fiber: 2, sugar: 5 },
    dietTags: ['vegan', 'vegetarian', 'gluten-free', 'low-cal'],
    tags: ['salad', 'side', 'vegan'],
    ingredients: [
      {
        items: [
          { quantity: 1, unit: '', item: 'onion', note: 'fine dice' },
          { quantity: 2, unit: '', item: 'tomatoes', note: 'seeded, diced' },
          { quantity: 1, unit: '', item: 'cucumber', note: 'diced' },
          { quantity: 1, unit: '', item: 'green chili', note: 'optional, minced' },
          { quantity: 2, unit: 'tbsp', item: 'lemon juice' },
          { quantity: 2, unit: 'tbsp', item: 'fresh coriander', note: 'chopped' },
          { quantity: null, unit: '', item: 'salt', note: 'to taste' },
        ],
      },
    ],
    steps: [
      { instruction: 'Dice onion, tomato, and cucumber; mince chili if using.' },
      { instruction: 'Toss with lemon, coriander, and salt just before serving.' },
    ],
    tips: ['Salt at the table so it stays crunchy.'],
    related: ['cucumber-raita', 'mint-raita'],
    heroSeed: 9106,
  }),
];
