/**
 * One-shot generator for chapter fill recipes. Run: node scripts/gen-fill.mjs
 * Writes src/lib/recipes/data-fill.ts — safe to re-run (overwrites).
 */
import { writeFileSync } from 'node:fs';

const NEED = {
  baking: [
    ['banana-bread', 'Banana Bread', 'Ripe bananas, brown sugar, and a soft crumb.', 'My rescue loaf for the spotty bananas nobody wants.', 'Sweet banana and warm spice.', 'Moist, tender crumb.', 'Baking', 15, 55, 10, 280, 5, 42, 10, ['sweet', 'loaf', 'vegetarian'], ['gluten', 'egg', 'dairy'], [[3, '', 'ripe bananas'], [200, 'g', 'flour'], [100, 'g', 'brown sugar'], [80, 'ml', 'oil'], [2, '', 'eggs'], [1, 'tsp', 'baking soda']], ['Mash bananas. Whisk in sugar, oil and eggs.', 'Fold in flour and soda.', ['Bake at 175°C until a skewer comes clean.', 3300]]],
    ['lemon-drizzle', 'Lemon Drizzle Cake', 'Sharp lemon cake under a crackling sugar crust.', 'The cake I bring to every potluck — it always disappears first.', 'Bright lemon, sweet crunch.', 'Soft sponge, glassy drizzle.', 'Baking', 20, 40, 10, 320, 5, 48, 12, ['sweet', 'cake', 'vegetarian'], ['gluten', 'egg', 'dairy'], [[200, 'g', 'flour'], [200, 'g', 'sugar'], [200, 'g', 'butter'], [4, '', 'eggs'], [2, '', 'lemons', 'zest + juice']], ['Cream butter and sugar; beat in eggs.', 'Fold flour and zest; bake.', ['Bake at 170°C.', 2400], 'Poke holes and pour over lemon-sugar drizzle while warm.']],
    ['shortbread', 'Butter Shortbread', 'Three ingredients, golden and sandy.', 'Grandma’s ratio: one sugar, two butter, three flour. Still perfect.', 'Buttery and plain-sweet.', 'Sandy, snap-crisp.', 'Baking', 15, 25, 16, 140, 2, 16, 8, ['sweet', 'cookie', 'vegetarian'], ['gluten', 'dairy'], [[150, 'g', 'butter'], [75, 'g', 'caster sugar'], [225, 'g', 'flour']], ['Rub butter into flour and sugar to a dough.', 'Press into a tin, dock with a fork.', ['Bake at 160°C until pale gold.', 1500], 'Slice while warm.']],
    ['carrot-cake', 'Carrot Cake', 'Spiced carrot cake with cream-cheese frosting.', 'Birthday cake in our house — the cream cheese frosting is non-negotiable.', 'Warm spice, sweet carrot.', 'Moist crumb, lush frosting.', 'Baking', 25, 45, 12, 420, 6, 52, 20, ['sweet', 'cake', 'celebration'], ['gluten', 'egg', 'dairy'], [[250, 'g', 'flour'], [200, 'g', 'sugar'], [3, '', 'eggs'], [200, 'ml', 'oil'], [250, 'g', 'grated carrot'], [200, 'g', 'cream cheese', 'for frosting']], ['Mix wet and dry; fold in carrot.', ['Bake at 175°C.', 2700], 'Cool, then frost with sweetened cream cheese.']],
  ],
  coffee: [
    ['karak-chai', 'Karak Chai', 'Strong, milky, lightly sweet tea.', 'The roadside cup I chase — thick, fragrant, and dangerously moreish.', 'Spiced, milky, sweet.', 'Silky and hot.', 'Pakistani', 5, 10, 2, 120, 4, 14, 5, ['drink', 'tea', 'chai'], ['dairy'], [[2, 'tsp', 'loose black tea'], [300, 'ml', 'water'], [200, 'ml', 'milk'], [2, '', 'cardamom'], [2, 'tsp', 'sugar']], ['Boil tea, water and cardamom hard.', 'Add milk and sugar; simmer until the colour deepens.', 'Strain into cups.']],
    ['cold-brew', 'Cold Brew Coffee', 'Smooth coffee steeped overnight.', 'For mornings when I want coffee without bitterness — patience does the work.', 'Smooth, low-acid coffee.', 'Silky cold.', 'Café', 10, 0, 4, 5, 0, 1, 0, ['drink', 'coffee', 'iced'], [], [[100, 'g', 'coarse coffee'], [800, 'ml', 'cold water']], ['Combine coffee and water in a jar.', ['Steep in the fridge.', 43200], 'Strain through a filter; serve over ice.']],
    ['affogato', 'Affogato', 'Espresso drowning a scoop of ice cream.', 'Dessert and coffee in one spoon — my favourite cheat.', 'Bitter espresso, sweet cream.', 'Hot over cold, melting.', 'Italian', 2, 1, 1, 210, 4, 22, 12, ['drink', 'dessert', 'coffee'], ['dairy'], [[1, 'scoop', 'vanilla ice cream'], [1, 'shot', 'hot espresso']], ['Scoop ice cream into a small cup.', 'Pour espresso over and eat immediately.']],
    ['golden-latte', 'Golden Latte', 'Turmeric, ginger and warm milk.', 'My evening wind-down when coffee is too much.', 'Earthy turmeric, gentle spice.', 'Creamy and soothing.', 'Home', 5, 5, 1, 140, 6, 12, 6, ['drink', 'warm', 'vegetarian'], ['dairy'], [[250, 'ml', 'milk'], [0.5, 'tsp', 'turmeric'], [0.25, 'tsp', 'ginger'], [1, 'tsp', 'honey'], [1, 'pinch', 'black pepper']], ['Warm milk with turmeric, ginger and pepper.', 'Sweeten with honey; whisk until frothy.']],
    ['espresso-tonic', 'Espresso Tonic', 'Bitter espresso over sparkling tonic.', 'Café curiosity that became a summer habit — bright and surprising.', 'Bitter, citrusy, sparkling.', 'Fizz with a coffee float.', 'Café', 3, 1, 1, 40, 0, 8, 0, ['drink', 'coffee', 'iced'], [], [[1, 'shot', 'espresso'], [150, 'ml', 'tonic water'], [null, '', 'ice'], [1, 'slice', 'lemon']], ['Fill a glass with ice and tonic.', 'Float the espresso over; garnish with lemon.']],
    ['doodh-patti', 'Doodh Patti', 'Milk tea boiled the old way.', 'Mum’s method: tea and milk cooked together until they become one.', 'Milky, strong, comforting.', 'Hot and creamy.', 'Pakistani', 5, 12, 2, 130, 5, 12, 6, ['drink', 'tea', 'chai'], ['dairy'], [[2, 'tsp', 'tea leaves'], [400, 'ml', 'full-fat milk'], [2, 'tsp', 'sugar']], ['Bring milk to a simmer with tea.', 'Boil gently until the colour is deep pink-brown.', 'Strain and serve.']],
  ],
  italian: [
    ['cacio-e-pepe', 'Cacio e Pepe', 'Pasta, pecorino, and a lot of pepper.', 'Roman simplicity — if the emulsion holds, you feel like a genius.', 'Salty cheese, hot pepper.', 'Silky sauce clinging to pasta.', 'Italian', 5, 15, 2, 520, 22, 60, 22, ['savory', 'pasta', 'vegetarian'], ['gluten', 'dairy'], [[200, 'g', 'spaghetti'], [80, 'g', 'pecorino', 'finely grated'], [2, 'tsp', 'black pepper'], [null, '', 'pasta water']], ['Toast pepper in a pan.', 'Cook pasta; reserve water.', 'Emulsify cheese with pasta water off-heat; toss with pasta and pepper.']],
    ['margherita-pizza', 'Margherita Pizza', 'Tomato, mozzarella, basil — nothing more.', 'Prove the dough overnight and the simplest pizza becomes special.', 'Sweet tomato, milky cheese.', 'Chewy crust, blistered top.', 'Italian', 30, 12, 2, 580, 24, 72, 18, ['savory', 'pizza', 'vegetarian'], ['gluten', 'dairy'], [[250, 'g', 'pizza dough'], [120, 'g', 'passata'], [150, 'g', 'mozzarella'], [1, 'handful', 'basil'], [2, 'tbsp', 'olive oil']], ['Stretch dough thin.', 'Spread passata, tear over mozzarella.', ['Bake as hot as your oven goes.', 720], 'Finish with basil and oil.']],
    ['aglio-olio', 'Aglio e Olio', 'Garlic, chili and olive oil pasta.', 'Midnight pasta. Ready before the kettle boils for tea.', 'Garlicky, gently hot.', 'Silky oil-coated strands.', 'Italian', 5, 12, 2, 480, 14, 58, 20, ['savory', 'pasta', 'quick'], ['gluten'], [[200, 'g', 'spaghetti'], [4, '', 'garlic cloves'], [1, 'tsp', 'chili flakes'], [4, 'tbsp', 'olive oil'], [1, 'handful', 'parsley']], ['Cook pasta.', 'Gently fry garlic and chili in oil — pale gold only.', 'Toss with pasta, parsley and a splash of water.']],
    ['osso-buco', 'Osso Buco', 'Braised veal shanks with gremolata.', 'Sunday patience — the marrow is the prize.', 'Deep, savoury, lemon-bright finish.', 'Falling-apart tender.', 'Italian', 25, 150, 4, 620, 48, 18, 32, ['savory', 'braise', 'festive'], [], [[4, '', 'veal shanks'], [1, '', 'onion'], [2, '', 'carrots'], [200, 'ml', 'white wine'], [400, 'ml', 'stock'], [1, '', 'lemon', 'zest for gremolata']], ['Brown the shanks; soften vegetables.', 'Deglaze with wine; add stock.', ['Braise covered until tender.', 9000], 'Serve with lemon-garlic-parsley gremolata.']],
    ['minestrone', 'Minestrone', 'Vegetable soup that eats like a meal.', 'Whatever is in the fridge becomes dinner — that’s the point.', 'Savoury, herby, tomato-warm.', 'Brothy with soft vegetables.', 'Italian', 15, 35, 6, 220, 8, 34, 6, ['savory', 'soup', 'vegetarian'], [], [[1, '', 'onion'], [2, '', 'carrots'], [2, '', 'celery sticks'], [400, 'g', 'tinned tomatoes'], [100, 'g', 'small pasta'], [1, 'tin', 'beans']], ['Soften the soffritto.', 'Add tomatoes and water; simmer.', 'Add pasta and beans near the end.']],
    ['tiramisu-cups', 'Tiramisu Cups', 'Individual tiramisu in glasses.', 'Same joy as the classic, no slicing — perfect for guests.', 'Coffee, cocoa, creamy mascarpone.', 'Soft, layered, chilled.', 'Italian', 25, 0, 6, 380, 7, 36, 24, ['sweet', 'dessert', 'make-ahead'], ['dairy', 'egg', 'gluten'], [[250, 'g', 'mascarpone'], [3, '', 'eggs'], [80, 'g', 'sugar'], [200, 'ml', 'espresso'], [20, '', 'savoiardi'], [null, '', 'cocoa']], ['Whip yolks with sugar; fold mascarpone; fold whipped whites.', 'Dip biscuits in espresso; layer in cups.', ['Chill.', 14400], 'Dust with cocoa.']],
    ['pesto-gnocchi', 'Pesto Gnocchi', 'Soft gnocchi tossed in bright basil pesto.', 'Weeknight luxury — gnocchi boil in two minutes.', 'Herby, garlicky, nutty.', 'Pillowy dumplings.', 'Italian', 10, 5, 3, 520, 14, 58, 26, ['savory', 'pasta', 'vegetarian'], ['gluten', 'dairy', 'nuts'], [[500, 'g', 'gnocchi'], [4, 'tbsp', 'basil pesto'], [2, 'tbsp', 'pasta water'], [null, '', 'parmesan']], ['Boil gnocchi until they float.', 'Toss with pesto loosened by pasta water.', 'Finish with parmesan.']],
    ['chicken-parmigiana', 'Chicken Parmigiana', 'Breaded chicken under tomato and mozzarella.', 'The Italian-American hug on a plate — always a crowd-pleaser.', 'Savoury, cheesy, tomato-sweet.', 'Crisp crumb, stretchy cheese.', 'Italian', 25, 30, 4, 640, 42, 38, 32, ['savory', 'chicken', 'baked'], ['gluten', 'dairy', 'egg'], [[4, '', 'chicken breasts'], [150, 'g', 'breadcrumbs'], [2, '', 'eggs'], [300, 'ml', 'passata'], [200, 'g', 'mozzarella']], ['Bread the chicken; pan-fry until golden.', 'Top with passata and mozzarella.', ['Bake until bubbling.', 900]]],
    ['bruschetta', 'Tomato Bruschetta', 'Garlic toast piled with ripe tomatoes.', 'Summer on bread. Only make it when tomatoes are actually good.', 'Fresh tomato, basil, olive oil.', 'Crisp toast, juicy topping.', 'Italian', 15, 5, 4, 220, 6, 28, 10, ['savory', 'starter', 'vegetarian'], ['gluten'], [[4, 'slices', 'sourdough'], [4, '', 'ripe tomatoes'], [1, '', 'garlic clove'], [1, 'handful', 'basil'], [3, 'tbsp', 'olive oil']], ['Toast the bread; rub with garlic.', 'Toss chopped tomatoes with oil, salt and basil.', 'Pile onto toast and serve at once.']],
  ],
  desserts: [
    ['chocolate-mousse', 'Chocolate Mousse', 'Airy dark chocolate mousse.', 'Five ingredients, a whisk, and silence while it sets.', 'Deep chocolate, lightly sweet.', 'Cloud-light, rich.', 'French', 20, 0, 4, 340, 6, 22, 26, ['sweet', 'chocolate', 'make-ahead'], ['dairy', 'egg'], [[200, 'g', 'dark chocolate'], [3, '', 'eggs'], [2, 'tbsp', 'sugar'], [150, 'ml', 'cream']], ['Melt chocolate; cool slightly.', 'Fold in yolks, then whipped whites and cream.', ['Chill.', 10800]]],
    ['fruit-tart', 'Fresh Fruit Tart', 'Crisp pastry, pastry cream, glazed fruit.', 'Looks bakery — tastes like a celebration.', 'Vanilla cream, bright fruit.', 'Shatter-crisp shell.', 'French', 40, 25, 8, 320, 5, 42, 14, ['sweet', 'tart', 'celebration'], ['gluten', 'dairy', 'egg'], [[1, '', 'sweet pastry shell'], [400, 'ml', 'pastry cream'], [400, 'g', 'mixed fruit'], [3, 'tbsp', 'apricot jam', 'warmed']], ['Blind-bake the shell.', 'Fill with cold pastry cream.', 'Arrange fruit; brush with jam.']],
    ['rice-pudding', 'Creamy Rice Pudding', 'Slow-cooked rice in sweet milk.', 'Comfort in a bowl — cinnamon on top is mandatory.', 'Milky, vanilla-sweet.', 'Thick and creamy.', 'Home', 10, 50, 6, 280, 7, 42, 8, ['sweet', 'comfort', 'vegetarian'], ['dairy'], [[100, 'g', 'short-grain rice'], [800, 'ml', 'milk'], [60, 'g', 'sugar'], [1, '', 'vanilla pod'], [1, 'pinch', 'cinnamon']], ['Simmer rice in milk with vanilla.', ['Cook low until thick.', 3000], 'Sweeten; dust with cinnamon.']],
    ['panna-cotta', 'Vanilla Panna Cotta', 'Silky set cream with berry sauce.', 'Make-ahead dessert that always feels fancy.', 'Vanilla cream, tart berries.', 'Jiggly, smooth.', 'Italian', 15, 5, 4, 310, 4, 22, 24, ['sweet', 'make-ahead', 'elegant'], ['dairy'], [[500, 'ml', 'cream'], [50, 'g', 'sugar'], [2, 'tsp', 'vanilla'], [2, 'tsp', 'gelatin'], [200, 'g', 'berries']], ['Bloom gelatin.', 'Warm cream with sugar and vanilla; dissolve gelatin.', ['Chill in moulds.', 14400], 'Serve with crushed berries.']],
    ['baklava', 'Baklava', 'Layered filo, nuts, and honey syrup.', 'Sticky fingers worth every sheet of filo.', 'Honey-sweet, nutty, spiced.', 'Shatter layers, sticky syrup.', 'Middle Eastern', 40, 35, 20, 280, 5, 32, 16, ['sweet', 'pastry', 'festive'], ['gluten', 'nuts', 'dairy'], [[20, 'sheets', 'filo'], [200, 'g', 'mixed nuts'], [150, 'g', 'butter', 'melted'], [200, 'g', 'sugar', 'for syrup'], [100, 'g', 'honey']], ['Layer buttered filo with nuts.', ['Bake until deep gold.', 2100], 'Pour cold syrup over hot baklava.']],
    ['cheesecake', 'Baked Cheesecake', 'Dense, vanilla cheesecake on a biscuit base.', 'The one that cracks if you rush the cool — patience pays.', 'Tangy cream cheese, vanilla.', 'Dense and creamy.', 'American', 25, 60, 12, 420, 8, 34, 28, ['sweet', 'cake', 'celebration'], ['gluten', 'dairy', 'egg'], [[250, 'g', 'digestive biscuits'], [100, 'g', 'butter'], [600, 'g', 'cream cheese'], [150, 'g', 'sugar'], [3, '', 'eggs']], ['Press biscuit base; chill.', 'Beat filling; pour over.', ['Bake at 160°C in a water bath.', 3600], 'Cool slowly in the oven with the door ajar.']],
    ['churros', 'Churros', 'Fried dough ridges rolled in cinnamon sugar.', 'Fairground energy in your own kitchen.', 'Cinnamon-sugar sweet.', 'Crisp outside, soft inside.', 'Spanish', 20, 15, 6, 320, 5, 40, 14, ['sweet', 'fried', 'fun'], ['gluten', 'egg', 'dairy'], [[250, 'ml', 'water'], [100, 'g', 'butter'], [150, 'g', 'flour'], [2, '', 'eggs'], [null, '', 'cinnamon sugar'], [null, '', 'oil', 'to fry']], ['Boil water and butter; beat in flour, then eggs.', 'Pipe into hot oil.', ['Fry until deep gold.', 480], 'Toss in cinnamon sugar.']],
    ['mochi-ice', 'Mochi Ice Cream', 'Chewy rice dough around ice cream.', 'A little project — freeze the ice cream scoops first.', 'Sweet rice, cold cream.', 'Chewy shell, frozen centre.', 'Japanese', 40, 0, 8, 180, 2, 28, 6, ['sweet', 'frozen', 'fun'], ['dairy'], [[100, 'g', 'glutinous rice flour'], [40, 'g', 'sugar'], [140, 'ml', 'water'], [8, 'scoops', 'ice cream', 'pre-frozen hard'], [null, '', 'cornflour', 'for dusting']], ['Microwave rice flour, sugar and water until translucent.', 'Roll thin; wrap around hard ice cream scoops.', 'Freeze until firm.']],
    ['apple-crumble', 'Apple Crumble', 'Soft spiced apples under a buttery rubble.', 'The smell of autumn. Serve with cold cream.', 'Warm apple, brown sugar.', 'Soft fruit, crunchy top.', 'British', 20, 40, 6, 360, 4, 52, 16, ['sweet', 'comfort', 'baked'], ['gluten', 'dairy'], [[6, '', 'apples'], [50, 'g', 'sugar'], [1, 'tsp', 'cinnamon'], [150, 'g', 'flour'], [100, 'g', 'butter'], [80, 'g', 'brown sugar']], ['Toss apples with sugar and cinnamon in a dish.', 'Rub butter into flour and sugar; scatter on top.', ['Bake at 180°C until bubbling and gold.', 2400]]],
    ['fudge', 'Chocolate Fudge', 'Square, set chocolate fudge.', 'Gift tin material — wraps beautifully.', 'Deep chocolate, sweet.', 'Soft-set, dense.', 'Home', 15, 15, 24, 140, 1, 18, 7, ['sweet', 'candy', 'gift'], ['dairy'], [[400, 'g', 'condensed milk'], [300, 'g', 'dark chocolate'], [1, 'tsp', 'vanilla'], [1, 'pinch', 'salt']], ['Melt condensed milk and chocolate gently.', 'Stir in vanilla and salt; pour into a tin.', ['Set.', 10800], 'Cut into squares.']],
  ],
  breads: [
    ['naan', 'Soft Naan', 'Pillowy flatbreads with blistered bubbles.', 'The bread that makes every curry better — cook in a screaming-hot pan.', 'Yeasty, lightly tangy.', 'Soft with charred spots.', 'Pakistani', 20, 20, 8, 220, 7, 38, 5, ['bread', 'flatbread', 'vegetarian'], ['gluten', 'dairy'], [[350, 'g', 'flour'], [7, 'g', 'yeast'], [120, 'ml', 'warm milk'], [120, 'g', 'yogurt'], [1, 'tsp', 'sugar'], [1, 'tsp', 'salt']], ['Knead a soft dough; rise until doubled.', 'Divide, roll oval, and cook in a hot dry pan.', 'Brush with butter.']],
    ['paratha', 'Flaky Paratha', 'Layered, pan-fried flatbread.', 'Breakfast with aioli eggs — or just butter and hush.', 'Buttery, wheaty.', 'Flaky and crisp-edged.', 'Pakistani', 25, 20, 6, 260, 6, 34, 12, ['bread', 'flatbread', 'breakfast'], ['gluten', 'dairy'], [[300, 'g', 'flour'], [180, 'ml', 'water'], [1, 'tsp', 'salt'], [60, 'g', 'ghee']], ['Knead dough; rest.', 'Roll, smear ghee, pleat and coil; roll again.', 'Fry on a hot tawa with more ghee until layered and gold.']],
    ['pita', 'Pita Bread', 'Pocket flatbreads that puff in the oven.', 'Stuff them, tear them, scoop with them.', 'Mild wheat.', 'Soft with a hollow pocket.', 'Middle Eastern', 20, 10, 8, 180, 6, 36, 2, ['bread', 'flatbread', 'vegetarian'], ['gluten'], [[350, 'g', 'flour'], [7, 'g', 'yeast'], [220, 'ml', 'warm water'], [1, 'tsp', 'salt'], [1, 'tsp', 'sugar']], ['Knead and rise.', 'Roll rounds; rest 10 minutes.', ['Bake on a screaming-hot stone until puffed.', 300]]],
    ['baguette', 'Everyday Baguette', 'Crusty stick bread with an open crumb.', 'Steam in the oven — that’s the crackle secret.', 'Wheaty, mild.', 'Crackly crust, airy crumb.', 'French', 25, 25, 2, 260, 9, 52, 1, ['bread', 'crusty'], ['gluten'], [[500, 'g', 'bread flour'], [10, 'g', 'salt'], [7, 'g', 'yeast'], [350, 'ml', 'water']], ['Mix, knead, and bulk-ferment.', 'Shape batards; prove.', ['Bake at 240°C with steam.', 1500]]],
    ['brioche', 'Brioche Loaf', 'Enriched, golden, feather-soft bread.', 'Toast it, French-toast it, or eat it warm with jam.', 'Buttery and gently sweet.', 'Feather-soft crumb.', 'French', 40, 30, 12, 240, 6, 28, 12, ['bread', 'enriched', 'vegetarian'], ['gluten', 'egg', 'dairy'], [[350, 'g', 'flour'], [50, 'g', 'sugar'], [7, 'g', 'yeast'], [3, '', 'eggs'], [150, 'g', 'butter'], [1, 'tsp', 'salt']], ['Mix dough; knead in soft butter.', 'Cold-prove overnight.', 'Shape, prove, egg-wash.', ['Bake at 180°C.', 1800]]],
    ['ciabatta', 'Ciabatta', 'Open-crumb Italian slipper loaf.', 'Wet dough, gentle hands — don’t punch the air out.', 'Olive-oil wheat.', 'Chewy, holey crumb.', 'Italian', 30, 25, 2, 220, 8, 42, 3, ['bread', 'crusty'], ['gluten'], [[400, 'g', 'flour'], [7, 'g', 'yeast'], [320, 'ml', 'water'], [2, 'tbsp', 'olive oil'], [8, 'g', 'salt']], ['Mix a wet dough; stretch-and-fold over 2 hours.', 'Shape gently; prove.', ['Bake at 230°C with steam.', 1500]]],
    ['dinner-rolls', 'Dinner Rolls', 'Soft pull-apart rolls for the table.', 'Holiday essential — brush with butter while hot.', 'Mild, buttery.', 'Pillowy soft.', 'Home', 25, 20, 12, 160, 5, 26, 4, ['bread', 'rolls', 'vegetarian'], ['gluten', 'dairy', 'egg'], [[400, 'g', 'flour'], [7, 'g', 'yeast'], [200, 'ml', 'warm milk'], [40, 'g', 'butter'], [1, '', 'egg'], [1, 'tsp', 'salt'], [2, 'tbsp', 'sugar']], ['Knead soft dough; rise.', 'Shape balls in a tin; prove.', ['Bake at 190°C.', 1200], 'Brush with butter.']],
    ['garlic-bread', 'Garlic Bread', 'Bagged baguette under garlic butter.', 'Friday-night pasta’s best friend.', 'Garlicky, herby, salty.', 'Crisp edges, soft middle.', 'Italian', 10, 12, 6, 280, 6, 32, 14, ['bread', 'side', 'garlic'], ['gluten', 'dairy'], [[1, '', 'baguette'], [80, 'g', 'butter'], [4, '', 'garlic cloves'], [1, 'handful', 'parsley']], ['Mash butter with garlic and parsley.', 'Split baguette; spread thickly.', ['Bake at 200°C until sizzling.', 720]]],
    ['cornbread', 'Skillet Cornbread', 'Golden cornbread with crisp edges.', 'Bake it in a hot cast-iron — the crust is everything.', 'Sweet corn, buttery.', 'Tender crumb, crisp rim.', 'American', 15, 25, 8, 240, 5, 32, 10, ['bread', 'side', 'vegetarian'], ['gluten', 'egg', 'dairy'], [[150, 'g', 'cornmeal'], [100, 'g', 'flour'], [2, 'tbsp', 'sugar'], [1, '', 'egg'], [240, 'ml', 'buttermilk'], [60, 'g', 'butter']], ['Heat a skillet with butter.', 'Mix batter; pour into the hot pan.', ['Bake at 200°C.', 1500]]],
    ['bagel', 'Chewy Bagels', 'Boiled then baked — properly chewy.', 'The boil is not optional. That’s what makes a bagel a bagel.', 'Malty wheat.', 'Dense, chewy crumb.', 'American', 30, 25, 8, 280, 10, 54, 2, ['bread', 'bagel'], ['gluten'], [[450, 'g', 'bread flour'], [7, 'g', 'yeast'], [260, 'ml', 'water'], [1, 'tbsp', 'sugar'], [10, 'g', 'salt'], [1, 'tbsp', 'baking soda', 'for boil']], ['Knead stiff dough; rise.', 'Shape rings; prove.', 'Boil briefly in soda water; seed if you like.', ['Bake at 220°C.', 1200]]],
    ['roti', 'Chapati Roti', 'Everyday whole-wheat flatbread.', 'If you can make roti, you can feed anyone.', 'Toasty whole wheat.', 'Soft and pliable.', 'Pakistani', 15, 15, 8, 120, 4, 24, 1, ['bread', 'flatbread', 'everyday'], ['gluten'], [[300, 'g', 'atta flour'], [180, 'ml', 'warm water'], [0.5, 'tsp', 'salt']], ['Knead soft dough; rest 20 minutes.', 'Roll thin rounds.', 'Cook on a hot tawa; puff over open flame if you can.']],
  ],
  meals: [
    ['sheet-pan-salmon', 'Sheet-Pan Salmon', 'Salmon and vegetables, one tray.', 'Minimal washing-up dinner — my weeknight hero.', 'Savoury, lemony fish.', 'Flaky salmon, roasted veg.', 'Home', 15, 20, 4, 480, 36, 18, 28, ['savory', 'fish', 'weeknight'], ['fish'], [[4, '', 'salmon fillets'], [400, 'g', 'mixed vegetables'], [2, 'tbsp', 'olive oil'], [1, '', 'lemon']], ['Toss veg with oil on a tray; nestle salmon.', ['Roast at 200°C.', 1200], 'Finish with lemon.']],
    ['chicken-stir-fry', 'Quick Chicken Stir-Fry', 'Hot wok, crisp vegetables, glossy sauce.', 'Faster than delivery if your chopping is ready.', 'Savoury, lightly sweet.', 'Crisp-tender veg, juicy chicken.', 'Chinese', 15, 10, 4, 420, 32, 28, 16, ['savory', 'stir-fry', 'quick'], ['soy'], [[400, 'g', 'chicken', 'sliced'], [300, 'g', 'mixed vegetables'], [3, 'tbsp', 'soy sauce'], [1, 'tbsp', 'honey'], [2, '', 'garlic cloves']], ['Sear chicken hot; set aside.', 'Stir-fry vegetables.', 'Return chicken with sauce; toss 1 minute.']],
    ['veggie-curry', 'Weeknight Veggie Curry', 'Coconut curry with whatever vegetables you have.', 'Flexible on purpose — clean out the drawer.', 'Creamy coconut, gentle spice.', 'Soft vegetables in sauce.', 'Indian', 15, 25, 4, 380, 10, 32, 22, ['savory', 'curry', 'vegetarian'], [], [[1, '', 'onion'], [2, 'tbsp', 'curry paste'], [400, 'ml', 'coconut milk'], [500, 'g', 'mixed vegetables'], [1, 'tin', 'chickpeas']], ['Soften onion; fry paste.', 'Add coconut milk and vegetables.', ['Simmer until tender.', 1500], 'Stir in chickpeas to heat through.']],
    ['beef-tacos', 'Beef Tacos', 'Spiced beef in warm tortillas.', 'Build-your-own night — everyone happy.', 'Savoury, cumin-warm.', 'Soft tortilla, saucy beef.', 'Mexican', 15, 20, 4, 520, 28, 42, 24, ['savory', 'tacos', 'crowd'], ['gluten'], [[500, 'g', 'minced beef'], [2, 'tbsp', 'taco spice'], [8, '', 'tortillas'], [null, '', 'salsa, lettuce, cheese']], ['Brown beef with spice.', 'Warm tortillas.', 'Serve with toppings.']],
    ['mushroom-risotto', 'Mushroom Risotto', 'Creamy risotto with roasted mushrooms.', 'Stirring is the therapy; the cheese is the reward.', 'Earthy mushroom, parmesan.', 'Creamy, al dente rice.', 'Italian', 15, 35, 4, 520, 14, 68, 18, ['savory', 'rice', 'vegetarian'], ['dairy'], [[300, 'g', 'arborio rice'], [400, 'g', 'mushrooms'], [1, '', 'onion'], [1, 'L', 'stock'], [60, 'g', 'parmesan']], ['Sauté onion and half the mushrooms.', 'Toast rice; ladle in stock while stirring.', 'Fold in cheese and remaining roasted mushrooms.']],
    ['sausage-pasta', 'Sausage Ragu Pasta', 'Broken sausage in a quick tomato ragu.', 'Tastes like it simmered all day — it didn’t.', 'Savoury, herby tomato.', 'Rich sauce on pasta.', 'Italian', 10, 25, 4, 580, 26, 62, 24, ['savory', 'pasta', 'weeknight'], ['gluten'], [[400, 'g', 'pasta'], [400, 'g', 'sausages', 'skins removed'], [400, 'g', 'passata'], [1, '', 'onion'], [2, '', 'garlic cloves']], ['Brown sausage meat with onion.', 'Add garlic and passata; simmer.', 'Toss with pasta.']],
    ['fish-curry', 'Coconut Fish Curry', 'Gentle coconut curry with white fish.', 'Light enough for a hot evening, comforting enough for a cold one.', 'Coconut, mild spice, sweet fish.', 'Silky sauce, flaky fish.', 'South Asian', 15, 20, 4, 440, 32, 16, 26, ['savory', 'fish', 'curry'], ['fish'], [[500, 'g', 'white fish'], [400, 'ml', 'coconut milk'], [2, 'tbsp', 'curry paste'], [1, '', 'onion'], [1, '', 'tomato']], ['Soften onion; fry paste.', 'Add coconut milk and tomato; simmer.', 'Poach fish gently until just opaque.']],
    ['stuffed-peppers', 'Stuffed Peppers', 'Peppers filled with spiced rice and mince.', 'Bake until the tops catch — that’s the best bit.', 'Savoury, gently spiced.', 'Soft pepper, fluffy filling.', 'Home', 20, 40, 4, 420, 22, 38, 18, ['savory', 'baked', 'family'], [], [[4, '', 'bell peppers'], [300, 'g', 'mince'], [150, 'g', 'cooked rice'], [1, '', 'onion'], [1, 'tsp', 'cumin']], ['Brown mince with onion and cumin.', 'Mix with rice; stuff peppers.', ['Bake at 190°C.', 2400]]],
    ['thai-green-curry', 'Thai Green Curry', 'Fragrant green curry with chicken.', 'Use a good paste — homemade if you’re ambitious, jar if you’re tired.', 'Herby, spicy, coconut.', 'Sauced and aromatic.', 'Thai', 15, 20, 4, 480, 28, 18, 32, ['savory', 'curry', 'spicy'], [], [[400, 'g', 'chicken'], [3, 'tbsp', 'green curry paste'], [400, 'ml', 'coconut milk'], [100, 'g', 'green beans'], [1, 'handful', 'thai basil']], ['Fry paste in a little coconut cream.', 'Add chicken, remaining milk and beans.', ['Simmer.', 900], 'Finish with basil.']],
    ['omelette-dinner', 'Loaded Omelette', 'Eggs folded over cheese, herbs and leftovers.', 'Dinner for one that feels considered.', 'Savoury, eggy, cheesy.', 'Soft curds, filled centre.', 'Home', 10, 8, 1, 420, 28, 4, 32, ['savory', 'eggs', 'quick'], ['egg', 'dairy'], [[3, '', 'eggs'], [40, 'g', 'cheese'], [1, 'handful', 'herbs'], [null, '', 'leftover veg']], ['Beat eggs; season.', 'Cook gently in butter; add fillings.', 'Fold and slide onto a plate.']],
    ['baked-potato-bar', 'Baked Potato Bar', 'Crispy-skinned potatoes with toppings.', 'Set out bowls and let people build their own.', 'Buttery potato, salty skin.', 'Fluffy inside, crisp skin.', 'Home', 10, 70, 4, 480, 12, 62, 18, ['savory', 'vegetarian', 'crowd'], ['dairy'], [[4, '', 'large potatoes'], [null, '', 'butter, cheese, beans, tuna, salad']], ['Prick potatoes; rub with oil and salt.', ['Bake at 200°C until soft.', 4200], 'Split and load toppings.']],
    ['lentil-dal', 'Everyday Dal', 'Soft red lentils with tadka.', 'The bowl I make when I need feeding, not cooking.', 'Earthy, gently spiced.', 'Creamy lentils.', 'Pakistani', 10, 30, 4, 320, 18, 48, 6, ['savory', 'vegetarian', 'comfort'], [], [[200, 'g', 'red lentils'], [1, 'tsp', 'turmeric'], [1, '', 'onion'], [2, '', 'garlic cloves'], [1, 'tsp', 'cumin seeds'], [2, 'tbsp', 'ghee']], ['Simmer lentils with turmeric until soft.', 'Fry onion, garlic and cumin in ghee.', 'Pour the tadka over the dal.']],
  ],
  snacks: [
    ['samosas', 'Crispy Samosas', 'Spiced potato parcels, deep-fried gold.', 'Party food that never lasts a full tray.', 'Spiced potato, crispy pastry.', 'Shatter-crisp shell.', 'Pakistani', 40, 20, 20, 180, 4, 22, 8, ['savory', 'fried', 'party'], ['gluten'], [[20, '', 'samosa wrappers'], [4, '', 'potatoes', 'boiled'], [1, 'tsp', 'cumin'], [1, 'tsp', 'garam masala'], [1, 'cup', 'peas'], [null, '', 'oil', 'to fry']], ['Mash filling with spices.', 'Fill and seal triangles.', ['Fry until deep gold.', 480]]],
    ['pakoras', 'Vegetable Pakoras', 'Chickpea-battered fried vegetables.', 'Rainy-day snack with chutney and chai.', 'Spiced, fried, savoury.', 'Crisp batter, soft veg.', 'Pakistani', 20, 15, 6, 260, 8, 28, 12, ['savory', 'fried', 'vegetarian'], [], [[200, 'g', 'gram flour'], [1, '', 'onion', 'sliced'], [1, '', 'potato', 'sliced'], [1, 'tsp', 'ajwain'], [null, '', 'oil', 'to fry']], ['Make a thick spiced batter.', 'Coat vegetables; fry in batches.', 'Drain on a rack; serve hot.']],
    ['hummus-plate', 'Hummus Plate', 'Creamy hummus with warm pita and olives.', 'Put it in the middle of the table and watch it vanish.', 'Tahini, lemon, garlic.', 'Silky dip.', 'Middle Eastern', 15, 0, 6, 280, 10, 24, 16, ['savory', 'dip', 'vegetarian'], ['sesame'], [[1, 'tin', 'chickpeas'], [3, 'tbsp', 'tahini'], [1, '', 'lemon', 'juice'], [1, '', 'garlic clove'], [null, '', 'olive oil, paprika']], ['Blend chickpeas with tahini, lemon, garlic and ice water.', 'Swirl on a plate; oil and paprika.', 'Serve with pita.']],
    ['guacamole', 'Guacamole', 'Chunky avocado with lime and chili.', 'Make it to order — avocado waits for no one.', 'Lime-bright, creamy avocado.', 'Chunky and lush.', 'Mexican', 10, 0, 4, 180, 3, 10, 16, ['savory', 'dip', 'vegetarian'], [], [[3, '', 'ripe avocados'], [1, '', 'lime', 'juice'], [0.5, '', 'red onion'], [1, '', 'tomato'], [1, '', 'chili']], ['Mash avocados roughly.', 'Fold in lime, onion, tomato and chili.', 'Salt generously; serve at once.']],
    ['spring-rolls', 'Crispy Spring Rolls', 'Vegetable spring rolls, fried until blistered.', 'Dip in sweet chili and try not to burn your tongue.', 'Savoury veg, fried pastry.', 'Shatter-crisp.', 'Chinese', 30, 15, 12, 160, 4, 20, 6, ['savory', 'fried', 'party'], ['gluten'], [[12, '', 'spring roll wrappers'], [300, 'g', 'shredded vegetables'], [2, 'tbsp', 'soy sauce'], [null, '', 'oil', 'to fry']], ['Stir-fry filling; cool.', 'Roll tightly; seal with water.', ['Fry until gold.', 360]]],
    ['cheese-board', 'Lazy Cheese Board', 'Cheese, fruit, nuts, something crunchy.', 'Not cooking — assembling. Still counts.', 'Salty, sweet, varied.', 'Mixed.', 'Home', 15, 0, 6, 420, 18, 24, 28, ['savory', 'sharing', 'no-cook'], ['dairy', 'nuts'], [[300, 'g', 'assorted cheeses'], [1, 'bunch', 'grapes'], [100, 'g', 'nuts'], [1, 'handful', 'crackers'], [null, '', 'honey or jam']], ['Arrange cheeses at room temperature.', 'Add fruit, nuts, crackers and a sweet.', 'Let people pick.']],
    ['edamame', 'Salted Edamame', 'Boiled pods with flaky salt.', 'The snack that disappears during credits.', 'Salty, beany.', 'Firm pods.', 'Japanese', 5, 5, 4, 140, 12, 10, 5, ['savory', 'snack', 'vegetarian'], [], [[400, 'g', 'frozen edamame'], [1, 'tbsp', 'flaky salt']], ['Boil edamame until bright green.', 'Drain; toss with salt.', 'Serve warm.']],
    ['nachos', 'Loaded Nachos', 'Chips under cheese, salsa and jalapeños.', 'Oven, five minutes, movie night sorted.', 'Cheesy, spicy, crunchy.', 'Molten cheese on chips.', 'Mexican', 10, 8, 4, 520, 16, 48, 28, ['savory', 'sharing', 'movie-night'], ['dairy', 'gluten'], [[300, 'g', 'tortilla chips'], [200, 'g', 'grated cheese'], [null, '', 'salsa, jalapeños, sour cream']], ['Spread chips on a tray; cover with cheese.', ['Bake until melted.', 480], 'Top with salsa, jalapeños and cream.']],
    ['fruit-chaat', 'Fruit Chaat', 'Chopped fruit with chaat masala and lemon.', 'Hot-day reset — sweet, sour, salty.', 'Tangy, spicy-sweet fruit.', 'Juicy and fresh.', 'Pakistani', 15, 0, 4, 120, 2, 28, 0, ['snack', 'fruit', 'no-cook'], [], [[4, 'cups', 'mixed fruit'], [1, 'tsp', 'chaat masala'], [1, '', 'lemon', 'juice'], [1, 'pinch', 'salt']], ['Chop fruit into a bowl.', 'Toss with lemon, chaat masala and salt.', 'Serve cold.']],
    ['popcorn', 'Stovetop Popcorn', 'Proper popcorn in a pot.', 'Three ingredients. Better than any bag.', 'Buttery, salty.', 'Light and crisp.', 'Home', 5, 5, 4, 160, 3, 18, 8, ['snack', 'movie-night', 'vegetarian'], ['dairy'], [[100, 'g', 'popcorn kernels'], [2, 'tbsp', 'oil'], [30, 'g', 'butter'], [null, '', 'salt']], ['Heat oil; add kernels; cover.', 'Shake until popping slows.', 'Toss with butter and salt.']],
    ['yogurt-parfait', 'Yogurt Parfait', 'Layered yogurt, fruit and crunch.', 'Breakfast that feels like a treat — or an afternoon pick-me-up.', 'Tangy yogurt, sweet fruit.', 'Creamy with crunch.', 'Home', 10, 0, 2, 280, 12, 36, 8, ['snack', 'breakfast', 'vegetarian'], ['dairy'], [[300, 'g', 'Greek yogurt'], [150, 'g', 'fruit'], [40, 'g', 'granola'], [1, 'tbsp', 'honey']], ['Layer yogurt, fruit and granola in glasses.', 'Drizzle honey.', 'Eat soon so the granola stays crisp.']],
    ['boiled-chana', 'Masala Boiled Chana', 'Warm chickpeas with chaat spices.', 'Street-stall nostalgia in a bowl.', 'Tangy, spicy, savoury.', 'Soft chickpeas.', 'Pakistani', 10, 10, 4, 220, 10, 32, 4, ['snack', 'vegetarian', 'spicy'], [], [[2, 'tins', 'chickpeas'], [1, 'tsp', 'chaat masala'], [1, '', 'onion', 'chopped'], [1, '', 'lemon'], [1, '', 'green chili']], ['Warm chickpeas with a splash of water.', 'Toss with onion, chili, lemon and chaat masala.', 'Serve warm.']],
  ],
  chinese: [
    ['egg-fried-rice', 'Egg Fried Rice', 'Day-old rice, hot wok, fluffy eggs.', 'Cold rice only — fresh rice turns to mush.', 'Savoury, eggy, sesame.', 'Separate grains.', 'Chinese', 10, 8, 3, 420, 14, 58, 14, ['savory', 'rice', 'quick'], ['egg', 'soy'], [[400, 'g', 'cold cooked rice'], [3, '', 'eggs'], [3, 'tbsp', 'soy sauce'], [2, '', 'spring onions'], [2, 'tbsp', 'oil']], ['Scramble eggs; set aside.', 'Fry rice hot; add soy.', 'Fold eggs and spring onion through.']],
    ['sweet-sour-chicken', 'Sweet & Sour Chicken', 'Crisp chicken in bright sweet-sour sauce.', 'The takeaway classic, less neon, more flavour.', 'Sweet, tangy, savoury.', 'Crisp batter, glossy sauce.', 'Chinese', 25, 20, 4, 540, 28, 48, 24, ['savory', 'fried', 'sweet-sour'], ['gluten', 'egg'], [[400, 'g', 'chicken', 'cubed'], [100, 'g', 'cornflour'], [1, '', 'egg'], [1, '', 'pepper'], [1, '', 'onion'], [4, 'tbsp', 'sweet-sour sauce']], ['Coat chicken; fry until crisp.', 'Stir-fry pepper and onion.', 'Toss all with sauce.']],
    ['mapo-tofu', 'Mapo Tofu', 'Silken tofu in spicy chili-bean sauce.', 'Numbing, fiery, addictive — serve over rice.', 'Spicy, numbing, savoury.', 'Soft tofu, clinging sauce.', 'Chinese', 15, 15, 3, 380, 18, 12, 28, ['savory', 'spicy', 'tofu'], ['soy'], [[400, 'g', 'silken tofu'], [100, 'g', 'minced beef', 'optional'], [2, 'tbsp', 'doubanjiang'], [1, 'tsp', 'Sichuan pepper'], [2, '', 'garlic cloves']], ['Fry beef and doubanjiang.', 'Add stock; slide in tofu gently.', 'Thicken slightly; finish with Sichuan pepper.']],
    ['chow-mein', 'Vegetable Chow Mein', 'Noodles tossed with crunchy vegetables.', 'A hot pan and cold noodles — don’t overcrowd.', 'Savoury, sesame, soy.', 'Springy noodles.', 'Chinese', 15, 10, 3, 460, 14, 62, 16, ['savory', 'noodles', 'vegetarian'], ['gluten', 'soy'], [[300, 'g', 'egg noodles'], [300, 'g', 'mixed vegetables'], [3, 'tbsp', 'soy sauce'], [1, 'tbsp', 'sesame oil']], ['Boil noodles; cool.', 'Stir-fry vegetables hot.', 'Add noodles and sauces; toss hard.']],
    ['hot-sour-soup', 'Hot & Sour Soup', 'Peppery, vinegary broth with tofu and mushrooms.', 'Clears a cold and a mood.', 'Sharp vinegar, white pepper heat.', 'Brothy with soft bits.', 'Chinese', 15, 20, 4, 160, 10, 12, 6, ['savory', 'soup', 'spicy'], ['egg', 'soy'], [[1, 'L', 'stock'], [100, 'g', 'tofu'], [50, 'g', 'mushrooms'], [2, 'tbsp', 'vinegar'], [1, 'tsp', 'white pepper'], [1, '', 'egg']], ['Simmer stock with mushrooms and tofu.', 'Season with vinegar, soy and pepper.', 'Stream in beaten egg for ribbons.']],
    ['dumpling-night', 'Pork Dumplings', 'Pleated dumplings, boiled or pan-fried.', 'A rolling party — freeze what you don’t cook.', 'Porky, gingery, savoury.', 'Tender wrappers.', 'Chinese', 45, 15, 30, 80, 5, 8, 3, ['savory', 'dumplings', 'party'], ['gluten'], [[30, '', 'dumpling wrappers'], [300, 'g', 'minced pork'], [2, 'tbsp', 'ginger'], [2, 'tbsp', 'soy sauce'], [2, '', 'spring onions']], ['Mix filling; pleat dumplings.', 'Boil until they float, or potsticker-fry.', 'Serve with vinegar-soy dip.']],
    ['sesame-chicken', 'Sesame Chicken', 'Crisp chicken in sticky sesame glaze.', 'Sweeter than kung pao, friendlier for kids.', 'Sweet sesame, savoury chicken.', 'Crisp then glazed.', 'Chinese', 20, 20, 4, 560, 32, 42, 26, ['savory', 'fried', 'sweet'], ['gluten', 'sesame'], [[400, 'g', 'chicken'], [100, 'g', 'cornflour'], [3, 'tbsp', 'soy sauce'], [2, 'tbsp', 'honey'], [2, 'tbsp', 'sesame seeds']], ['Coat and fry chicken.', 'Reduce soy-honey glaze.', 'Toss chicken; finish with sesame.']],
    ['beef-broccoli', 'Beef & Broccoli', 'Velveted beef with crisp broccoli.', 'Velveting is the restaurant secret — baking soda and a short rest.', 'Savoury beef, green broccoli.', 'Tender beef, snappy veg.', 'Chinese', 20, 10, 3, 440, 34, 16, 26, ['savory', 'stir-fry', 'beef'], ['soy'], [[350, 'g', 'beef', 'sliced'], [300, 'g', 'broccoli'], [1, 'tsp', 'baking soda'], [3, 'tbsp', 'soy sauce'], [2, '', 'garlic cloves']], ['Toss beef with soda and a little water; rest 15 minutes; rinse.', 'Stir-fry beef; set aside.', 'Cook broccoli; return beef with sauce.']],
    ['spring-onion-pancake', 'Spring Onion Pancakes', 'Flaky, laminated scallion flatbreads.', 'Roll, coil, roll again — the layers are the joy.', 'Toasty onion, salty.', 'Flaky and crisp.', 'Chinese', 30, 15, 6, 220, 5, 28, 10, ['savory', 'bread', 'vegetarian'], ['gluten'], [[300, 'g', 'flour'], [180, 'ml', 'hot water'], [4, '', 'spring onions'], [3, 'tbsp', 'oil'], [1, 'tsp', 'salt']], ['Make dough with hot water; rest.', 'Brush oil, scatter onion, roll and coil; roll flat.', 'Pan-fry until blistered.']],
    ['wontons-soup', 'Wonton Soup', 'Delicate pork wontons in clear broth.', 'Comfort when someone needs looking after.', 'Light broth, gingery pork.', 'Silky wrappers.', 'Chinese', 35, 15, 4, 280, 16, 24, 8, ['savory', 'soup', 'comfort'], ['gluten'], [[24, '', 'wonton wrappers'], [250, 'g', 'minced pork'], [1, 'L', 'chicken stock'], [2, 'tbsp', 'ginger'], [2, '', 'spring onions']], ['Fill and fold wontons.', 'Simmer stock with ginger.', 'Cook wontons in the broth until they float.']],
    ['chili-garlic-noodles', 'Chili Garlic Noodles', 'Slippery noodles in chili-garlic oil.', 'Heat level: your call. I go generous.', 'Spicy, garlicky, savoury.', 'Slippery noodles.', 'Chinese', 10, 10, 2, 480, 12, 58, 20, ['savory', 'noodles', 'spicy'], ['gluten', 'soy'], [[200, 'g', 'noodles'], [4, '', 'garlic cloves'], [2, 'tbsp', 'chili oil'], [2, 'tbsp', 'soy sauce'], [1, 'tsp', 'sugar']], ['Cook noodles.', 'Sizzle garlic in chili oil.', 'Toss noodles with oil, soy and sugar.']],
    ['tea-eggs', 'Soy Tea Eggs', 'Marbled eggs steeped in spiced soy tea.', 'Make a jar for the week — snacks sorted.', 'Savoury, tea-fragrant.', 'Firm, stained whites.', 'Chinese', 15, 60, 8, 80, 6, 1, 5, ['savory', 'snack', 'make-ahead'], ['egg', 'soy'], [[8, '', 'eggs'], [400, 'ml', 'water'], [3, 'tbsp', 'soy sauce'], [2, 'tbsp', 'loose tea'], [2, '', 'star anise']], ['Boil eggs; crack shells gently all over.', 'Simmer in soy-tea spice broth.', ['Steep off heat.', 14400]]],
    ['lettuce-wraps', 'Chicken Lettuce Wraps', 'Savoury chicken mince in crisp lettuce cups.', 'Light, crunchy, gone in minutes.', 'Savoury, gingery, fresh.', 'Crisp lettuce, saucy mince.', 'Chinese', 15, 12, 4, 320, 24, 14, 18, ['savory', 'light', 'chicken'], ['soy'], [[400, 'g', 'chicken mince'], [1, 'tin', 'water chestnuts', 'chopped'], [2, 'tbsp', 'soy sauce'], [1, 'tbsp', 'hoisin'], [1, 'head', 'butter lettuce']], ['Stir-fry mince until dry and browned.', 'Add chestnuts and sauces.', 'Spoon into lettuce cups.']],
  ],
  tips: [
    ['tip-fried-onions', 'Perfect Fried Onions', 'Deep gold, never bitter.', 'The base of half my Pakistani cooking — rush them and everything tastes raw.', 'Sweet, toasty onion.', 'Crisp threads.', 'Tip', 5, 25, 1, 80, 1, 8, 5, ['tip', 'technique'], [], [[3, '', 'onions', 'sliced thin'], [null, '', 'oil', 'to shallow-fry']], ['Slice evenly so they cook together.', 'Fry on medium, stirring, until deep gold — past pale, before burnt.', 'Drain on paper; they crisp as they cool.']],
    ['tip-rice', 'Fluffy Basmati Every Time', 'Wash, soak, steam.', 'My rice rule: treat it like a guest — don’t rush it.', 'Clean, aromatic rice.', 'Separate grains.', 'Tip', 35, 15, 4, 200, 4, 44, 0, ['tip', 'rice'], [], [[2, 'cups', 'basmati'], [null, '', 'salt'], [null, '', 'water']], ['Wash until water runs clear; soak 30 minutes.', 'Boil in salted water until 70% done; drain.', 'Steam covered on low 10 minutes; rest 5 more.']],
    ['tip-knives', 'Keep Your Knives Sharp', 'A sharp knife is safer.', 'Dull knives slip. Sharpen little and often.', '—', '—', 'Tip', 5, 0, 1, 0, 0, 0, 0, ['tip', 'safety'], [], [[1, '', 'honing steel'], [1, '', 'chef’s knife']], ['Hone before each big cook — five strokes a side.', 'Stone-sharpen when honing stops helping.', 'Hand-wash and dry; never the dishwasher.']],
    ['tip-mise', 'Mise en Place', 'Chop first, then cook.', 'Especially for stir-fries — the pan won’t wait while you mince garlic.', '—', '—', 'Tip', 15, 0, 1, 0, 0, 0, 0, ['tip', 'technique'], [], [[null, '', 'bowls'], [null, '', 'your ingredients']], ['Read the whole recipe once.', 'Chop and measure into bowls.', 'Set them in cooking order by the stove.']],
    ['tip-salt', 'Salt in Layers', 'Season as you go.', 'One heavy salt at the end tastes harsh; little bits along the way taste rounded.', '—', '—', 'Tip', 1, 0, 1, 0, 0, 0, 0, ['tip', 'seasoning'], [], [[null, '', 'salt'], [null, '', 'your dish']], ['Salt onions as they soften.', 'Salt proteins before they hit the pan.', 'Taste at the end and adjust — not before.']],
    ['tip-eggs', 'Room-Temperature Eggs', 'For baking, always.', 'Cold eggs seize butter and make batters curdle. I take them out with my coffee.', '—', '—', 'Tip', 30, 0, 1, 0, 0, 0, 0, ['tip', 'baking'], ['egg'], [[null, '', 'eggs']], ['Take eggs out 30 minutes before baking.', 'In a rush: warm in a bowl of tepid water 5 minutes.', 'Never microwave an egg to warm it.']],
    ['tip-yogurt', 'Yogurt That Won’t Split', 'Temper it.', 'Hot pan + cold yogurt = grainy sauce. I ruined many qormas learning this.', '—', '—', 'Tip', 5, 0, 1, 0, 0, 0, 0, ['tip', 'technique'], ['dairy'], [[null, '', 'yogurt'], [null, '', 'a ladle of warm sauce']], ['Whisk yogurt smooth first.', 'Stir a ladle of warm (not boiling) sauce into the yogurt.', 'Then return it to the pan off the boil.']],
    ['tip-leftovers', 'Leftovers Are Ingredients', 'Tomorrow’s lunch starts tonight.', 'Cook once with a second life in mind — roast chicken becomes soup, rice becomes fried rice.', '—', '—', 'Tip', 5, 0, 1, 0, 0, 0, 0, ['tip', 'planning'], [], [[null, '', 'last night’s food']], ['Cool leftovers quickly; fridge within 2 hours.', 'Label with the day.', 'Reheat once, until steaming hot.']],
    ['tip-taste', 'Taste as You Cook', 'The recipe can’t taste for you.', 'Your tomatoes, your salt, your pan — adjust.', '—', '—', 'Tip', 1, 0, 1, 0, 0, 0, 0, ['tip', 'mindset'], [], [[null, '', 'a clean spoon']], ['Taste after each major addition.', 'Ask: salt? acid? heat? fat?', 'Fix with the smallest change that helps.']],
    ['tip-cast-iron', 'Loving Cast Iron', 'Heat, oil, never soak.', 'A good pan outlives trends. Treat it kindly.', '—', '—', 'Tip', 5, 0, 1, 0, 0, 0, 0, ['tip', 'equipment'], [], [[1, '', 'cast-iron pan'], [null, '', 'oil']], ['Preheat gradually; don’t shock cold iron with ice water.', 'Clean with salt and a wipe; thin oil while warm.', 'If it rusts: scrub, dry, re-season.']],
    ['tip-herbs', 'When to Add Herbs', 'Hard early, soft late.', 'Bay and thyme can simmer; coriander and basil die if you boil them.', '—', '—', 'Tip', 1, 0, 1, 0, 0, 0, 0, ['tip', 'flavour'], [], [[null, '', 'hard herbs'], [null, '', 'soft herbs']], ['Add woody herbs at the start.', 'Add soft herbs off the heat.', 'Stems of coriander belong in the simmer; leaves at the end.']],
    ['tip-spice', 'Bloom Your Spices', 'Oil wakes them up.', 'Raw powdered spice tastes dusty; 30 seconds in oil tastes alive.', '—', '—', 'Tip', 2, 2, 1, 0, 0, 0, 0, ['tip', 'spice'], [], [[null, '', 'whole or ground spices'], [null, '', 'oil or ghee']], ['Heat oil until it shimmers.', 'Add spices; stir until fragrant — seconds, not minutes.', 'If they burn, start over; bitter never leaves.']],
    ['tip-dough', 'Wet Dough Is Your Friend', 'Fear sticky less.', 'More water often means better crumb. Flour your hands, not the dough.', '—', '—', 'Tip', 5, 0, 1, 0, 0, 0, 0, ['tip', 'bread'], ['gluten'], [[null, '', 'dough'], [null, '', 'a scraper']], ['Resist adding fistfuls of flour to sticky dough.', 'Use a scraper and wet hands.', 'Time and folds build strength better than extra flour.']],
    ['tip-rest-meat', 'Rest the Meat', 'Juices need a minute.', 'Cut too soon and the board drinks your dinner.', '—', '—', 'Tip', 10, 0, 1, 0, 0, 0, 0, ['tip', 'meat'], [], [[null, '', 'cooked meat'], [null, '', 'foil']], ['Rest steaks 5–10 minutes; roasts 15–20.', 'Tent loosely with foil.', 'Carve against the grain.']],
    ['tip-trust', 'Trust Your Senses', 'Timers help; senses decide.', 'Colour, smell, sound — they’re older than any recipe.', '—', '—', 'Tip', 0, 0, 1, 0, 0, 0, 0, ['tip', 'mindset'], [], [[null, '', 'your attention']], ['Look for the colour the recipe promises.', 'Listen for the lively sizzle, not a weak hiss.', 'When it smells right, you’re close — taste and finish.']],
  ],
  favorites: [
    // Jia's pinned forever-recipes (unique dishes living in this chapter)
    ['jia-sunday-biryani', 'Jia’s Sunday Biryani', 'The one pot that means family is home.', 'If the house smells like this, everyone shows up without being asked.', 'Layered spice, saffron-kissed rice.', 'Fluffy rice, tender meat.', 'Pakistani', 40, 60, 8, 640, 34, 70, 24, ['favorite', 'biryani', 'festive'], ['dairy'], [[1, 'kg', 'chicken', 'bone-in'], [750, 'g', 'basmati', 'soaked'], [400, 'g', 'yogurt'], [4, '', 'fried onions'], [0.5, 'tsp', 'saffron']], ['Marinate chicken in yogurt and spices.', 'Parboil rice; layer with chicken and onions.', ['Dum-cook sealed.', 1500], 'Rest and serve from the sides.']],
    ['jia-chai-ritual', 'Jia’s Chai Ritual', 'How I actually make chai when nobody’s watching.', 'Cardamom crushed in its shell, milk boiled properly, no shortcuts.', 'Spiced, milky, exact.', 'Hot and soothing.', 'Pakistani', 5, 12, 2, 130, 4, 14, 5, ['favorite', 'chai', 'ritual'], ['dairy'], [[2, 'tsp', 'tea'], [350, 'ml', 'milk'], [100, 'ml', 'water'], [3, '', 'cardamom'], [2, 'tsp', 'sugar']], ['Crush cardamom; boil with water and tea.', 'Add milk and sugar; boil until the colour is right.', 'Strain. Sit. Sip.']],
    ['jia-cake', 'Jia’s Anytime Chocolate Cake', 'One bowl, no drama, always loved.', 'Birthdays, bad days, Tuesdays — this cake has seen them all.', 'Deep chocolate, not too sweet.', 'Tender, moist crumb.', 'Home', 15, 35, 12, 340, 5, 48, 14, ['favorite', 'cake', 'chocolate'], ['gluten', 'egg', 'dairy'], [[200, 'g', 'flour'], [40, 'g', 'cocoa'], [180, 'g', 'sugar'], [1, 'tsp', 'baking soda'], [80, 'ml', 'oil'], [240, 'ml', 'buttermilk'], [2, '', 'eggs']], ['Whisk dry; whisk wet; combine.', ['Bake at 175°C.', 2100], 'Cool in the tin 10 minutes.']],
    ['jia-karahi', 'Jia’s Weeknight Karahi', 'Karahi scaled for a Tuesday.', 'Same soul as the dhaba version, half the ceremony.', 'Tomato, ginger, heat.', 'Clinging masala.', 'Pakistani', 15, 25, 4, 480, 36, 14, 28, ['favorite', 'karahi', 'weeknight'], [], [[600, 'g', 'chicken'], [4, '', 'tomatoes'], [2, 'tbsp', 'ginger'], [4, '', 'green chilies'], [1, 'tsp', 'cumin']], ['Cook chicken with tomatoes until the oil rises.', 'Finish with ginger and chilies.', 'Rest 5 minutes before serving.']],
    ['jia-cookies', 'Jia’s Midnight Cookies', 'The cookies I bake when I can’t sleep.', 'Brown butter if I have patience; regular butter if I don’t. Both work.', 'Butterscotch-sweet.', 'Chewy centres, crisp rims.', 'Home', 20, 12, 18, 180, 2, 24, 9, ['favorite', 'cookie', 'sweet'], ['gluten', 'egg', 'dairy'], [[170, 'g', 'butter'], [150, 'g', 'brown sugar'], [1, '', 'egg'], [220, 'g', 'flour'], [150, 'g', 'chocolate chips']], ['Cream butter and sugar; beat in egg.', 'Fold flour and chips.', ['Bake at 180°C.', 720], 'Rest on the tray 5 minutes.']],
    ['jia-dal-chawal', 'Jia’s Dal Chawal', 'The plate that feels like home.', 'If I could only keep one meal, it would be this — dal, rice, a spoon of ghee.', 'Earthy, comforting.', 'Soft dal, fluffy rice.', 'Pakistani', 10, 35, 4, 420, 18, 62, 8, ['favorite', 'dal', 'comfort'], [], [[200, 'g', 'masoor dal'], [1, 'tsp', 'turmeric'], [2, 'cups', 'basmati'], [2, 'tbsp', 'ghee'], [1, 'tsp', 'cumin seeds']], ['Cook dal soft with turmeric.', 'Make a cumin tadka in ghee; pour over.', 'Serve with plain steamed rice.']],
    ['jia-salad', 'Jia’s Crunchy Salad', 'The salad that doesn’t feel like punishment.', 'Crunch, acid, fat, salt — then I’ll happily eat leaves.', 'Bright, herby, lemony.', 'Crisp and juicy.', 'Home', 15, 0, 4, 180, 4, 14, 12, ['favorite', 'salad', 'fresh'], [], [[1, 'head', 'lettuce'], [1, '', 'cucumber'], [1, 'handful', 'herbs'], [3, 'tbsp', 'olive oil'], [1, '', 'lemon']], ['Tear leaves; chop cucumber and herbs.', 'Dress with oil, lemon and salt.', 'Toss at the table.']],
    ['jia-pasta', 'Jia’s One-Pan Pasta', 'Everything in one pan, including the pasta.', 'Lazy genius energy. The starch makes its own sauce.', 'Tomato, garlic, basil.', 'Silky, saucy pasta.', 'Italian', 10, 20, 3, 480, 16, 68, 14, ['favorite', 'pasta', 'easy'], ['gluten'], [[250, 'g', 'spaghetti'], [400, 'g', 'tinned tomatoes'], [3, '', 'garlic cloves'], [1, 'L', 'water'], [1, 'handful', 'basil']], ['Put everything except basil in a wide pan.', 'Boil, stirring, until pasta is done and sauce clings.', 'Finish with basil and oil.']],
  ],
};

function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function fmtIng(ing) {
  return ing.map((row) => {
    const [q, u, item, note] = row;
    const qv = q === null || q === undefined ? 'null' : q;
    // fix accidental typos like 1' from bad data
    const uu = String(u).replace(/'/g, '');
    const it = String(item).replace(/'/g, '');
    if (note) return `[${qv}, '${esc(uu)}', '${esc(it)}', '${esc(note)}']`;
    return `[${qv}, '${esc(uu)}', '${esc(it)}']`;
  }).join(',\n        ');
}

function fmtSteps(steps) {
  return steps.map((s) => {
    if (Array.isArray(s)) return `['${esc(s[0])}', ${s[1]}]`;
    return `'${esc(s)}'`;
  }).join(',\n      ');
}

let seed = 300;
let out = `import type { ChapterId, Difficulty, Recipe } from './types';

/** Chapter fill toward ~15 recipes each + Tips wisdom + Jia's Favorites. */

type Tup = [number | null, string, string, string?];
type St = string | [string, number];

interface Mini {
  id: string;
  chapter: ChapterId;
  title: string;
  tagline: string;
  story: string;
  tasteLike: string;
  texture: string;
  cuisine: string;
  difficulty: Difficulty;
  spice?: number;
  allergens?: string[];
  prep: number;
  cook: number;
  servings: number;
  cal: number;
  protein: number;
  carbs: number;
  fat: number;
  tags: string[];
  ing: Tup[];
  steps: St[];
  tips?: string[];
  related?: string[];
  seed: number;
}

function r(x: Mini): Recipe {
  return {
    id: x.id,
    chapter: x.chapter,
    title: x.title,
    tagline: x.tagline,
    story: x.story,
    tasteLike: x.tasteLike,
    texture: x.texture,
    cuisine: x.cuisine,
    difficulty: x.difficulty,
    spiceLevel: x.spice ?? 0,
    allergens: x.allergens ?? [],
    prepMin: x.prep,
    cookMin: x.cook,
    servings: x.servings,
    nutrition: {
      calories: x.cal,
      protein: x.protein,
      carbs: x.carbs,
      fat: x.fat,
      fiber: 2,
      sugar: 4,
    },
    tags: x.tags,
    ingredients: [{ items: x.ing.map(([q, u, it, n]) => ({ quantity: q, unit: u, item: it, note: n })) }],
    steps: x.steps.map((s) => (Array.isArray(s) ? { instruction: s[0], durationSec: s[1] } : { instruction: s })),
    tips: x.tips,
    related: x.related,
    heroSeed: x.seed,
  };
}

export const FILL_RECIPES: Recipe[] = [
`;

for (const [chapter, recipes] of Object.entries(NEED)) {
  out += `\n  /* ── ${chapter} ── */\n`;
  for (const row of recipes) {
    const [id, title, tagline, story, taste, texture, cuisine, prep, cook, servings, cal, protein, carbs, fat, tags, allergens, ing, steps] = row;
    seed += 1;
    out += `  r({
    id: '${id}',
    chapter: '${chapter}',
    title: '${esc(title)}',
    tagline: '${esc(tagline)}',
    story: '${esc(story)}',
    tasteLike: '${esc(taste)}',
    texture: '${esc(texture)}',
    cuisine: '${esc(cuisine)}',
    difficulty: 'easy',
    prep: ${prep},
    cook: ${cook},
    servings: ${servings},
    cal: ${cal},
    protein: ${protein},
    carbs: ${carbs},
    fat: ${fat},
    tags: [${tags.map((t) => `'${t}'`).join(', ')}],
    allergens: [${allergens.map((t) => `'${t}'`).join(', ')}],
    ing: [
        ${fmtIng(ing)}
    ],
    steps: [
      ${fmtSteps(steps)}
    ],
    tips: ['Made with love — taste and adjust as you go.'],
    seed: ${seed},
  }),\n`;
  }
}

out += `];\n`;

writeFileSync(new URL('../src/lib/recipes/data-fill.ts', import.meta.url), out);
console.log('Wrote data-fill.ts, recipes:', Object.values(NEED).reduce((a, b) => a + b.length, 0));
