#!/usr/bin/env python3
"""
FoodFusion → Jia Cooks content archive.

Pulls WP REST catalog + HTML recipe bodies, maps to Jia chapters,
writes organized JSON under content/sources/foodfusion/.

Usage:
  python3 scripts/scrape-foodfusion.py              # catalog only
  python3 scripts/scrape-foodfusion.py --bodies 80  # + parse N recipe pages
  python3 scripts/scrape-foodfusion.py --bodies all --download-images curated
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import Counter
from html import unescape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content" / "sources" / "foodfusion"
UA = "JiaCooksResearch/1.0 (+private heirloom cookbook; contact via Capricorn)"
API = "https://foodfusion.com/wp-json/wp/v2/recipe"
PER_PAGE = 100

FRAC = {
    "½": 0.5,
    "¼": 0.25,
    "¾": 0.75,
    "⅓": 0.33,
    "⅔": 0.67,
    "⅛": 0.125,
    "⅜": 0.375,
    "⅝": 0.625,
    "⅞": 0.875,
}

CHAPTER_RULES: list[tuple[str, list[str]]] = [
    ("desserts", ["dessert", "sweet", "cake", "cookie", "pudding", "ice-cream", "mithai", "bakery"]),
    ("coffee", ["drink", "beverage", "chai", "coffee", "smoothie", "mocktail", "juice", "lassi"]),
    ("breads", ["bread", "roti", "naan", "paratha", "flatbread", "pita"]),
    ("baking", ["baked", "baking", "muffin", "brownie", "pastry"]),
    ("chinese", ["chinese", "stir-fry", "noodles", "fried-rice", "manchurian", "szechuan"]),
    ("italian", ["italian", "pasta", "pizza", "risotto", "lasagna"]),
    ("snacks", ["snack", "appetizer", "finger", "chaat", "pakora", "samosa", "roll", "wrap", "sandwich", "iftar"]),
    ("meals", ["breakfast", "brunch", "quick", "easy-meal", "one-pot", "salad", "soup"]),
    ("pakistani", ["desi", "curry", "biryani", "karahi", "nihari", "pulao", "daal", "dal", "qorma", "korma", "handi", "bbq", "tikka", "kebab", "meat", "chicken", "beef", "mutton", "fish", "vegetable", "lunch", "dinner"]),
]

SKIP_EXISTING_IDS: set[str] = set()


def load_existing_ids() -> set[str]:
    ids: set[str] = set()
    for rel in (
        "src/lib/recipes/data.ts",
        "src/lib/recipes/data-extra.ts",
        "src/lib/recipes/data-fill.ts",
        # data-foodfusion.ts omitted — regenerated by this script
    ):
        p = ROOT / rel
        if not p.exists():
            continue
        ids.update(re.findall(r"\bid:\s*'([^']+)'", p.read_text(encoding="utf-8")))
    return ids


def http_get(url: str, retries: int = 3) -> tuple[bytes, dict[str, str]]:
    last: Exception | None = None
    for i in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "*/*"})
            with urllib.request.urlopen(req, timeout=90) as r:
                headers = {k.lower(): v for k, v in r.headers.items()}
                return r.read(), headers
        except Exception as e:  # noqa: BLE001
            last = e
            time.sleep(1.5 * (i + 1))
    raise RuntimeError(f"GET failed {url}: {last}")


def strip_tags(html: str) -> str:
    t = re.sub(r"<br\s*/?>", "\n", html, flags=re.I)
    t = re.sub(r"</p>", "\n", t, flags=re.I)
    t = re.sub(r"<[^>]+>", "", t)
    return unescape(re.sub(r"\s+", " ", t)).strip()



JUNK_STEP = re.compile(
    r"food fusion|sign up|login|don.?t have an account|already an account|"
    r"happy\s*cooking|redefining|digital food|subscribe|youtube|facebook|"
    r"follow us|#HappyCooking|video portal|talk of the town|eating out habits|"
    r"share your experience|comment below|recipe in english and urdu|"
    r"pakistan.?s first digital|flavorsome treat|next talk of the town",
    re.I,
)
URDU_TOKENS = re.compile(
    r"\b(mein|ker|dein|lein|aur|per|tak|janay|phir|dal|karein|"
    r"rakh|ho\s+jay|mix\s+ker|add\s+ker|side\s+per|ubal|pheela|"
    r"laga|tayyar|kliya|tarhan|ache)\b",
    re.I,
)


def is_branding_junk(text: str) -> bool:
    """Promo / login / site chrome — never keep. Roman Urdu OK."""
    t = text.strip()
    if not t:
        return True
    if JUNK_STEP.search(t):
        return True
    # Long marketing paragraphs (English promo)
    if len(t) > 320 and not URDU_TOKENS.search(t):
        return True
    return False


def is_section_heading(text: str) -> bool:
    t = text.strip().lower().rstrip(":")
    if len(t) < 2:
        return True
    if t in ("directions", "method", "ingredients", "ajza", "tariqa", "tarika"):
        return True
    if t.startswith("directions") or t.startswith("method") or t.startswith("ingredients") or t.startswith("ajza"):
        return True
    return False


def is_roman_urdu(text: str) -> bool:
    return len(URDU_TOKENS.findall(text)) >= 2


def extract_lang_block(html: str, cls: str) -> str:
    parts = re.split(rf'class="[^"]*{re.escape(cls)}[^"]*"', html, flags=re.I)
    if len(parts) < 2:
        return ""
    chunk = parts[1]
    chunk = re.split(
        r'class="[^"]*(?:urdu-detail-ff|english-detail-ff|related|ff-brand|recipe-detail-sidebar)',
        chunk,
        maxsplit=1,
        flags=re.I,
    )[0]
    return chunk


def paras_from(html_chunk: str) -> list[str]:
    out: list[str] = []
    for p in re.findall(r"<p[^>]*>(.*?)</p>", html_chunk, re.S | re.I):
        t = strip_tags(p)
        if not t:
            continue
        if is_section_heading(t):
            continue
        if is_branding_junk(t):
            break  # real promo/login — stop
        if len(t) < 12:
            continue
        if out and out[-1].lower() == t.lower():
            continue
        out.append(t)
    return out


def pair_steps(english: list[str], urdu: list[str]) -> list[dict]:
    """English instruction + Roman Urdu tip when lengths align; else append leftover."""
    steps: list[dict] = []
    n = max(len(english), len(urdu))
    for i in range(n):
        en = english[i] if i < len(english) else None
        ur = urdu[i] if i < len(urdu) else None
        if en and ur:
            steps.append({"instruction": en, "romanUrdu": ur})
        elif en:
            steps.append({"instruction": en, "romanUrdu": None})
        elif ur:
            steps.append({"instruction": ur, "romanUrdu": None})
    return steps


def clean_steps(steps: list) -> list:
    """Accept str list (legacy) or {instruction, romanUrdu} list."""
    out = []
    for s in steps:
        if isinstance(s, dict):
            en = (s.get("instruction") or "").strip()
            ur = (s.get("romanUrdu") or s.get("tip") or "").strip() or None
            if en and is_branding_junk(en):
                break
            if ur and is_branding_junk(ur):
                ur = None
            if not en:
                continue
            out.append({"instruction": en, "romanUrdu": ur})
        else:
            t = str(s).strip()
            if is_branding_junk(t):
                break
            out.append({"instruction": t, "romanUrdu": None})
    return out




def slug_id(slug: str) -> str:
    s = slug.lower().strip()
    s = re.sub(r"-recipe(-by-food-fusion)?$", "", s)
    s = re.sub(r"[^a-z0-9-]+", "-", s)
    s = re.sub(r"-{2,}", "-", s).strip("-")
    if not s:
        s = "ff-recipe"
    if len(s) > 56:
        s = s[:56].rstrip("-")
    return f"ff-{s}"


def is_junk_row(row: dict) -> bool:
    slug = (row.get("slug") or "").lower()
    title = (row.get("title") or "").lower()
    rid = (row.get("id") or "").lower()
    if "trash" in slug or "trash" in rid or title.startswith("trashed"):
        return True
    if rid.startswith("ff-trashed") or "trashed-" in slug:
        return True
    return False


def map_chapter(class_list: list[str], title: str) -> str:
    blob = " ".join(class_list + [title]).lower()
    scores: Counter[str] = Counter()
    for chapter, keys in CHAPTER_RULES:
        for k in keys:
            if k in blob:
                scores[chapter] += 1
    if scores:
        return scores.most_common(1)[0][0]
    return "meals"


UNIT_ALT = (
    r"cups?|cup|tbs?p?|tbsp|tsp|teaspoons?|tablespoons?|kg|g|gm|grams?|"
    r"ml|ltr?|liters?|litres?|oz|lb|pcs?|pieces?|cloves?|pinch(?:es)?|"
    r"bunch(?:es)?|slices?|cans?|packets?|packs?|inch(?:es)?|"
    r"small pieces?|whole"
)

UNIT_NORM = {
    "tbsp": "tbsp", "tbs": "tbsp", "tsp": "tsp", "gm": "g", "grams": "g", "gram": "g",
    "cups": "cup", "cup": "cup", "ltr": "l", "liter": "l", "litre": "l", "liters": "l",
    "litres": "l", "pcs": "pc", "pieces": "pc", "piece": "pc", "teaspoon": "tsp",
    "teaspoons": "tsp", "tablespoon": "tbsp", "tablespoons": "tbsp", "inches": "inch",
    "inch": "inch", "small pieces": "pc", "small piece": "pc",
}


def _parse_num_token(tok: str) -> float | None:
    tok = tok.strip()
    if tok in FRAC:
        return FRAC[tok]
    m = re.match(r"^(\d+)\s*([½¼¾⅓⅔⅛⅜⅝⅞])$", tok)
    if m:
        return float(m.group(1)) + FRAC[m.group(2)]
    m = re.match(r"^(\d+(?:\.\d+)?)$", tok)
    if m:
        return float(m.group(1))
    return None


def parse_qty(raw: str) -> tuple[float | None, str, str, str | None]:
    """Parse 'Yogurt ½ cup' or '½ cup yogurt' → (qty, unit, item, note)."""
    text = unescape(raw).strip().replace("\u00a0", " ")
    note = None
    work = re.sub(r"(\d+)\s*-\s*\d+", r"\1", text)
    work = re.sub(r"(\d+)\s*&\s*([½¼¾⅓⅔⅛⅜⅝⅞])", lambda m: str(float(m.group(1)) + FRAC[m.group(2)]), work)
    work = re.sub(r"(\d+)\s*&\s*(\d+(?:/\d+)?)", r"\1", work)  # odd markup fallback
    qty: float | None = None
    unit = ""
    item = work

    trail = re.search(
        rf"^(?P<item>.+?)\s+(?P<qty>\d+\s*[½¼¾⅓⅔⅛⅜⅝⅞]|[½¼¾⅓⅔⅛⅜⅝⅞]|\d+(?:\.\d+)?)\s*(?P<unit>{UNIT_ALT})?\b\.?\s*(?P<tail>.*)$",
        work,
        re.I,
    )
    lead = re.match(
        rf"^(?P<qty>\d+\s*[½¼¾⅓⅔⅛⅜⅝⅞]|[½¼¾⅓⅔⅛⅜⅝⅞]|\d+(?:\.\d+)?)\s*(?P<unit>{UNIT_ALT})?\b\.?\s*(?P<item>.+)$",
        work,
        re.I,
    )
    use_trail = bool(trail) and bool(
        re.search(r"[A-Za-z\u0600-\u06FF)]\s+\d|[A-Za-z\u0600-\u06FF)]\s+[½¼¾⅓⅔⅛⅜⅝⅞]", work)
    )
    chosen = trail if use_trail else (lead or trail)
    if chosen:
        qty = _parse_num_token(chosen.group("qty"))
        unit_raw = (chosen.group("unit") or "").lower().strip()
        unit = UNIT_NORM.get(unit_raw, unit_raw)
        item = chosen.group("item").strip()
        if "tail" in chosen.groupdict() and chosen.group("tail"):
            tail = chosen.group("tail").strip()
            if tail and not note:
                note = tail
    if qty is None and not unit:
        item = text
    return qty, unit, item, note


def parse_body(html: str) -> dict:
    # Prefer recipe-step-direction-detail block
    block = ""
    m = re.search(
        r'id="recipe-step-direction-detail"[^>]*>(.*?)(?:id="recipe-|</article>|class="related)',
        html,
        re.S | re.I,
    )
    if m:
        block = m.group(1)
    else:
        block = html

    groups: list[dict] = []
    # Split by h4 section headings inside Ingredients area
    ing_start = re.search(r"Ingredients\s*:</", block, re.I)
    dir_start = re.search(r"(?:Directions|Method|Steps)\s*:</", block, re.I)

    ing_html = ""
    dir_html = ""
    if ing_start and dir_start and dir_start.start() > ing_start.start():
        ing_html = block[ing_start.start() : dir_start.start()]
        dir_html = block[dir_start.start() :]
    elif ing_start:
        ing_html = block[ing_start.start() :]
    else:
        # fallback: all ul.am-ing
        ing_html = block
        dir_html = block

    # ingredient groups
    parts = re.split(r"<h4[^>]*>", ing_html, flags=re.I)
    for part in parts:
        if not part.strip():
            continue
        hm = re.match(r"([^<]+)</h4>(.*)$", part, re.S | re.I)
        if hm:
            heading = strip_tags(hm.group(1)).rstrip(":")
            body = hm.group(2)
        else:
            heading = None
            body = part
        items = []
        # Prefer FoodFusion ingredient lists; fall back to bare <li>
        lis = re.findall(r'<ul[^>]*class="[^"]*am-ing[^"]*"[^>]*>(.*?)</ul>', body, re.S | re.I)
        li_htmls: list[str] = []
        if lis:
            for ul in lis:
                li_htmls.extend(re.findall(r"<li[^>]*>(.*?)</li>", ul, re.S | re.I))
        else:
            li_htmls = re.findall(r"<li[^>]*>(.*?)</li>", body, re.S | re.I)
        for li in li_htmls:
            raw = strip_tags(li)
            if not raw or len(raw) < 2:
                continue
            if raw.lower().startswith("http") or "food fusion" in raw.lower():
                continue
            qty, unit, item, note = parse_qty(raw)
            items.append(
                {
                    "quantity": qty,
                    "unit": unit,
                    "item": item,
                    "note": note,
                    "raw": raw,
                }
            )
        if items:
            groups.append({"heading": heading, "items": items})

    # Prefer lang blocks: english-detail-ff + urdu-detail-ff
    eng_chunk = extract_lang_block(html, "english-detail-ff") or dir_html
    urd_chunk = extract_lang_block(html, "urdu-detail-ff")
    english = paras_from(eng_chunk)
    # Drop ingredient-looking lead-ins from eng directions if Ingredients: leaked
    english = [e for e in english if not e.lower().startswith("ingredients")]
    urdu = paras_from(urd_chunk) if urd_chunk else []
    steps = pair_steps(english, urdu)

    # og / excerpt helpers
    og = re.search(r'property="og:image"\s+content="([^"]+)"', html)
    desc = re.search(r'property="og:description"\s+content="([^"]+)"', html)
    return {
        "ingredientGroups": groups,
        "steps": steps,
        "ogImage": og.group(1) if og else None,
        "ogDescription": unescape(desc.group(1)) if desc else None,
    }


def fetch_catalog(force: bool = False) -> list[dict]:
    OUT.mkdir(parents=True, exist_ok=True)
    catalog_path = OUT / "catalog.json"
    if catalog_path.exists() and not force:
        print(f"catalog cache hit: {catalog_path}")
        return json.loads(catalog_path.read_text(encoding="utf-8"))

    # discover total pages
    _, headers = http_get(f"{API}?per_page=1&page=1&_fields=id")
    total = int(headers.get("x-wp-total", "0"))
    pages = int(headers.get("x-wp-totalpages", "0"))
    # with per_page=100
    pages = max(1, (total + PER_PAGE - 1) // PER_PAGE)
    print(f"FoodFusion catalog: {total} recipes, {pages} pages @ {PER_PAGE}")

    rows: list[dict] = []
    for page in range(1, pages + 1):
        url = f"{API}?per_page={PER_PAGE}&page={page}&_embed=1"
        raw, _ = http_get(url)
        batch = json.loads(raw.decode("utf-8"))
        for p in batch:
            title = strip_tags(p.get("title", {}).get("rendered", ""))
            excerpt = strip_tags(p.get("excerpt", {}).get("rendered", ""))
            classes = p.get("class_list") or []
            media = None
            emb = (p.get("_embedded") or {}).get("wp:featuredmedia") or []
            if emb:
                media = emb[0].get("source_url") or emb[0].get("media_details", {}).get("sizes", {}).get(
                    "full", {}
                ).get("source_url")
            rid = slug_id(p["slug"])
            rows.append(
                {
                    "wpId": p["id"],
                    "slug": p["slug"],
                    "id": rid,
                    "title": title,
                    "excerpt": excerpt,
                    "link": p.get("link"),
                    "date": p.get("date"),
                    "modified": p.get("modified"),
                    "classList": classes,
                    "chapter": map_chapter(classes, title),
                    "imageUrl": media,
                    "source": "foodfusion",
                    "attribution": "Recipe adapted from Food Fusion (foodfusion.com). Not an official Food Fusion product.",
                }
            )
        print(f"  page {page}/{pages} (+{len(batch)}) total={len(rows)}")
        time.sleep(0.25)

    catalog_path.write_text(json.dumps(rows, indent=2, ensure_ascii=False), encoding="utf-8")
    (OUT / "catalog.meta.json").write_text(
        json.dumps({"total": len(rows), "fetchedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}, indent=2),
        encoding="utf-8",
    )
    return rows


def fetch_bodies(catalog: list[dict], limit: int | None) -> dict[str, dict]:
    bodies_dir = OUT / "recipes"
    bodies_dir.mkdir(parents=True, exist_ok=True)
    # Prefer classics / chapter diversity: sort by chapter then title
    work = list(catalog)
    if limit is not None:
        # prioritize: has image, desi-ish chapters, short slug (often classics)
        work = sorted(
            work,
            key=lambda r: (
                0 if r.get("imageUrl") else 1,
                0 if r["chapter"] in ("pakistani", "desserts", "breads", "snacks") else 1,
                len(r["slug"]),
                r["title"],
            ),
        )[:limit]

    out: dict[str, dict] = {}
    work = [r for r in work if not is_junk_row(r)]
    for i, row in enumerate(work, 1):
        path = bodies_dir / f"{row['id']}.json"
        if path.exists():
            out[row["id"]] = json.loads(path.read_text(encoding="utf-8"))
            continue
        link = row.get("link")
        if not link:
            continue
        try:
            raw, _ = http_get(link)
            html = raw.decode("utf-8", errors="ignore")
            parsed = parse_body(html)
            rec = {**row, **parsed, "scrapedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
            path.write_text(json.dumps(rec, indent=2, ensure_ascii=False), encoding="utf-8")
            out[row["id"]] = rec
            n_ing = sum(len(g["items"]) for g in parsed["ingredientGroups"])
            print(f"  [{i}/{len(work)}] {row['id']} ings={n_ing} steps={len(parsed['steps'])}")
        except Exception as e:  # noqa: BLE001
            print(f"  [{i}/{len(work)}] FAIL {row['id']}: {e}")
        time.sleep(0.35)
    return out


def write_index(catalog: list[dict]) -> None:
    by_chapter: dict[str, list[dict]] = {}
    for r in catalog:
        by_chapter.setdefault(r["chapter"], []).append(
            {"id": r["id"], "title": r["title"], "slug": r["slug"], "imageUrl": r.get("imageUrl"), "link": r.get("link")}
        )
    (OUT / "by-chapter.json").write_text(json.dumps(by_chapter, indent=2, ensure_ascii=False), encoding="utf-8")
    counts = {k: len(v) for k, v in sorted(by_chapter.items())}
    (OUT / "README.md").write_text(
        "\n".join(
            [
                "# FoodFusion source archive",
                "",
                "Private research scrape for **Jia Cooks** heirloom cookbook.",
                "",
                "## Attribution",
                "",
                "Content and images © Food Fusion / respective owners.",
                "Used here as **attributed research reference** for a private family book —",
                "not for public republication as original Jia recipes without rewrite + rights clearance.",
                "Source: https://foodfusion.com",
                "",
                "## Layout",
                "",
                "- `catalog.json` — all WP recipe cards (title, slug, chapter guess, image URL)",
                "- `by-chapter.json` — same, grouped by Jia chapter mapping",
                "- `recipes/*.json` — parsed ingredients + steps (HTML scrape)",
                "- `images/` — downloaded heroes (when `--download-images`)",
                "- `curated.json` — subset selected for app import",
                "",
                f"## Counts (chapter map)",
                "",
                *[f"- **{k}**: {v}" for k, v in counts.items()],
                "",
                f"Total catalog: **{len(catalog)}**",
                "",
            ]
        ),
        encoding="utf-8",
    )


def reparse_body_quantities(body: dict) -> dict:
    groups = []
    for g in body.get("ingredientGroups") or []:
        items = []
        for it in g.get("items") or []:
            raw = it.get("raw") or it.get("item") or ""
            qty, unit, item, note = parse_qty(raw)
            items.append({"quantity": qty, "unit": unit, "item": item, "note": note, "raw": raw})
        if items:
            groups.append({"heading": g.get("heading"), "items": items})
    return {**body, "ingredientGroups": groups}


def pick_curated(catalog: list[dict], bodies: dict[str, dict], n: int = 72) -> list[dict]:
    existing = load_existing_ids()
    title_hit = {re.sub(r"[^a-z0-9]+", "", x.lower()) for x in existing}

    scored: list[tuple[int, dict]] = []
    for row in catalog:
        if is_junk_row(row):
            continue
        body = bodies.get(row["id"])
        if not body or is_junk_row(body):
            continue
        body = reparse_body_quantities(body)
        bodies[row["id"]] = body
        n_ing = sum(len(g["items"]) for g in body.get("ingredientGroups") or [])
        clean = clean_steps(list(body.get("steps") or []))
        body = {**body, "steps": clean}
        bodies[row["id"]] = body
        n_steps = len(clean)
        if n_ing < 3 or n_ing > 60 or n_steps < 3:
            continue
        if row["id"] in existing:
            continue
        tnorm = re.sub(r"[^a-z0-9]+", "", row["title"].lower())
        if tnorm in title_hit:
            continue
        parsed_qty = sum(1 for g in body["ingredientGroups"] for it in g["items"] if it["quantity"] is not None)
        score = 0
        score += min(n_ing, 20) + min(n_steps, 15) + min(parsed_qty, 15)
        if row.get("imageUrl"):
            score += 10
        if row["chapter"] == "pakistani":
            score += 8
        elif row["chapter"] in ("desserts", "breads", "snacks", "coffee"):
            score += 5
        blob = (row["title"] + " " + row["slug"]).lower()
        for kw in ("biryani", "karahi", "nihari", "haleem", "pulao", "qorma", "korma", "tikka", "naan", "paratha", "chai", "halwa", "kheer", "gulab"):
            if kw in blob:
                score += 6
        scored.append((score, body))

    scored.sort(key=lambda x: (-x[0], x[1]["title"]))
    # chapter balance
    picked: list[dict] = []
    per_ch: Counter[str] = Counter()
    for score, body in scored:
        ch = body["chapter"]
        if per_ch[ch] >= max(6, n // 8) and ch != "pakistani":
            continue
        if per_ch[ch] >= 18:
            continue
        picked.append(body)
        per_ch[ch] += 1
        if len(picked) >= n:
            break
    return picked


def ts_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ")


def qty_ts(q: float | None) -> str:
    if q is None:
        return "null"
    if abs(q - round(q)) < 1e-9:
        return str(int(round(q)))
    return str(round(q, 2))


def emit_typescript(curated: list[dict], path: Path) -> None:
    """Emit Recipe[] — English + Roman Urdu method, Jia-voice stories, zero FoodFusion branding in UI."""
    lines: list[str] = [
        "import type { Recipe } from './types';",
        "",
        "/**",
        " * Adapted kitchen cards (English method cleaned from public FoodFusion pages).",
        " * Not a copy-paste dump — promo/login/Urdu mirrors stripped. Private heirloom use.",
        " * Regen: python3 scripts/scrape-foodfusion.py --curate 64 --emit-ts",
        " */",
        "",
        "function seed(id: string): number {",
        "  let h = 0;",
        "  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;",
        "  return h % 10000;",
        "}",
        "",
        "export const FOODFUSION_RECIPES: Recipe[] = [",
    ]

    for rec in curated:
        groups = rec.get("ingredientGroups") or []
        steps = clean_steps(list(rec.get("steps") or []))
        if len(steps) < 3:
            continue
        # nutrition placeholders (unknown) — low confidence zeros avoided; modest defaults
        prep = 20
        cook = 40
        servings = 4
        # crude allergen guess
        blob = " ".join(
            i["item"] for g in groups for i in g["items"]
        ).lower()
        allergens: list[str] = []
        if any(x in blob for x in ("milk", "cream", "butter", "yogurt", "cheese", "ghee")):
            allergens.append("dairy")
        if any(x in blob for x in ("flour", "atta", "bread", "maida", "pasta")):
            allergens.append("gluten")
        if "egg" in blob:
            allergens.append("egg")
        if any(x in blob for x in ("almond", "cashew", "pistachio", "walnut", "peanut", "nut")):
            allergens.append("nuts")

        spice = 2 if rec["chapter"] == "pakistani" else 1
        if any(x in blob for x in ("chili", "chilli", "mirch", "pepper")):
            spice = min(5, spice + 1)

        tagline = (rec.get("ogDescription") or rec.get("excerpt") or f"{rec['title']} — adapted for our kitchen.").strip()
        tagline = re.sub(r"#HappyCooking\S*", "", tagline, flags=re.I).strip()
        tagline = re.sub(r"Food Fusion", "home kitchen", tagline, flags=re.I).strip()
        if len(tagline) > 110:
            tagline = tagline[:107] + "…"
        if len(tagline) < 12:
            tagline = f"{rec['title']} — adapted for our kitchen."
        story = (
            f"A kitchen card we adapted for the book — {rec['title']}. "
            f"Cook it once, then scribble your own timings in the notes."
        )

        lines.append("  {")
        lines.append(f"    id: '{rec['id']}',")
        lines.append(f"    chapter: '{rec['chapter']}',")
        lines.append(f"    title: '{ts_escape(rec['title'])}',")
        lines.append(f"    tagline: '{ts_escape(tagline)}',")
        lines.append(f"    story: '{ts_escape(story)}',")
        lines.append(f"    cuisine: 'Pakistani',")
        lines.append(f"    difficulty: 'medium',")
        lines.append(f"    spiceLevel: {spice},")
        lines.append(f"    allergens: {json.dumps(allergens)},")
        lines.append(f"    prepMin: {prep},")
        lines.append(f"    cookMin: {cook},")
        lines.append(f"    servings: {servings},")
        lines.append(
            "    nutrition: { calories: 450, protein: 18, carbs: 40, fat: 22, fiber: 3, sugar: 6 },  // estimate — not lab-tested"
        )
        lines.append(f"    tags: ['family', 'roman-urdu', '{rec['chapter']}'],")
        lines.append("    ingredients: [")
        for g in groups:
            lines.append("      {")
            if g.get("heading"):
                lines.append(f"        heading: '{ts_escape(g['heading'])}',")
            lines.append("        items: [")
            for it in g["items"]:
                note = f", note: '{ts_escape(it['note'])}'" if it.get("note") else ""
                lines.append(
                    f"          {{ quantity: {qty_ts(it['quantity'])}, unit: '{ts_escape(it['unit'])}', item: '{ts_escape(it['item'])}'{note} }},"
                )
            lines.append("        ],")
            lines.append("      },")
        lines.append("    ],")
        lines.append("    steps: [")
        for st in steps:
            if isinstance(st, dict):
                en = st.get("instruction") or ""
                ur = st.get("romanUrdu") or ""
            else:
                en, ur = str(st), ""
            if ur:
                lines.append(
                    f"      {{ instruction: '{ts_escape(en)}', tip: '{ts_escape(ur)}' }},"
                )
            else:
                lines.append(f"      {{ instruction: '{ts_escape(en)}' }},")
        lines.append("    ],")
        lines.append(
            "    tips: ['Taste as you go — every stove runs different.', 'Swap the hero for a family photo when you cook this.'],"
        )
        lines.append(f"    heroSeed: seed('{rec['id']}'),")
        lines.append("  },")

    lines.append("];")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path} ({len(curated)} recipes)")


def download_images(curated: list[dict]) -> None:
    img_dir = OUT / "images"
    img_dir.mkdir(parents=True, exist_ok=True)
    pub = ROOT / "public" / "recipes"
    pub.mkdir(parents=True, exist_ok=True)
    # use node+sharp via small helper
    jobs = []
    for rec in curated:
        url = rec.get("ogImage") or rec.get("imageUrl")
        if not url:
            continue
        # strip query for extension guess
        jobs.append({"id": rec["id"], "url": url})
    manifest = OUT / "image-jobs.json"
    manifest.write_text(json.dumps(jobs, indent=2), encoding="utf-8")
    print(f"image jobs: {len(jobs)} → {manifest}")
    # invoke node helper
    helper = ROOT / "scripts" / "fetch-foodfusion-images.mjs"
    if helper.exists():
        import subprocess

        subprocess.check_call(["node", str(helper)], cwd=str(ROOT))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--force-catalog", action="store_true")
    ap.add_argument("--bodies", default="0", help="N | all")
    ap.add_argument("--curate", type=int, default=72)
    ap.add_argument("--download-images", action="store_true")
    ap.add_argument("--emit-ts", action="store_true")
    args = ap.parse_args()

    catalog = fetch_catalog(force=args.force_catalog)
    write_index(catalog)

    limit: int | None
    if args.bodies == "all":
        limit = None
    elif args.bodies == "0":
        limit = 0
    else:
        limit = int(args.bodies)

    bodies: dict[str, dict] = {}
    if limit != 0:
        bodies = fetch_bodies(catalog, limit)

    # load any existing bodies for curate
    bodies_dir = OUT / "recipes"
    if bodies_dir.exists():
        for p in bodies_dir.glob("*.json"):
            bodies.setdefault(p.stem, json.loads(p.read_text(encoding="utf-8")))

    curated = pick_curated(catalog, bodies, n=args.curate) if bodies else []
    if curated:
        (OUT / "curated.json").write_text(json.dumps(curated, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"curated {len(curated)}")
        ch = Counter(r["chapter"] for r in curated)
        print("  by chapter:", dict(ch))

    if args.emit_ts and curated:
        emit_typescript(curated, ROOT / "src" / "lib" / "recipes" / "data-foodfusion.ts")

    if args.download_images and curated:
        download_images(curated)

    print("done →", OUT)


if __name__ == "__main__":
    main()
